#!/bin/sh

changed=0

set_default() {
	option=$1
	value=$2

	if ! uci -q get "lanspeed.main.$option" >/dev/null; then
		uci set "lanspeed.main.$option=$value"
		changed=1
	fi
}

set_default nss_fifo_target_delay_ms 50
set_default nss_fifo_min_queue_packets 8
set_default rate_compensation_factor 1.10
set_default nss_low_rate_window_ms 18000
set_default nss_low_rate_high_watermark_bps 8000000

[ "$changed" -eq 0 ] || uci commit lanspeed
exit 0
