'use strict';
'require baseclass';

var CSS = [
	'.lanspeed-connection-detail{display:flex;flex-direction:column;gap:1em;margin:0}',
	'.lanspeed-connection-breadcrumb{display:flex;flex-wrap:wrap;align-items:center;gap:.65em}',
	'.lanspeed-connection-breadcrumb-current{font-size:.9em;opacity:.72}',
	'.lanspeed-connection-back{flex:0 0 auto}',
	'.lanspeed-connection-error{display:flex;align-items:baseline;gap:.5em;margin:0}',
	'.lanspeed-connection-error[hidden],.lanspeed-connection-empty[hidden]{display:none!important}',
	'.lanspeed-connection-identity{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(25em,1fr);gap:1.5em 2.25em;align-items:stretch}',
	'.lanspeed-connection-client{min-width:0}',
	'.lanspeed-connection-client-heading{display:flex;align-items:center;gap:1em;margin:-.38em -.48em .62em;padding:.38em .48em;min-width:0;border-radius:var(--lanspeed-radius-control);cursor:pointer;transition:box-shadow var(--lanspeed-transition)}',
	'.lanspeed-connection-client-heading:hover{background:transparent!important;background-image:none!important}',
	'.lanspeed-connection-client-heading:focus-visible{outline:0;box-shadow:var(--lanspeed-focus-ring)}',
	'.lanspeed-connection-client-heading[aria-disabled="true"]{cursor:default}',
	'.lanspeed-connection-client-heading[aria-disabled="true"]:hover{background:transparent!important}',
	'.lanspeed-connection-client-avatar{display:inline-flex;align-items:center;justify-content:center;width:3.4em;height:3.4em;flex:0 0 3.4em;border:1px solid var(--lanspeed-border);border-radius:var(--lanspeed-radius-section);background:var(--lanspeed-accent-soft);color:var(--lanspeed-accent)}',
	'.lanspeed-connection-client-device{position:relative;display:block;width:1.55em;height:1.05em;border:.14em solid currentColor;border-radius:.25em}',
	'.lanspeed-connection-client-device::before{content:"";position:absolute;left:50%;bottom:-.48em;width:.16em;height:.34em;border-radius:999px;background:currentColor;transform:translateX(-50%)}',
	'.lanspeed-connection-client-device::after{content:"";position:absolute;left:50%;bottom:-.58em;width:.85em;height:.14em;border-radius:999px;background:currentColor;transform:translateX(-50%)}',
	'.lanspeed-connection-client-title{display:flex;flex-direction:column;gap:.12em;min-width:0}',
	'.lanspeed-connection-client-kicker{font-size:.72em;font-weight:600;letter-spacing:.08em;opacity:.55}',
	'.lanspeed-connection-client-name-row{display:flex;align-items:center;gap:.42em;min-width:0}',
	'.lanspeed-connection-client-name{margin:0;font-size:1.28em;font-weight:650;line-height:1.25;overflow-wrap:anywhere}',
	'.lanspeed-connection-client-edit{flex:0 0 auto;font-size:.9em;opacity:.38;transition:opacity .15s ease}',
	'.lanspeed-connection-client-heading:focus-visible .lanspeed-connection-client-edit{opacity:.9}',
	'.lanspeed-connection-client-meta{display:grid;gap:.8em;margin:0;min-width:0}',
	'.lanspeed-connection-meta-group{display:grid;gap:.45em;min-width:0}',
	'.lanspeed-connection-meta-heading{display:flex;align-items:center;gap:.5em;min-width:0}',
	'.lanspeed-connection-meta-heading-label{font-size:.78em;font-weight:600;letter-spacing:.03em;opacity:.65}',
	'.lanspeed-connection-meta-count{display:inline-flex;align-items:center;justify-content:center;min-width:1.65em;height:1.65em;padding:0 .42em;border-radius:var(--lanspeed-radius-badge);background:var(--lanspeed-accent-soft);color:var(--lanspeed-accent);font-size:.68em;font-weight:650;font-variant-numeric:tabular-nums}',
	'.lanspeed-connection-meta-values{display:flex;flex-wrap:wrap;gap:.45em .55em;min-width:0}',
	'.lanspeed-connection-meta-ip{display:inline-flex;align-items:center;max-width:100%;padding:.4em .65em;border:1px solid var(--lanspeed-border);border-radius:var(--lanspeed-radius-control);background:var(--lanspeed-surface-muted);font-family:var(--font-mono,var(--font-monospace,ui-monospace,monospace));font-size:.86em;font-variant-numeric:tabular-nums;line-height:1.25;overflow-wrap:anywhere}',
	'.lanspeed-connection-meta-facts{display:grid;grid-template-columns:minmax(13em,1.5fr) minmax(7em,1fr);gap:.55em;min-width:0}',
	'.lanspeed-connection-meta-facts[data-count="1"]{grid-template-columns:minmax(0,1fr)}',
	'.lanspeed-connection-meta-fact{display:flex;flex-direction:column;justify-content:center;gap:.16em;min-width:0;padding:.58em .72em;border:1px solid var(--lanspeed-border);border-radius:var(--lanspeed-radius-control);background:var(--lanspeed-surface-muted)}',
	'.lanspeed-connection-meta-label{font-size:.69em;font-weight:600;letter-spacing:.03em;opacity:.55;white-space:nowrap}',
	'.lanspeed-connection-meta-value{min-width:0;font-size:.88em;font-weight:500;line-height:1.35;overflow-wrap:anywhere}',
	'.lanspeed-connection-meta-empty{display:block;padding:.8em 0;opacity:.65}',
	'.lanspeed-connection-hostname-modal-form{display:grid;gap:.7em;min-width:min(28em,80vw)}',
	'.lanspeed-connection-hostname-modal-label{font-weight:600}',
	'.lanspeed-connection-hostname-modal-input{width:100%;box-sizing:border-box}',
	'.lanspeed-connection-hostname-modal-hint,.lanspeed-connection-hostname-modal-status{margin:0;font-size:.86em;line-height:1.45;overflow-wrap:anywhere}',
	'.lanspeed-connection-hostname-modal-hint{opacity:.68}',
	'.lanspeed-connection-hostname-modal-status[hidden]{display:none!important}',
	'.lanspeed-connection-hostname-modal-status[data-state="error"]{color:var(--lanspeed-danger)}',
	'.lanspeed-connection-hostname-modal-actions{margin-top:1.1em}',
	'.lanspeed-connection-state{display:inline-flex;align-items:center;gap:.5em;padding:.32em .72em!important;border:1px solid var(--lanspeed-border-strong);border-radius:var(--lanspeed-radius-badge)!important;background:var(--lanspeed-surface-muted)!important;font-size:.82em;font-weight:600;line-height:1.4;white-space:nowrap}',
	'.lanspeed-connection-state::before{content:"";width:.55em;height:.55em;flex:0 0 .55em;border-radius:var(--lanspeed-radius-badge);background:currentColor}',
	'.lanspeed-connection-state[data-state="active"]{border-color:var(--lanspeed-normal-border);background:var(--lanspeed-normal-soft)!important;color:var(--lanspeed-normal)!important}',
	'.lanspeed-connection-state[data-state="unavailable"]{border-color:var(--lanspeed-danger-border);background:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-danger)!important}',
	'.lanspeed-connection-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));align-content:center;gap:.75em;min-width:0;padding-left:2em;border-left:1px solid var(--lanspeed-border)}',
	'.lanspeed-connection-summary-title{grid-column:1/-1;margin:0 0 .2em;font-size:.9em;font-weight:650;letter-spacing:.02em}',
	'.lanspeed-connection-summary-item{display:flex;flex-direction:column;justify-content:center;gap:.32em;min-width:0;min-height:5.4em;padding:.85em .95em;border:1px solid var(--lanspeed-border);border-radius:var(--lanspeed-radius-control);background:var(--lanspeed-surface-muted)}',
	'.lanspeed-connection-summary-label{font-size:.72em;font-weight:550;opacity:.58}',
	'.lanspeed-connection-summary-value{order:-1;font-size:1.38em;font-weight:650;line-height:1.15;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}',
	'.lanspeed-connection-toolbar{align-items:center}',
	'.lanspeed-connection-toolbar-left{grid-template-columns:auto minmax(12em,1fr)}',
	'.lanspeed-connection-protocols{display:inline-flex;align-items:center;gap:.35em;white-space:nowrap}',
	'.lanspeed-connection-protocol[aria-pressed="true"]{font-weight:600}',
	'.lanspeed-connection-protocol-label{font-size:.9em;margin-right:.1em}',
	'.lanspeed-connection-filter{min-width:0}',
	'.lanspeed-connection-filter-input{min-width:10em;max-width:24em;width:100%}',
	'.lanspeed-connections-card .lanspeed-body{min-width:0}',
	'.lanspeed-connection-table{table-layout:fixed}',
	'.lanspeed-connection-table th:nth-child(1){width:20%}',
	'.lanspeed-connection-table th:nth-child(2){width:13%}',
	'.lanspeed-connection-table th:nth-child(3){width:10%}',
	'.lanspeed-connection-table th:nth-child(4){width:8%}',
	'.lanspeed-connection-table th:nth-child(5){width:9%}',
	'.lanspeed-connection-table th:nth-child(6),.lanspeed-connection-table th:nth-child(7){width:15%}',
	'.lanspeed-connection-table th:nth-child(8){width:10%}',
	'.lanspeed-connection-endpoint{font-family:var(--font-monospace,ui-monospace,monospace);overflow-wrap:anywhere;word-break:break-word}',
	'.lanspeed-connection-location-cell{overflow-wrap:anywhere;word-break:break-word}',
	'.lanspeed-connection-rate-cell{font-size:.92em}',
	'.lanspeed-connection-group-row{cursor:default}',
	'.lanspeed-connection-expand{display:inline-flex;align-items:center;gap:.35em}',
	'.lanspeed-connection-detail-row>td{padding-top:0}',
	'.lanspeed-connection-detail-cell{min-width:0}',
	'.lanspeed-connection-detail-list{display:grid;gap:.35em;margin:0;padding:.25em 0 .5em}',
	'.lanspeed-connection-detail-item{display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:baseline;gap:.5em 1em;min-width:0}',
	'.lanspeed-connection-detail-meta{white-space:nowrap}',
	'.lanspeed-connection-detail-rates{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:.3em .8em;min-width:0;font-variant-numeric:tabular-nums}',
	'.lanspeed-connection-detail-rate{display:inline-flex;align-items:baseline;white-space:nowrap}',
	'.lanspeed-connection-empty{margin:.5em 0;padding:1.2em;text-align:center}',
	'.lanspeed-connection-pager{display:flex;align-items:center;justify-content:flex-end;gap:.55em;margin:.8em 0 0}',
	'.lanspeed-connection-pager[hidden]{display:none!important}',
	'.lanspeed-connection-page-button{display:inline-flex!important;align-items:center;justify-content:center;width:2.35em;height:2.35em;min-width:2.35em;padding:0!important;font-size:1.1em;line-height:1}',
	'.lanspeed-connection-page-status{min-width:4.5em;text-align:center;font-variant-numeric:tabular-nums;font-size:.88em;font-weight:600}',
	'.lanspeed-connection-footer{margin:.8em 0 0;font-size:.85em}'
].join('\n');

return baseclass.extend({
	CSS: CSS
});
