'use strict';
'require baseclass';

var CSS = [
	'.lanspeed-connection-detail{display:flex;flex-direction:column;gap:1em;margin:0}',
	'.lanspeed-connection-breadcrumb{display:flex;flex-wrap:wrap;align-items:center;gap:.65em}',
	'.lanspeed-connection-breadcrumb-current{font-size:.9em;opacity:.72}',
	'.lanspeed-connection-back{flex:0 0 auto}',
	'.lanspeed-connection-error{display:flex;align-items:baseline;gap:.5em;margin:0}',
	'.lanspeed-connection-error[hidden],.lanspeed-connection-empty[hidden]{display:none!important}',
	'.lanspeed-connection-identity{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(25em,1fr);gap:1.5em 2.25em;align-items:stretch}',
	'.lanspeed-connection-client{min-width:0}',
	'.lanspeed-connection-client-heading{display:flex;align-items:center;gap:1em;margin:0 0 1em;min-width:0}',
	'.lanspeed-connection-client-avatar{display:inline-flex;align-items:center;justify-content:center;width:3.4em;height:3.4em;flex:0 0 3.4em;border:1px solid color-mix(in srgb,currentColor 12%,transparent);border-radius:1em;background:color-mix(in srgb,currentColor 6%,transparent);color:var(--primary,currentColor)}',
	'.lanspeed-connection-client-device{position:relative;display:block;width:1.55em;height:1.05em;border:.14em solid currentColor;border-radius:.25em}',
	'.lanspeed-connection-client-device::before{content:"";position:absolute;left:50%;bottom:-.48em;width:.16em;height:.34em;border-radius:999px;background:currentColor;transform:translateX(-50%)}',
	'.lanspeed-connection-client-device::after{content:"";position:absolute;left:50%;bottom:-.58em;width:.85em;height:.14em;border-radius:999px;background:currentColor;transform:translateX(-50%)}',
	'.lanspeed-connection-client-title{display:flex;flex-direction:column;gap:.12em;min-width:0}',
	'.lanspeed-connection-client-kicker{font-size:.72em;font-weight:600;letter-spacing:.08em;opacity:.55}',
	'.lanspeed-connection-client-name{margin:0;font-size:1.28em;font-weight:650;line-height:1.25;overflow-wrap:anywhere}',
	'.lanspeed-connection-client-meta{display:grid;gap:.8em;margin:0;min-width:0}',
	'.lanspeed-connection-meta-group{display:grid;gap:.45em;min-width:0}',
	'.lanspeed-connection-meta-heading{display:flex;align-items:center;gap:.5em;min-width:0}',
	'.lanspeed-connection-meta-heading-label{font-size:.78em;font-weight:600;letter-spacing:.03em;opacity:.65}',
	'.lanspeed-connection-meta-count{display:inline-flex;align-items:center;justify-content:center;min-width:1.65em;height:1.65em;padding:0 .42em;border-radius:999px;background:color-mix(in srgb,currentColor 8%,transparent);font-size:.68em;font-weight:650;font-variant-numeric:tabular-nums;opacity:.72}',
	'.lanspeed-connection-meta-values{display:flex;flex-wrap:wrap;gap:.45em .55em;min-width:0}',
	'.lanspeed-connection-meta-ip{display:inline-flex;align-items:center;max-width:100%;padding:.4em .65em;border:1px solid color-mix(in srgb,currentColor 10%,transparent);border-radius:.65em;background:color-mix(in srgb,currentColor 4%,transparent);font-family:var(--font-monospace,ui-monospace,monospace);font-size:.86em;font-variant-numeric:tabular-nums;line-height:1.25;overflow-wrap:anywhere}',
	'.lanspeed-connection-meta-facts{display:grid;grid-template-columns:minmax(13em,1.5fr) minmax(7em,1fr);gap:.55em;min-width:0}',
	'.lanspeed-connection-meta-facts[data-count="1"]{grid-template-columns:minmax(0,1fr)}',
	'.lanspeed-connection-meta-fact{display:flex;flex-direction:column;justify-content:center;gap:.16em;min-width:0;padding:.58em .72em;border:1px solid color-mix(in srgb,currentColor 9%,transparent);border-radius:.65em;background:color-mix(in srgb,currentColor 3%,transparent)}',
	'.lanspeed-connection-meta-label{font-size:.69em;font-weight:600;letter-spacing:.03em;opacity:.55;white-space:nowrap}',
	'.lanspeed-connection-meta-value{min-width:0;font-size:.88em;font-weight:500;line-height:1.35;overflow-wrap:anywhere}',
	'.lanspeed-connection-meta-empty{display:block;padding:.8em 0;opacity:.65}',
	'.lanspeed-connection-state{display:inline-flex;align-items:center;gap:.5em;padding:.32em .72em!important;border:1px solid color-mix(in srgb,currentColor 14%,transparent);border-radius:999px!important;background:color-mix(in srgb,currentColor 5%,transparent)!important;font-size:.82em;font-weight:600;line-height:1.4;white-space:nowrap}',
	'.lanspeed-connection-state::before{content:"";width:.55em;height:.55em;flex:0 0 .55em;border-radius:50%;background:currentColor;box-shadow:0 0 0 .22em color-mix(in srgb,currentColor 12%,transparent)}',
	'.lanspeed-connection-state[data-state="active"]{color:var(--success-color,var(--primary,currentColor))}',
	'.lanspeed-connection-state[data-state="unavailable"]{color:var(--danger-color,var(--error-color,currentColor))}',
	'.lanspeed-connection-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));align-content:center;gap:.75em;min-width:0;padding-left:2em;border-left:1px solid var(--border,rgba(128,128,128,.18))}',
	'.lanspeed-connection-summary-title{grid-column:1/-1;margin:0 0 .2em;font-size:.9em;font-weight:650;letter-spacing:.02em}',
	'.lanspeed-connection-summary-item{display:flex;flex-direction:column;justify-content:center;gap:.32em;min-width:0;min-height:5.4em;padding:.85em .95em;border:1px solid color-mix(in srgb,currentColor 10%,transparent);border-radius:.8em;background:color-mix(in srgb,currentColor 4%,transparent)}',
	'.lanspeed-connection-summary-label{font-size:.72em;font-weight:550;opacity:.58}',
	'.lanspeed-connection-summary-value{order:-1;font-size:1.38em;font-weight:650;line-height:1.15;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}',
	'.lanspeed-connection-toolbar{align-items:center}',
	'.lanspeed-connection-toolbar-left{grid-template-columns:auto minmax(12em,1fr)}',
	'.lanspeed-connection-protocols{display:inline-flex;align-items:center;gap:.35em;white-space:nowrap}',
	'.lanspeed-connection-protocol[aria-pressed="true"]{font-weight:600;box-shadow:inset 0 0 0 2px currentColor}',
	'.lanspeed-connection-protocol-label{font-size:.9em;margin-right:.1em}',
	'.lanspeed-connection-filter{min-width:0}',
	'.lanspeed-connection-filter-input{min-width:10em;max-width:24em;width:100%}',
	'.lanspeed-connections-card .lanspeed-body{min-width:0}',
	'.lanspeed-connection-table{table-layout:fixed}',
	'.lanspeed-connection-table th:nth-child(1){width:20%}',
	'.lanspeed-connection-table th:nth-child(2){width:13%}',
	'.lanspeed-connection-table th:nth-child(3){width:10%}',
	'.lanspeed-connection-table th:nth-child(4){width:8%}',
	'.lanspeed-connection-table th:nth-child(5){width:9%}',
	'.lanspeed-connection-table th:nth-child(6),.lanspeed-connection-table th:nth-child(7){width:15%}',
	'.lanspeed-connection-table th:nth-child(8){width:10%}',
	'.lanspeed-connection-endpoint{font-family:var(--font-monospace,ui-monospace,monospace);overflow-wrap:anywhere;word-break:break-word}',
	'.lanspeed-connection-location-cell{overflow-wrap:anywhere;word-break:break-word}',
	'.lanspeed-connection-rate-cell{font-size:.92em}',
	'.lanspeed-connection-group-row{cursor:default}',
	'.lanspeed-connection-expand{display:inline-flex;align-items:center;gap:.35em}',
	'.lanspeed-connection-detail-row>td{padding-top:0}',
	'.lanspeed-connection-detail-cell{min-width:0}',
	'.lanspeed-connection-detail-list{display:grid;gap:.35em;margin:0;padding:.25em 0 .5em}',
	'.lanspeed-connection-detail-item{display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:baseline;gap:.5em 1em;min-width:0}',
	'.lanspeed-connection-detail-meta{white-space:nowrap}',
	'.lanspeed-connection-detail-rates{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:.3em .8em;min-width:0;font-variant-numeric:tabular-nums}',
	'.lanspeed-connection-detail-rate{display:inline-flex;align-items:baseline;white-space:nowrap}',
	'.lanspeed-connection-empty{padding:1.2em 0;text-align:center;opacity:.7}',
	'.lanspeed-connection-pager{display:flex;align-items:center;justify-content:flex-end;gap:.55em;margin:.8em 0 0}',
	'.lanspeed-connection-pager[hidden]{display:none!important}',
	'.lanspeed-connection-page-button{display:inline-flex!important;align-items:center;justify-content:center;width:2.35em;height:2.35em;min-width:2.35em;padding:0!important;font-size:1.1em;line-height:1}',
	'.lanspeed-connection-page-status{min-width:4.5em;text-align:center;font-variant-numeric:tabular-nums;font-size:.88em;font-weight:600}',
	'.lanspeed-connection-footer{margin:.8em 0 0;font-size:.85em;opacity:.72}'
].join('\n');

return baseclass.extend({
	CSS: CSS
});
