'use strict';
'require baseclass';

return baseclass.extend({
	LABELS: {
		nss_path_identity_pending: _('正在确认客户端流量的实际执行路径，尚未发布限速分类。'),
		nss_control_rollback_failed: _('NSS 控制应用失败且专用对象未能完整回滚。'),
		nss_control_command_timeout: _('NSS 控制命令执行超时，已停止应用。'),
		nss_ecm_dscp_unavailable: _('ECM QoS 分类器未启用，无法安全写入双向 NSS 标签。'),
		nss_qdisc_unavailable: _('NSS 固件队列模块不可用。'),
		nss_wan_topology_invalid: _('默认路由拓扑数据无效。'),
		nss_netifd_topology_unavailable: _('无法从 netifd 确认实际 WAN 出口。'),
		nss_fw4_topology_unavailable: _('无法从防火墙区域确认互联网出口。'),
		nss_wan_interface_unavailable: _('未找到可安装 NSS 队列的实际 WAN 出口。'),
		nss_download_edge_unavailable: _('尚未由 Access Edge 确认客户端真实下载出口。'),
		nss_download_edge_invalid: _('客户端下载出口与 WAN 冲突，已拒绝应用。'),
		nss_default_class_capacity_exceeded: _('目标接口链路容量超过 NSS 安全整形上限或无法确认。'),
		nss_qdisc_owned_by_external_service: _('目标接口的 NSS 队列正在由其它服务管理。'),
		nss_qdisc_apply_failed: _('NSS 固件队列创建失败，已回滚。'),
		nss_qdisc_inspection_failed: _('无法读取 NSS 固件队列状态。'),
		nss_qdisc_verification_failed: _('NSS 队列树校验失败，未发布分类映射。'),
		nss_control_firewall_owned_by_external_service: _('NSS 分类表正在由其它服务管理。'),
		nss_control_firewall_inspection_failed: _('无法检查 NSS 分类表所有权。'),
		nss_control_firewall_failed: _('NSS 双栈分类映射应用失败。'),
		cpu_path_block_interface_unavailable: _('尚未确认可在代理接管前后保留客户端身份的禁网接口。'),
		cpu_path_block_owned_by_external_service: _('CPU 路径禁网表正在由其它服务管理。'),
		cpu_path_block_inspection_failed: _('无法检查 CPU 路径禁网规则。'),
		cpu_path_block_apply_failed: _('CPU 路径双向禁网规则创建失败。'),
		cpu_path_block_missing: _('CPU 路径双向禁网规则不完整，正在重建。'),
		cpu_path_block_stale: _('发现过期的 CPU 路径禁网规则。'),
		cpu_path_block_cleanup_failed: _('CPU 路径禁网规则清理失败。'),
		cpu_path_probe_interface_unavailable: _('尚未确认可保留客户端身份的 CPU 路径接口。'),
		cpu_path_probe_owned_by_external_service: _('CPU 路径证明表正在由其它服务管理。'),
		cpu_path_probe_inspection_failed: _('无法读取 CPU 路径证明计数。'),
		cpu_path_probe_apply_failed: _('CPU 路径证明规则创建失败。'),
		cpu_path_probe_missing: _('CPU 路径证明规则不完整，正在重建。'),
		cpu_path_probe_stale: _('发现过期的 CPU 路径证明规则。'),
		cpu_path_probe_cleanup_failed: _('CPU 路径证明规则清理失败。'),
		cpu_path_classifier_owned_by_external_service: _('CPU 路径分类链与其它 TC 规则冲突。'),
		cpu_path_classifier_inspection_failed: _('无法读取 CPU 路径分类规则。'),
		cpu_path_classifier_verification_failed: _('CPU 路径分类发布后校验失败。'),
		cpu_path_classifier_missing: _('CPU 路径分类规则不完整，正在重建。'),
		cpu_path_classifier_stale: _('发现过期的 CPU 路径分类规则。'),
		cpu_path_qdisc_owned_by_external_service: _('NSS 专属 CPU 队列正在由其它服务管理。'),
		cpu_path_qdisc_verification_failed: _('NSS 专属 CPU 队列树校验失败。'),
		cpu_path_qdisc_inspection_failed: _('无法读取 NSS 专属 CPU 队列状态。'),
		cpu_path_class_inspection_failed: _('无法读取 NSS 专属 CPU class 状态。'),
		cpu_path_filter_owned_by_external_service: _('NSS 专属 IFB 分类链与其它规则冲突。'),
		cpu_path_filter_inspection_failed: _('无法读取 NSS 专属 IFB 分类规则。'),
		cpu_path_filter_verification_failed: _('NSS 专属 IFB 分类规则校验失败。')
	}
});
