'use strict';
'require baseclass';

/* Layout rules intentionally shared by Aurora and Argon. */
var SHARED_CSS = [
	'.lanspeed-theme-aurora,',
	'.lanspeed-theme-argon{display:flex;flex-direction:column;gap:1rem;margin:0}',
	'.lanspeed-theme-aurora>.cbi-section,',
	'.lanspeed-theme-argon>.cbi-section{margin:0;padding:0;overflow:hidden}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-body,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-body{overflow-x:auto}',
	'.lanspeed-theme-aurora .lanspeed-config-table th:nth-child(1),',
	'.lanspeed-theme-aurora .lanspeed-config-table td:nth-child(1),',
	'.lanspeed-theme-argon .lanspeed-config-table th:nth-child(1),',
	'.lanspeed-theme-argon .lanspeed-config-table td:nth-child(1){width:9rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table th:nth-child(2),',
	'.lanspeed-theme-aurora .lanspeed-config-table td:nth-child(2),',
	'.lanspeed-theme-argon .lanspeed-config-table th:nth-child(2),',
	'.lanspeed-theme-argon .lanspeed-config-table td:nth-child(2){width:18rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table .value,',
	'.lanspeed-theme-argon .lanspeed-config-table .value{width:auto}',
	'.lanspeed-theme-aurora .lanspeed-config-table .value input,',
	'.lanspeed-theme-argon .lanspeed-config-table .value input{max-width:16rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table .value.range input,',
	'.lanspeed-theme-argon .lanspeed-config-table .value.range input{max-width:none}',
	'.lanspeed-theme-aurora .lanspeed-range-stack,',
	'.lanspeed-theme-argon .lanspeed-range-stack{max-width:26rem}',
	'.lanspeed-theme-aurora .lanspeed-range-pill,',
	'.lanspeed-theme-argon .lanspeed-range-pill{display:grid;grid-template-columns:minmax(0,1fr) auto;',
	'  gap:.5rem;align-items:center}',
	'.lanspeed-theme-aurora .lanspeed-range-remove,',
	'.lanspeed-theme-argon .lanspeed-range-remove{width:2.25rem;min-width:2.25rem;',
	'  height:2.25rem;padding:0}',
	'.lanspeed-theme-aurora .lanspeed-range-add,',
	'.lanspeed-theme-argon .lanspeed-range-add{display:grid;grid-template-columns:minmax(0,1fr) auto;',
	'  gap:.5rem;align-items:center}',
	'.lanspeed-theme-aurora .lanspeed-range-add button,',
	'.lanspeed-theme-argon .lanspeed-range-add button{height:2.25rem}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table .action,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table .action{width:19rem}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-seg,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-seg{gap:.35rem;min-width:17rem}',
	'@media (min-width:801px){',
	'.lanspeed-theme-aurora .lanspeed-config-table,',
	'.lanspeed-theme-argon .lanspeed-config-table{display:block}',
	'.lanspeed-theme-aurora .lanspeed-config-table thead,',
	'.lanspeed-theme-argon .lanspeed-config-table thead{display:none}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody,',
	'.lanspeed-theme-argon .lanspeed-config-table tbody{display:block}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody tr,.lanspeed-theme-argon .lanspeed-config-table tbody tr{display:grid;',
	'  grid-template-columns:minmax(12rem,20rem) minmax(13rem,24rem);',
	'  grid-template-areas:"label control" "hint control";',
	'  column-gap:1.25rem;row-gap:.2rem;align-items:center;',
	'  padding:.68rem 0;border-bottom:1px solid var(--border,rgba(128,128,128,.18))}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody tr:last-child,',
	'.lanspeed-theme-argon .lanspeed-config-table tbody tr:last-child{border-bottom:0}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody td,',
	'.lanspeed-theme-argon .lanspeed-config-table tbody td{padding:0;border-bottom:0;text-align:left}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody td:nth-child(1),',
	'.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(1){grid-area:label;width:auto;align-self:end;font-weight:600}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody td:nth-child(2),',
	'.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(2){grid-area:control;width:auto;align-self:center;justify-self:stretch}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody td:nth-child(3),',
	'.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(3){grid-area:hint;width:auto;align-self:start}',
	'.lanspeed-theme-aurora .lanspeed-config-table .value input,',
	'.lanspeed-theme-argon .lanspeed-config-table .value input{max-width:22rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table .value select,',
	'.lanspeed-theme-argon .lanspeed-config-table .value select{max-width:100%}',
	'.lanspeed-theme-aurora .lanspeed-range-stack,',
	'.lanspeed-theme-argon .lanspeed-range-stack{max-width:23rem;gap:.45rem}',
	'.lanspeed-theme-aurora .lanspeed-range-list,',
	'.lanspeed-theme-argon .lanspeed-range-list{gap:.45rem}',
	'.lanspeed-theme-aurora .lanspeed-range-pill,',
	'.lanspeed-theme-argon .lanspeed-range-pill,',
	'.lanspeed-theme-aurora .lanspeed-range-add,',
	'.lanspeed-theme-argon .lanspeed-range-add{grid-template-columns:minmax(0,1fr) auto;gap:.45rem}',
	'.lanspeed-theme-aurora .lanspeed-range-add button,.lanspeed-theme-argon .lanspeed-range-add button{min-width:4rem;height:2.25rem}',
	'.lanspeed-theme-aurora .lanspeed-range-remove,',
	'.lanspeed-theme-argon .lanspeed-range-remove{width:2.25rem;min-width:2.25rem;height:2.25rem;padding:0}}',
].join('\n');

return baseclass.extend({
	CSS: SHARED_CSS
});
