'use strict';
'require baseclass';

/* Aurora uses generous spacing inside one section surface; setting rows are not nested cards. */
var AURORA_CSS = [
	'.lanspeed-config-root.lanspeed-theme-aurora .lanspeed-header{padding:1rem 1.25rem .85rem;gap:.45rem .75rem}',
	'.lanspeed-config-root.lanspeed-theme-aurora .lanspeed-header>h3{font-size:1.2rem;line-height:1.25}',
	'.lanspeed-config-root.lanspeed-theme-aurora .lanspeed-config-subheader{padding:1rem 1.25rem .85rem;background-color:var(--lanspeed-surface-raised)}',
	'.lanspeed-config-root.lanspeed-theme-aurora .lanspeed-config-subheader>h4{font-size:1.2rem;line-height:1.25}',
	'.lanspeed-config-root.lanspeed-theme-aurora :is(.lanspeed-config-body,.lanspeed-ifcfg-body){',
		'padding:1rem 1.25rem 1.15rem}',
	'.lanspeed-config-root.lanspeed-theme-aurora :is(.lanspeed-header,.lanspeed-config-subheader)>.sum{padding:.22rem .58rem;',
		'border:0;border-radius:var(--lanspeed-radius-badge);background:var(--lanspeed-surface-sunken)}',
	'.lanspeed-theme-aurora .lanspeed-range-stack,.lanspeed-theme-aurora .lanspeed-range-list{gap:.5rem;max-width:none}',
	'.lanspeed-theme-aurora :is(.lanspeed-range-pill,.lanspeed-range-add){display:grid;',
		'grid-template-columns:minmax(0,1fr) auto;gap:.5rem;align-items:center}',
	'.lanspeed-theme-aurora :is(.lanspeed-range-text,.lanspeed-range-value,.lanspeed-range-add>input,',
		'.lanspeed-range-remove,.lanspeed-range-add>button){height:2.35rem;min-height:2.35rem}',
	'.lanspeed-theme-aurora :is(.lanspeed-range-text,.lanspeed-range-value,.lanspeed-range-add>input){max-width:none}',
	'.lanspeed-theme-aurora :is(.lanspeed-range-text,.lanspeed-range-value){display:flex;align-items:center}',
	'.lanspeed-theme-aurora .lanspeed-range-remove{width:2.35rem;min-width:2.35rem;padding:0}',
	'.lanspeed-theme-aurora .lanspeed-range-add>button{min-width:4rem}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-seg{display:grid;',
		'grid-template-columns:repeat(3,minmax(0,1fr));width:100%;min-width:0;gap:.35rem;',
		'padding:.22rem;border-radius:var(--lanspeed-radius-input);background:var(--lanspeed-surface-sunken)}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-seg>button{padding:.5rem .55rem;border-color:transparent!important;',
		'background:transparent!important;box-shadow:none}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-seg>button.active{border-color:var(--lanspeed-border)!important;',
		'background:var(--lanspeed-surface)!important;box-shadow:var(--lanspeed-shadow-section)}',
	'@media (min-width:801px){',
	'.lanspeed-theme-aurora :is(.lanspeed-config-table,.lanspeed-ifcfg-table){display:block}',
	'.lanspeed-theme-aurora :is(.lanspeed-config-table,.lanspeed-ifcfg-table) thead{display:none}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody{display:grid;',
		'grid-template-columns:repeat(2,minmax(0,1fr));column-gap:2rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody tr{display:grid;',
		'grid-template-columns:minmax(10rem,1fr) minmax(12rem,18rem);',
		'grid-template-areas:"label control" "hint control";grid-template-rows:auto 1fr;',
		'column-gap:1.25rem;row-gap:.3rem;align-items:start;min-width:0;padding:1rem 0;',
		'border-bottom:1px solid var(--lanspeed-border);background:transparent}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody :is(th,td){width:auto;min-width:0;padding:0;border:0}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody :is(th,td):nth-child(1){grid-area:label;font-weight:600}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody :is(th,td):nth-child(2){grid-area:control;justify-self:stretch}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody :is(th,td):nth-child(3){grid-area:hint}',
	'.lanspeed-theme-aurora .lanspeed-config-table .value :is(input:not([type="checkbox"]),select){',
		'width:100%;max-width:none}',
	'.lanspeed-theme-aurora .lanspeed-rate-control{display:grid;grid-template-columns:minmax(0,1fr);gap:.4rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody tr.lanspeed-private-ipv6-row{',
		'grid-column:1/-1;grid-template-columns:minmax(14rem,1fr) minmax(12rem,18rem)}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody tr.lanspeed-range-row{grid-column:1/-1;',
		'grid-template-columns:minmax(14rem,1fr) minmax(18rem,27rem)}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody{display:grid;',
		'grid-template-columns:repeat(3,minmax(0,1fr));gap:0 1.25rem}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody tr{display:grid;',
		'grid-template-columns:minmax(0,1fr) auto;grid-template-areas:"iface badge" "action action";',
		'gap:.55rem .65rem;min-width:0;padding:.9rem 0;border-bottom:1px solid var(--lanspeed-border);',
		'background:transparent}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody td{width:auto;min-width:0;padding:0;border:0}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody td:nth-child(1){grid-area:iface;overflow-wrap:anywhere}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody td:nth-child(2){grid-area:badge;justify-self:end}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody td.action{grid-area:action;width:auto}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table .devtags{justify-content:flex-end}',
	'.lanspeed-theme-aurora :is(.lanspeed-config-actions,.lanspeed-ifcfg-actions){padding-top:1rem}',
	'}',
	'@media (min-width:801px) and (max-width:1120px){',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody{grid-template-columns:minmax(0,1fr)}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody{grid-template-columns:repeat(2,minmax(0,1fr))}}',
	'@media (max-width:800px){',
	'.lanspeed-theme-aurora{--lanspeed-mobile-config-row-padding:.9rem 0;',
		'--lanspeed-mobile-ifcfg-row-padding:.85rem 0;--lanspeed-mobile-seg-padding:.5rem .3rem}',
	'.lanspeed-config-root.lanspeed-theme-aurora .lanspeed-header{padding:.85rem 1rem .7rem}',
	'.lanspeed-config-root.lanspeed-theme-aurora .lanspeed-config-subheader{padding:.85rem 1rem .7rem}',
	'.lanspeed-config-root.lanspeed-theme-aurora :is(.lanspeed-config-body,.lanspeed-ifcfg-body){',
		'padding:.85rem 1rem 1rem}',
	'.lanspeed-theme-aurora :is(.lanspeed-config-table,.lanspeed-ifcfg-table) tbody tr{',
		'border-bottom:1px solid var(--lanspeed-border);background:transparent}',
	'.lanspeed-theme-aurora :is(.lanspeed-header,.lanspeed-config-subheader)>.sum{font-size:.76em}}'
].join('\n');

return baseclass.extend({
	CSS: AURORA_CSS
});
