'use strict';
'require baseclass';

/* shadcn renders settings and interfaces as bordered rows on one card surface. */
var SHADCN_CSS = [
	'.lanspeed-config-root.lanspeed-theme-shadcn{gap:var(--lanspeed-page-gap);font-size:.94rem}',
	'.lanspeed-config-root.lanspeed-theme-shadcn .lanspeed-header{padding:.85rem 1.15rem .72rem;',
		'border-bottom-color:var(--lanspeed-border)}',
	'.lanspeed-config-root.lanspeed-theme-shadcn .lanspeed-header>h3{font-size:1.05rem;line-height:1.3}',
	'.lanspeed-config-root.lanspeed-theme-shadcn .lanspeed-config-subheader{padding:.8rem 1.15rem .68rem;',
		'border-bottom-color:var(--lanspeed-border);background-color:var(--lanspeed-surface-muted)}',
	'.lanspeed-config-root.lanspeed-theme-shadcn .lanspeed-config-subheader>h4{font-size:1rem;line-height:1.3}',
	'.lanspeed-config-root.lanspeed-theme-shadcn :is(.lanspeed-config-body,.lanspeed-ifcfg-body){',
		'padding:.85rem 1.15rem 1rem}',
	'.lanspeed-config-root.lanspeed-theme-shadcn.lanspeed-config-x86 .lanspeed-config-runtime-section + .lanspeed-ifcfg{',
		'margin-top:1.1rem}',
	'.lanspeed-config-root.lanspeed-theme-shadcn.lanspeed-config-x86 .lanspeed-ifcfg-table{',
		'width:100%;max-width:none}',
	'.lanspeed-config-root.lanspeed-theme-shadcn .lanspeed-config-group{border:0;',
		'background:transparent;border-radius:0}',
	'.lanspeed-config-root.lanspeed-theme-shadcn .lanspeed-config-group-heading{padding:.5rem .68rem;',
		'border:1px solid var(--lanspeed-border);border-radius:var(--lanspeed-radius-control);',
		'background:var(--lanspeed-surface-muted);color:var(--lanspeed-text);font-size:.92rem;font-weight:600}',
	'.lanspeed-config-root.lanspeed-theme-shadcn .lanspeed-config-group-subtitle{',
		'color:var(--lanspeed-text-muted);font-size:.78rem;font-weight:400}',
	'.lanspeed-config-root.lanspeed-theme-shadcn .lanspeed-config-group-body{padding:.05rem 0 0}',
	'.lanspeed-theme-shadcn :is(.lanspeed-config-table,.lanspeed-ifcfg-table){border-collapse:collapse}',
	'.lanspeed-theme-shadcn :is(.lanspeed-config-table,.lanspeed-ifcfg-table) thead th{',
		'padding:.5rem .65rem;border-bottom:1px solid var(--lanspeed-border);',
		'background:var(--lanspeed-surface-muted)}',
	'.lanspeed-theme-shadcn :is(.lanspeed-config-table,.lanspeed-ifcfg-table) tbody td{padding:.55rem .65rem}',
	'.lanspeed-config-root.lanspeed-theme-shadcn :is(.lanspeed-config-table,.lanspeed-ifcfg-table) ',
		'tbody tr:hover{background:transparent!important;background-image:none!important}',
	'.lanspeed-theme-shadcn .lanspeed-config-table :is(th,td):nth-child(1){width:20%}',
	'.lanspeed-theme-shadcn .lanspeed-config-table :is(th,td):nth-child(2){width:22%}',
	'.lanspeed-theme-shadcn .lanspeed-config-table .value{width:auto}',
	'.lanspeed-theme-shadcn .lanspeed-config-table .value :is(input:not([type="checkbox"]),select){',
		'width:100%;max-width:16rem}',
	'.lanspeed-theme-shadcn .lanspeed-range-stack{max-width:18rem;gap:.4rem}',
	'.lanspeed-theme-shadcn .lanspeed-range-list{gap:.4rem}',
	'.lanspeed-theme-shadcn :is(.lanspeed-range-pill,.lanspeed-range-add){display:grid;',
		'grid-template-columns:minmax(0,1fr) auto;gap:.35rem;align-items:center}',
	'.lanspeed-theme-shadcn :is(.lanspeed-range-text,.lanspeed-range-value,.lanspeed-range-add input){max-width:none!important}',
	'.lanspeed-theme-shadcn :is(.lanspeed-range-text,.lanspeed-range-value){display:flex;align-items:center}',
	'.lanspeed-theme-shadcn .lanspeed-range-remove{width:2.25rem;min-width:2.25rem;height:2.25rem;padding:0}',
	'.lanspeed-theme-shadcn .lanspeed-range-add button{height:2.25rem}',
	'.lanspeed-theme-shadcn .lanspeed-ifcfg-table .action{width:18rem}',
	'.lanspeed-theme-shadcn .lanspeed-ifcfg-seg{display:grid;',
		'grid-template-columns:repeat(3,minmax(0,1fr));gap:0;min-width:17rem}',
	'.lanspeed-theme-shadcn .lanspeed-ifcfg-seg>button{min-height:2.25rem;padding:.42rem .5rem;border-radius:0}',
	'.lanspeed-theme-shadcn .lanspeed-ifcfg-seg>button+button{margin-left:-1px}',
	'.lanspeed-theme-shadcn .lanspeed-ifcfg-seg>button:first-child{border-radius:var(--lanspeed-radius-control) 0 0 var(--lanspeed-radius-control)}',
	'.lanspeed-theme-shadcn .lanspeed-ifcfg-seg>button:last-child{border-radius:0 var(--lanspeed-radius-control) var(--lanspeed-radius-control) 0}',
	'.lanspeed-config-root.lanspeed-theme-shadcn .lanspeed-ifcfg-seg>button.active:hover:not(:disabled){',
		'background-color:var(--lanspeed-accent-soft)!important;',
		'box-shadow:inset 0 0 0 1px var(--lanspeed-accent-safe)!important}',
	'@media (min-width:801px){',
	'.lanspeed-config-root.lanspeed-theme-shadcn.lanspeed-config-x86 .lanspeed-ifcfg-table{display:block}',
	'.lanspeed-config-root.lanspeed-theme-shadcn.lanspeed-config-x86 .lanspeed-ifcfg-table thead{display:none}',
	'.lanspeed-config-root.lanspeed-theme-shadcn.lanspeed-config-x86 .lanspeed-ifcfg-table tbody{',
		'display:grid;grid-template-columns:repeat(3,minmax(0,1fr));column-gap:1rem}',
	'.lanspeed-config-root.lanspeed-theme-shadcn.lanspeed-config-x86 .lanspeed-ifcfg-table tbody tr{',
		'display:grid;grid-template-columns:minmax(10rem,18rem) auto;justify-content:start;',
		'grid-template-areas:"iface badge" "action action";column-gap:1rem;row-gap:.45rem;align-items:center;',
		'padding:.72rem 0;border-bottom:1px solid var(--lanspeed-border);background:transparent}',
	'.lanspeed-config-root.lanspeed-theme-shadcn.lanspeed-config-x86 .lanspeed-ifcfg-table tbody td{',
		'width:auto;min-width:0;padding:0;border:0}',
	'.lanspeed-config-root.lanspeed-theme-shadcn.lanspeed-config-x86 .lanspeed-ifcfg-table tbody td:nth-child(1){',
		'grid-area:iface;overflow-wrap:anywhere}',
	'.lanspeed-config-root.lanspeed-theme-shadcn.lanspeed-config-x86 .lanspeed-ifcfg-table tbody td:nth-child(2){',
		'grid-area:badge;justify-self:start;max-width:18rem}',
	'.lanspeed-config-root.lanspeed-theme-shadcn.lanspeed-config-x86 .lanspeed-ifcfg-table tbody td.action{',
		'grid-area:action;width:18rem;justify-self:start}',
	'.lanspeed-config-root.lanspeed-theme-shadcn.lanspeed-config-x86 .lanspeed-ifcfg-seg{',
		'width:18rem;min-width:16rem;max-width:20rem}',
	'}',
	'@media (min-width:801px) and (max-width:1120px){',
	'.lanspeed-config-root.lanspeed-theme-shadcn.lanspeed-config-x86 .lanspeed-ifcfg-table tbody{',
		'grid-template-columns:repeat(2,minmax(0,1fr))}}',
	'@media (max-width:800px){',
	'.lanspeed-theme-shadcn{--lanspeed-mobile-config-row-padding:.68rem 0;',
		'--lanspeed-mobile-ifcfg-row-padding:.68rem 0;--lanspeed-mobile-seg-padding:.5rem .25rem}',
	'.lanspeed-config-root.lanspeed-theme-shadcn .lanspeed-header{padding:.7rem .85rem .6rem}',
	'.lanspeed-config-root.lanspeed-theme-shadcn .lanspeed-config-subheader{padding:.68rem .85rem .58rem}',
	'.lanspeed-config-root.lanspeed-theme-shadcn :is(.lanspeed-config-body,.lanspeed-ifcfg-body){',
		'padding:.7rem .85rem .85rem}',
	'.lanspeed-theme-shadcn :is(.lanspeed-config-table,.lanspeed-ifcfg-table) tbody{gap:0}',
	'.lanspeed-theme-shadcn :is(.lanspeed-config-table,.lanspeed-ifcfg-table) tbody tr{',
		'border-bottom:1px solid var(--lanspeed-border);background:transparent}',
	'.lanspeed-theme-shadcn :is(.lanspeed-config-table,.lanspeed-ifcfg-table) tbody tr>td{background:transparent!important}',
	'.lanspeed-theme-shadcn .lanspeed-config-table .value :is(input:not([type="checkbox"]),select){max-width:none}',
	'.lanspeed-theme-shadcn .lanspeed-ifcfg-seg{width:100%;min-width:0}}'
].join('\n');

return baseclass.extend({
	CSS: SHADCN_CSS
});
