'use strict';
'require baseclass';

/* Aurora uses spacious rounded tiles and pill-shaped controls. */
var AURORA_CSS = [
	'.lanspeed-theme-aurora .lanspeed-header{padding:1rem 1.25rem .85rem;align-items:center}',
	'.lanspeed-theme-aurora .lanspeed-config-body,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-body{padding:1rem 1.25rem 1.15rem}',
	'.lanspeed-theme-aurora .lanspeed-header>.sum{padding:.25rem .65rem;border-radius:999px;',
	'  background:rgba(127,127,127,.07);background:color-mix(in srgb,currentColor 7%,transparent)}',
	'.lanspeed-theme-aurora .lanspeed-config-table .hint,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table .muted{line-height:1.45}',
	'.lanspeed-theme-aurora .lanspeed-range-stack,',
	'.lanspeed-theme-aurora .lanspeed-range-list{gap:.5rem;max-width:none}',
	'.lanspeed-theme-aurora .lanspeed-range-pill,',
	'.lanspeed-theme-aurora .lanspeed-range-add{display:grid;grid-template-columns:minmax(0,1fr) auto;',
	'  gap:.5rem;align-items:center}',
	'.lanspeed-theme-aurora .lanspeed-range-text,',
	'.lanspeed-theme-aurora .lanspeed-range-add>input,',
	'.lanspeed-theme-aurora .lanspeed-range-remove,',
	'.lanspeed-theme-aurora .lanspeed-range-add>button{height:2.35rem;min-height:2.35rem;box-sizing:border-box}',
	'.lanspeed-theme-aurora .lanspeed-range-text,',
	'.lanspeed-theme-aurora .lanspeed-range-add>input{max-width:none}',
	'.lanspeed-theme-aurora .lanspeed-range-remove{width:2.35rem;min-width:2.35rem;',
	'  padding:0}',
	'.lanspeed-theme-aurora .lanspeed-range-add>button{min-width:4rem;',
	'  border-radius:calc(var(--radius-base,.5rem)*1.5)}',
	'.lanspeed-theme-aurora .lanspeed-config-actions,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-actions{margin:.85rem 0 0}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-seg{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));',
	'  width:100%;min-width:0;gap:.4rem}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-seg>button{min-height:2.35rem;padding:.5rem .55rem;',
	'  border-radius:calc(var(--radius-base,.5rem)*1.5)}',
	'@media (min-width:801px){',
	'.lanspeed-theme-aurora .lanspeed-config-table,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table{display:block}',
	'.lanspeed-theme-aurora .lanspeed-config-table thead,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table thead{display:none}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody{display:grid;',
	'  grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody tr{display:grid;',
	'  grid-template-columns:minmax(10rem,1fr) minmax(12rem,18rem);',
	'  grid-template-areas:"label control" "hint control";grid-template-rows:auto 1fr;',
	'  column-gap:1.1rem;row-gap:.25rem;',
	'  align-items:start;min-width:0;padding:.9rem 1rem;border:0;',
	'  border-radius:calc(var(--radius-base,.5rem)*1.5);',
	'  background:rgba(127,127,127,.055);background:color-mix(in srgb,currentColor 5%,transparent);',
	'  box-shadow:0 1px 2px rgba(15,23,42,.04)}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody td{width:auto;min-width:0;',
	'  padding:0;border:0;text-align:left}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody td:nth-child(1){',
	'  grid-area:label;align-self:start;font-weight:600}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody td:nth-child(2){',
	'  grid-area:control;align-self:start;justify-self:stretch;width:auto}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody td:nth-child(3){',
	'  grid-area:hint;align-self:start}',
	'.lanspeed-theme-aurora .lanspeed-config-table .value input:not([type="checkbox"]),',
	'.lanspeed-theme-aurora .lanspeed-config-table .value select{width:100%;max-width:none;box-sizing:border-box}',
	'.lanspeed-theme-aurora .lanspeed-rate-control{display:grid;grid-template-columns:minmax(0,1fr);',
	'  align-items:start;gap:.4rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody tr.lanspeed-private-ipv6-row{grid-column:1/-1;',
	'  grid-template-columns:minmax(14rem,1fr) minmax(12rem,18rem)}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody tr.lanspeed-range-row{',
	'  grid-column:1/-1;grid-template-columns:minmax(14rem,1fr) minmax(18rem,27rem);',
	'  grid-template-areas:"label control" "hint control";grid-template-rows:auto 1fr}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody{display:grid;',
	'  grid-template-columns:repeat(3,minmax(0,1fr));gap:.65rem}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody tr{display:grid;',
	'  grid-template-columns:minmax(0,1fr) auto;grid-template-areas:"iface badge" "action action";',
	'  gap:.5rem .65rem;min-width:0;padding:.8rem .85rem;border:0;',
	'  border-radius:calc(var(--radius-base,.5rem)*1.5);',
	'  background:rgba(127,127,127,.055);background:color-mix(in srgb,currentColor 5%,transparent);',
	'  box-shadow:0 1px 2px rgba(15,23,42,.04)}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody td{width:auto;min-width:0;',
	'  padding:0;border:0}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody td:nth-child(1){grid-area:iface;align-self:center}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody td:nth-child(1){white-space:normal;overflow-wrap:anywhere}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody td:nth-child(2){grid-area:badge;',
	'  align-self:center;justify-self:end;text-align:right}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody td.action{grid-area:action;width:auto}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table .devtags{justify-content:flex-end}',
	'}',
	'@media (min-width:801px) and (max-width:1120px){',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody{grid-template-columns:minmax(0,1fr)}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody{grid-template-columns:repeat(2,minmax(0,1fr))}',
	'}',
	'@media (max-width:800px){',
	'.lanspeed-theme-aurora{--lanspeed-mobile-config-row-padding:.85rem .85rem;',
	'  --lanspeed-mobile-ifcfg-row-padding:.8rem .85rem;--lanspeed-mobile-seg-padding:.5rem .3rem}',
	'.lanspeed-theme-aurora .lanspeed-header{padding:.9rem 1rem .75rem}',
	'.lanspeed-theme-aurora .lanspeed-config-body,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-body{padding:.85rem .8rem 1rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody{gap:.65rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody tr,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table tbody tr{border:0;',
	'  border-radius:calc(var(--radius-base,.5rem)*1.5);',
	'  background:rgba(127,127,127,.055);background:color-mix(in srgb,currentColor 5%,transparent);',
	'  box-shadow:0 1px 2px rgba(15,23,42,.04)}',
	'.lanspeed-theme-aurora .lanspeed-header>.sum{font-size:.78em;padding:.2rem .5rem}',
	'}'
].join('\n');

return baseclass.extend({
	CSS: AURORA_CSS
});
