'use strict';
'require baseclass';

/* Theme-neutral configuration information architecture. */
var BASE_CSS = [
	'.lanspeed-config-root{display:flex;flex-direction:column;gap:var(--lanspeed-page-gap);margin:0;min-width:0;font-weight:400}',
	'.lanspeed-config-root>:is(.cbi-section,.lanspeed-config-subsection,.lanspeed-ifcfg){padding:0;font-weight:400}',
	'.lanspeed-config-root .lanspeed-header{display:flex;flex-wrap:wrap;gap:.4em 1em;align-items:center;',
		'margin:0;padding:var(--lanspeed-section-y) var(--lanspeed-section-x) .78em;border-bottom:1px solid var(--lanspeed-border)}',
	'.lanspeed-config-root .lanspeed-header>h3{display:inline;flex:0 0 auto;width:auto;margin:0;padding:0;',
		'border:0;background:transparent;box-shadow:none;color:var(--lanspeed-text);font-weight:600;',
		'letter-spacing:0;line-height:1.25}',
	'.lanspeed-config-root .lanspeed-header>.spacer{flex:1 1 auto}',
	'.lanspeed-config-root .lanspeed-header>.sum{min-width:0;color:var(--lanspeed-text-muted);',
		'font-family:var(--font-mono,var(--font-monospace,ui-monospace,monospace));font-size:.8em;',
		'text-align:right;white-space:normal;overflow-wrap:anywhere}',
	'.lanspeed-config-page-body{display:grid;grid-template-columns:minmax(0,1fr);min-width:0}',
	'.lanspeed-config-subsection{min-width:0;margin:0;padding:0;border:0;background:transparent;box-shadow:none}',
	'.lanspeed-config-subsection+.lanspeed-config-subsection{border-top:0}',
	'.lanspeed-config-subheader{display:flex;flex-wrap:wrap;align-items:center;gap:.4em 1em;',
		'margin:0;padding:var(--lanspeed-section-y) var(--lanspeed-section-x) .68em;border-bottom:1px solid var(--lanspeed-border)}',
	'.lanspeed-config-subheader>h4{display:inline;flex:0 0 auto;width:auto;margin:0;padding:0;border:0;',
		'background:transparent;box-shadow:none;color:var(--lanspeed-text);font-size:1em;font-weight:650;line-height:1.25}',
	'.lanspeed-config-subheader>.spacer{flex:1 1 auto}',
	'.lanspeed-config-subheader>:is(.sum,.lanspeed-config-runtime){min-width:0;color:var(--lanspeed-text-muted);',
		'font-size:.78em;line-height:1.35;text-align:right;overflow-wrap:anywhere}',
	'.lanspeed-config-body,.lanspeed-ifcfg-body{min-width:0;padding:var(--lanspeed-section-y) var(--lanspeed-section-x)}',

	'.lanspeed-config-table,.lanspeed-ifcfg-table{width:100%;margin:0;border-collapse:collapse;color:var(--lanspeed-text)}',
	'.lanspeed-config-table :is(th,td),.lanspeed-ifcfg-table :is(th,td){padding:.62em .6em;',
		'border-bottom:1px solid var(--lanspeed-border);background:transparent;text-align:left;vertical-align:middle}',
	'.lanspeed-config-table tbody tr:last-child :is(th,td),.lanspeed-ifcfg-table tbody tr:last-child td{border-bottom:0}',
	'.lanspeed-config-table :is(th,td):first-child,.lanspeed-ifcfg-table :is(th,td):first-child{padding-left:0}',
	'.lanspeed-config-table :is(th,td):last-child,.lanspeed-ifcfg-table :is(th,td):last-child{padding-right:0}',
	'.lanspeed-config-table thead th,.lanspeed-ifcfg-table thead th{color:var(--lanspeed-text-muted);font-weight:600}',
	'.lanspeed-config-table tbody th{color:var(--lanspeed-text);font-weight:600}',
	'.lanspeed-config-table .key,.lanspeed-ifcfg-table .mono{font-family:var(--font-mono,var(--font-monospace,ui-monospace,monospace));font-size:.9em;white-space:nowrap}',
	'.lanspeed-config-table .value{width:12em}',
	'.lanspeed-config-table .value.rate{width:16em}',
	'.lanspeed-config-table .value input:not([type="checkbox"]):not([type="radio"]){width:100%;max-width:12em}',
	'.lanspeed-config-table .value.range{width:18em}',
	'.lanspeed-config-table .value.range input{max-width:none}',
	'.lanspeed-config-table .hint,.lanspeed-ifcfg-table .muted{color:var(--lanspeed-text-muted);font-size:.84em;line-height:1.45}',
	'.lanspeed-config-field[data-state="invalid"]{background-color:var(--lanspeed-danger-soft)}',
	'.lanspeed-config-field[data-disabled="true"]{color:var(--lanspeed-text-muted);opacity:1}',
	'.lanspeed-config-field[data-disabled="true"] :is(th,label,.lanspeed-toggle-label,.hint,',
		'.lanspeed-range-value,.lanspeed-range-text){color:var(--lanspeed-text-muted)!important}',
	'.lanspeed-config-field[data-disabled="true"] :is(input,select,button):disabled{',
		'border-color:var(--lanspeed-border)!important;background-color:var(--lanspeed-surface-muted)!important;',
		'box-shadow:none!important;color:var(--lanspeed-text-muted)!important;opacity:1!important}',
	'.lanspeed-config-field-error{margin:.28em 0 0;color:var(--lanspeed-danger);font-size:.82em;font-weight:600;line-height:1.4}',
	'.lanspeed-toggle{display:inline-flex;align-items:center;gap:.5em;min-height:var(--lanspeed-control-height);',
		'margin:0;padding:.25em 0;color:var(--lanspeed-text);cursor:pointer}',
	'.lanspeed-toggle>input{flex:0 0 auto;min-width:0;max-width:none;margin:0}',
	'.lanspeed-toggle-label{min-width:3.2em;font-size:.86em}',

	'.lanspeed-rate-control{display:flex;flex-wrap:wrap;align-items:center;gap:.45em}',
	'.lanspeed-current-rate-source{display:inline-flex;align-items:baseline;gap:.25em;color:var(--lanspeed-text-muted);font-size:.84em;white-space:nowrap}',
	'.lanspeed-current-rate-source>.label{opacity:1}',
	'.lanspeed-range-stack{display:flex;flex-direction:column;gap:.6em;align-items:stretch;max-width:22em}',
	'.lanspeed-range-list{display:flex;flex-direction:column;gap:.5em}',
	'.lanspeed-range-pill{display:flex;align-items:center;justify-content:space-between;gap:.5em;padding:.25em 0;border-bottom:1px solid var(--lanspeed-border)}',
	'.lanspeed-range-pill:last-child{border-bottom:0}',
	'.lanspeed-range-value,.lanspeed-range-text{flex:1 1 auto;min-width:0;color:var(--lanspeed-text);',
		'background-color:transparent!important;font-family:var(--font-mono,var(--font-monospace,ui-monospace,monospace));overflow-wrap:anywhere}',
	'.lanspeed-range-remove{flex:0 0 auto}',
	'.lanspeed-range-add{display:flex;gap:.5em;align-items:center}',
	'.lanspeed-range-add input{flex:1 1 auto;min-width:0}',
	'.lanspeed-range-add button{flex:0 0 auto}',

	'.lanspeed-ifcfg-table .action{width:17em;text-align:right}',
	'.lanspeed-ifcfg-table .devtags{display:inline-flex;gap:.35em;flex-wrap:wrap;color:var(--lanspeed-text-muted);font-size:.78em}',
	'.lanspeed-ifcfg-table .devtag{padding:.08em .42em;border:1px solid var(--lanspeed-border);',
		'border-radius:var(--lanspeed-radius-badge);background-color:var(--lanspeed-surface-muted)}',
	'.lanspeed-interface-limit{color:var(--lanspeed-text-muted);font-size:.8em}',
	'.lanspeed-interface-limit[data-state="limit"]{color:var(--lanspeed-warning);font-weight:650}',
	'.lanspeed-interface-orphans{display:grid;gap:.42em;margin:.85em 0 0;padding-top:.75em;border-top:1px solid var(--lanspeed-border)}',
	'.lanspeed-interface-orphan{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:.55em;align-items:center;min-width:0}',
	'.lanspeed-interface-orphan code{min-width:0;overflow-wrap:anywhere}',
	'.lanspeed-interface-orphan-kind{color:var(--lanspeed-text-muted);font-size:.76em}',

	'.lanspeed-config-actions,.lanspeed-ifcfg-actions{display:flex;flex-wrap:wrap;gap:.5em;align-items:center;',
		'margin:.85em 0 0;padding-top:.8em;border-top:1px solid var(--lanspeed-border)}',
	'.lanspeed-config-actions>.spacer,.lanspeed-ifcfg-actions>.spacer{flex:1 1 auto}',
	'.lanspeed-config-save-state,.lanspeed-ifcfg-actions .status{min-width:0;color:var(--lanspeed-text-muted);',
		'font-family:var(--font-mono,var(--font-monospace,ui-monospace,monospace));font-size:.82em;overflow-wrap:anywhere}',
	'.lanspeed-config-save-state[data-state="success"],.lanspeed-config-save-state[data-state="staged"]{color:var(--lanspeed-normal-text)}',
	'.lanspeed-config-save-state[data-state="dirty"],.lanspeed-config-save-state[data-state="invalid"],',
	'.lanspeed-config-save-state[data-state="degraded"]{color:var(--lanspeed-warning)}',
	'.lanspeed-config-save-state[data-state="error"]{color:var(--lanspeed-danger)}',

	'.lanspeed-ifcfg{display:flex;flex-direction:column;margin:0}',
	'.lanspeed-ifcfg-seg{display:inline-flex;gap:.35em;align-items:stretch;min-width:16em}',
	'.lanspeed-ifcfg-seg>button{flex:1 1 0;min-width:0;min-height:var(--lanspeed-control-height);padding:.48em .65em;',
		'border:1px solid var(--lanspeed-control-border);background-color:var(--lanspeed-control-bg);color:var(--lanspeed-text);',
		'cursor:pointer;font-size:.88em;line-height:1.25}',
	'.lanspeed-ifcfg-seg>button:hover:not(:disabled){background-color:var(--lanspeed-hover)}',
	'.lanspeed-ifcfg-seg>button.active{font-weight:600}',
	'.lanspeed-hint{margin:.8em 0 0;color:var(--lanspeed-text-muted);font-size:.84em;line-height:1.45}',
	'.lanspeed-state-message[data-state="empty"]{color:var(--lanspeed-text-muted)}',
	'.lanspeed-state-message[data-state="degraded"]{color:var(--lanspeed-warning)}',
	'.lanspeed-page-failure .lanspeed-state-message{margin:0 0 .75em}'
].join('\n');

return baseclass.extend({ CSS: BASE_CSS });
