'use strict';
'require baseclass';

var CONFIG_CSS = [
	'.lanspeed-config-root{font-weight:400}',
	'.lanspeed-config-root .cbi-section{font-weight:400}',
	'.lanspeed-header{display:flex;flex-wrap:wrap;gap:.4em 1em;align-items:baseline;',
	'  padding:1em 1.25em .75em 1.25em;margin:0;',
	'  border-bottom:1px solid var(--border,rgba(128,128,128,.25))}',
	'.lanspeed-header>h3{margin:0;padding:0;border:0;width:auto;display:inline;',
	'  flex:0 0 auto;background:transparent;box-shadow:none;line-height:1.25;font-weight:600}',
	'.lanspeed-header>.spacer{flex:1 1 auto}',
	'.lanspeed-header>.sum{font-size:.85em;opacity:.75;',
	'  font-family:var(--font-monospace,ui-monospace,monospace)}',
	'.lanspeed-config-body,.lanspeed-ifcfg-body{padding:1em 1.25em}',
	'.lanspeed-config-table,.lanspeed-ifcfg-table{width:100%;border-collapse:collapse;margin:0}',
	'.lanspeed-config-table th,.lanspeed-config-table td,',
	'.lanspeed-ifcfg-table th,.lanspeed-ifcfg-table td{padding:.6em .6em;text-align:left;',
	'  border-bottom:1px solid var(--border,rgba(128,128,128,.18));vertical-align:middle}',
	'.lanspeed-config-table tbody tr:last-child td,',
	'.lanspeed-ifcfg-table tbody tr:last-child td{border-bottom:0}',
	'.lanspeed-config-table th:first-child,.lanspeed-config-table td:first-child,',
	'.lanspeed-ifcfg-table th:first-child,.lanspeed-ifcfg-table td:first-child{padding-left:0}',
	'.lanspeed-config-table th:last-child,.lanspeed-config-table td:last-child,',
	'.lanspeed-ifcfg-table th:last-child,.lanspeed-ifcfg-table td:last-child{padding-right:0}',
	'.lanspeed-config-table thead th,.lanspeed-ifcfg-table thead th{font-weight:600;opacity:.85}',
	'.lanspeed-config-table .key,.lanspeed-ifcfg-table .mono{font-family:var(--font-monospace,ui-monospace,monospace);',
	'  font-size:.9em;white-space:nowrap}',
	'.lanspeed-config-table .value{width:12em}',
	'.lanspeed-config-table .value.rate{width:16em}',
	'.lanspeed-config-table .value input{width:100%;max-width:12em}',
	'.lanspeed-config-table .value.range{width:18em}',
	'.lanspeed-config-table .value.range input{max-width:none}',
	'.lanspeed-config-table .hint,.lanspeed-ifcfg-table .muted{font-size:.85em;opacity:.72}',
	'.lanspeed-config-table tr.lanspeed-nss-config-only{display:table-row}',
	'.lanspeed-rate-control{display:flex;flex-wrap:wrap;align-items:center;gap:.45em}',
	'.lanspeed-rate-badge{display:none;padding:.08em .45em;border-radius:.35em;',
	'  border:1px solid var(--border,rgba(128,128,128,.22));',
	'  background:var(--label-surface,rgba(128,128,128,.12));',
	'  font-size:.8em;line-height:1.55;white-space:nowrap}',
	'.lanspeed-range-stack{display:flex;flex-direction:column;gap:.6em;align-items:stretch;max-width:22em}',
	'.lanspeed-range-list{display:flex;flex-direction:column;gap:.6em}',
	'.lanspeed-range-pill{display:flex;align-items:center;justify-content:space-between;',
	'  gap:.5em;box-sizing:border-box}',
	'.lanspeed-range-text{flex:1 1 auto;min-width:0;',
	'  font-family:var(--font-monospace,ui-monospace,monospace)}',
	'.lanspeed-range-remove{flex:0 0 auto}',
	'.lanspeed-range-add{display:flex;gap:.5em;align-items:center}',
	'.lanspeed-range-add input{flex:1 1 auto;min-width:0}',
	'.lanspeed-range-add button{flex:0 0 auto}',
	'.lanspeed-ifcfg-table .action{text-align:right;width:17em}',
	'.lanspeed-ifcfg-table .devtags{font-size:.8em;opacity:.7;display:inline-flex;gap:.4em;flex-wrap:wrap}',
	'.lanspeed-ifcfg-table .devtag{padding:.05em .45em;border-radius:.25em;',
	'  background:var(--label-surface,rgba(128,128,128,.12))}',
	'.lanspeed-config-actions{display:flex;flex-wrap:wrap;gap:.5em;align-items:center;margin:1em 0 0 0}',
	'.lanspeed-config-actions>.spacer{flex:1 1 auto}',
	'.lanspeed-config-actions .status{font-size:.85em;opacity:.75;',
	'  font-family:var(--font-monospace,ui-monospace,monospace)}',
	'.lanspeed-ifcfg{display:flex;flex-direction:column;margin:0}',
	'.lanspeed-ifcfg-seg{display:inline-flex;gap:.35em;align-items:stretch;min-width:16em}',
	'.lanspeed-ifcfg-seg>button{flex:1 1 0;min-width:0;padding:.5em .7em;',
	'  font-size:.9em;border:1px solid var(--border,rgba(128,128,128,.3));',
	'  border-radius:.4em;background:transparent;cursor:pointer;color:inherit;',
	'  transition:background-color .1s ease,border-color .1s ease}',
	'.lanspeed-ifcfg-seg>button:hover{background:var(--label-surface,rgba(128,128,128,.1))}',
	'.lanspeed-ifcfg-seg>button.active{',
	'  background:var(--primary,var(--label-surface,rgba(80,120,200,.15)));',
	'  color:var(--primary-foreground,inherit);',
	'  border-color:var(--primary,var(--border,rgba(128,128,128,.3)));',
	'  font-weight:600}',
	'.lanspeed-ifcfg-actions{display:flex;flex-wrap:wrap;gap:.5em;align-items:center;',
	'  margin:.4em 0 0 0}',
	'.lanspeed-ifcfg-actions>.spacer{flex:1 1 auto}',
	'.lanspeed-ifcfg-actions .status{font-size:.85em;opacity:.75;',
	'  font-family:var(--font-monospace,ui-monospace,monospace)}',
	'.lanspeed-hint{margin:.8em 0 0 0;font-size:.85em;opacity:.75}',

	'.lanspeed-theme-aurora{display:flex;flex-direction:column;gap:1rem;margin:0}',
	'.lanspeed-theme-aurora>.cbi-section{margin:0;padding:0;overflow:hidden}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-body{overflow-x:auto}',
	'.lanspeed-theme-aurora .lanspeed-header{padding:1rem 1.25rem .85rem}',
	'.lanspeed-theme-aurora .lanspeed-config-body,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-body{padding:1rem 1.25rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table th,',
	'.lanspeed-theme-aurora .lanspeed-config-table td,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table th,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table td{padding:.55rem .65rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table th:nth-child(1),',
	'.lanspeed-theme-aurora .lanspeed-config-table td:nth-child(1){width:9rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table th:nth-child(2),',
	'.lanspeed-theme-aurora .lanspeed-config-table td:nth-child(2){width:18rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table .value{width:auto}',
	'.lanspeed-theme-aurora .lanspeed-config-table .value input{max-width:16rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table .value.range input{max-width:none}',
	'.lanspeed-theme-aurora .lanspeed-range-stack{max-width:26rem;gap:.5rem}',
	'.lanspeed-theme-aurora .lanspeed-range-pill{display:grid;grid-template-columns:minmax(0,1fr) auto;',
	'  gap:.5rem;align-items:center}',
	'.lanspeed-theme-aurora .lanspeed-range-remove{width:2.25rem;min-width:2.25rem;',
	'  height:2.25rem;padding:0}',
	'.lanspeed-theme-aurora .lanspeed-range-add{display:grid;grid-template-columns:minmax(0,1fr) auto;',
	'  gap:.5rem;align-items:center}',
	'.lanspeed-theme-aurora .lanspeed-range-add button{height:2.25rem}',
	'.lanspeed-theme-aurora .lanspeed-config-actions,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-actions{margin:.8rem 0 0 0}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table .action{width:19rem}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-seg{gap:.35rem;min-width:17rem}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-seg>button{padding:.48rem .7rem;',
	'  border-radius:calc(var(--radius-base, .5rem)*1.5)}',
	'@media (max-width:800px){.lanspeed-theme-aurora .lanspeed-header{padding:.85rem 1rem .7rem}',
	'.lanspeed-theme-aurora .lanspeed-config-body,',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-body{padding:.85rem 1rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table,',
	'.lanspeed-theme-aurora .lanspeed-config-table thead,',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody,',
	'.lanspeed-theme-aurora .lanspeed-config-table tr,',
	'.lanspeed-theme-aurora .lanspeed-config-table th,',
	'.lanspeed-theme-aurora .lanspeed-config-table td{display:block;width:auto}',
	'.lanspeed-theme-aurora .lanspeed-config-table thead{display:none}',
	'.lanspeed-theme-aurora .lanspeed-config-table tr{padding:.7rem 0;border-bottom:1px solid var(--border,rgba(128,128,128,.18))}',
	'.lanspeed-theme-aurora .lanspeed-config-table td{padding:.2rem 0;border-bottom:0}',
	'.lanspeed-theme-aurora .lanspeed-config-table td:nth-child(1),',
	'.lanspeed-theme-aurora .lanspeed-config-table td:nth-child(2),',
	'.lanspeed-theme-aurora .lanspeed-config-table td:nth-child(3){width:auto}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-table .action{width:auto;text-align:left}',
	'.lanspeed-theme-aurora .lanspeed-ifcfg-seg{min-width:0;width:100%}}',

	'.lanspeed-theme-argon{display:flex;flex-direction:column;gap:1rem;margin:0;font-size:1rem}',
	'.lanspeed-theme-argon>.cbi-section{margin:0;padding:0;overflow:hidden}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-body{overflow-x:auto}',
	'.lanspeed-theme-argon .lanspeed-header{padding:.95rem 1.25rem .8rem}',
	'.lanspeed-theme-argon .lanspeed-config-body,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-body{padding:1rem 1.25rem}',
	'.lanspeed-theme-argon .lanspeed-header>h3{font-size:1.35rem}',
	'.lanspeed-theme-argon .lanspeed-config-table th,.lanspeed-theme-argon .lanspeed-config-table td,.lanspeed-theme-argon .lanspeed-ifcfg-table th,.lanspeed-theme-argon .lanspeed-ifcfg-table td{padding:.68rem .75rem;font-size:1rem;line-height:1.45}',
	'.lanspeed-theme-argon .lanspeed-config-table .hint,.lanspeed-theme-argon .lanspeed-ifcfg-table .muted{font-size:.88rem;line-height:1.45}',
	'.lanspeed-theme-argon .lanspeed-config-table input,',
	'.lanspeed-theme-argon .lanspeed-config-table select{font-size:1rem}',
	'.lanspeed-theme-argon .lanspeed-config-table th:first-child,.lanspeed-theme-argon .lanspeed-config-table td:first-child,.lanspeed-theme-argon .lanspeed-ifcfg-table th:first-child,.lanspeed-theme-argon .lanspeed-ifcfg-table td:first-child{padding-left:.35rem}',
	'.lanspeed-theme-argon .lanspeed-config-table th:last-child,',
	'.lanspeed-theme-argon .lanspeed-config-table td:last-child,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table th:last-child,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table td:last-child{padding-right:0}',
	'.lanspeed-theme-argon .lanspeed-config-table th:nth-child(1),',
	'.lanspeed-theme-argon .lanspeed-config-table td:nth-child(1){width:9rem}',
	'.lanspeed-theme-argon .lanspeed-config-table th:nth-child(2),',
	'.lanspeed-theme-argon .lanspeed-config-table td:nth-child(2){width:18rem}',
	'.lanspeed-theme-argon .lanspeed-config-table .value{width:auto}',
	'.lanspeed-theme-argon .lanspeed-config-table .value input{max-width:16rem}',
	'.lanspeed-theme-argon .lanspeed-config-table .value.range input{max-width:none}',
	'.lanspeed-theme-argon .lanspeed-range-stack{max-width:26rem;gap:.55rem}',
	'.lanspeed-theme-argon .lanspeed-range-pill{display:grid;grid-template-columns:minmax(0,1fr) auto;',
	'  gap:.5rem;align-items:center}',
	'.lanspeed-theme-argon .lanspeed-range-remove{width:2.25rem;min-width:2.25rem;',
	'  height:2.25rem;padding:0}',
	'.lanspeed-theme-argon .lanspeed-range-add{display:grid;grid-template-columns:minmax(0,1fr) auto;',
	'  gap:.5rem;align-items:center}',
	'.lanspeed-theme-argon .lanspeed-range-add button{height:2.25rem}',
	'.lanspeed-theme-argon .lanspeed-config-actions,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-actions{margin:.85rem 0 0 0}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table .action{width:19rem}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-seg{gap:.35rem;min-width:17rem}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-seg>button{padding:.55rem .8rem;border-radius:.25rem;font-size:.98rem}',
	'@media (min-width:801px){.lanspeed-theme-argon .lanspeed-ifcfg-table{table-layout:fixed}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table th:nth-child(1),.lanspeed-theme-argon .lanspeed-ifcfg-table td:nth-child(1){width:16rem}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table th:nth-child(3),.lanspeed-theme-argon .lanspeed-ifcfg-table td:nth-child(3){width:21rem}}',
	'@media (min-width:801px){',
	'.lanspeed-theme-aurora .lanspeed-config-table,',
	'.lanspeed-theme-argon .lanspeed-config-table{display:block}',
	'.lanspeed-theme-aurora .lanspeed-config-table thead,',
	'.lanspeed-theme-argon .lanspeed-config-table thead{display:none}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody,',
	'.lanspeed-theme-argon .lanspeed-config-table tbody{display:block}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody tr,.lanspeed-theme-argon .lanspeed-config-table tbody tr{display:grid;',
	'  grid-template-columns:minmax(12rem,20rem) minmax(13rem,24rem);',
	'  grid-template-areas:"label control" "hint control";',
	'  column-gap:1.25rem;row-gap:.2rem;align-items:center;',
	'  padding:.68rem 0;border-bottom:1px solid var(--border,rgba(128,128,128,.18))}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody tr:last-child,',
	'.lanspeed-theme-argon .lanspeed-config-table tbody tr:last-child{border-bottom:0}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody td,',
	'.lanspeed-theme-argon .lanspeed-config-table tbody td{padding:0;border-bottom:0;text-align:left}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody td:nth-child(1),',
	'.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(1){grid-area:label;width:auto;align-self:end;font-weight:600}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody td:nth-child(2),',
	'.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(2){grid-area:control;width:auto;align-self:center;justify-self:stretch}',
	'.lanspeed-theme-aurora .lanspeed-config-table tbody td:nth-child(3),',
	'.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(3){grid-area:hint;width:auto;align-self:start}',
	'.lanspeed-theme-aurora .lanspeed-config-table .value input,',
	'.lanspeed-theme-argon .lanspeed-config-table .value input{max-width:22rem}',
	'.lanspeed-theme-aurora .lanspeed-config-table .value select,',
	'.lanspeed-theme-argon .lanspeed-config-table .value select{max-width:100%}',
	'.lanspeed-theme-aurora .lanspeed-range-stack,',
	'.lanspeed-theme-argon .lanspeed-range-stack{max-width:23rem;gap:.45rem}',
	'.lanspeed-theme-aurora .lanspeed-range-list,',
	'.lanspeed-theme-argon .lanspeed-range-list{gap:.45rem}',
	'.lanspeed-theme-aurora .lanspeed-range-pill,',
	'.lanspeed-theme-argon .lanspeed-range-pill,',
	'.lanspeed-theme-aurora .lanspeed-range-add,',
	'.lanspeed-theme-argon .lanspeed-range-add{grid-template-columns:minmax(0,1fr) auto;gap:.45rem}',
	'.lanspeed-theme-aurora .lanspeed-range-add button,.lanspeed-theme-argon .lanspeed-range-add button{min-width:4rem;height:2.25rem}',
	'.lanspeed-theme-aurora .lanspeed-range-remove,',
	'.lanspeed-theme-argon .lanspeed-range-remove{width:2.25rem;min-width:2.25rem;height:2.25rem;padding:0}}',
	'@media (max-width:800px){.lanspeed-theme-argon .lanspeed-header{padding:.85rem 1rem .7rem}',
	'.lanspeed-theme-argon .lanspeed-config-body,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-body{padding:.85rem 1rem}',
	'.lanspeed-theme-argon .lanspeed-config-table,',
	'.lanspeed-theme-argon .lanspeed-config-table thead,',
	'.lanspeed-theme-argon .lanspeed-config-table tbody,',
	'.lanspeed-theme-argon .lanspeed-config-table tr,',
	'.lanspeed-theme-argon .lanspeed-config-table th,',
	'.lanspeed-theme-argon .lanspeed-config-table td{display:block;width:auto}',
	'.lanspeed-theme-argon .lanspeed-config-table thead{display:none}',
	'.lanspeed-theme-argon .lanspeed-config-table tr{padding:.75rem 0;border-bottom:1px solid var(--border,rgba(128,128,128,.18))}',
	'.lanspeed-theme-argon .lanspeed-config-table td{padding:.2rem 0;border-bottom:0}',
	'.lanspeed-theme-argon .lanspeed-config-table td:nth-child(1),',
	'.lanspeed-theme-argon .lanspeed-config-table td:nth-child(2),',
	'.lanspeed-theme-argon .lanspeed-config-table td:nth-child(3){width:auto}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table .action{width:auto;text-align:left}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-seg{min-width:0;width:100%}}'
].join('\n');

return baseclass.extend({
	CSS: CONFIG_CSS
});
