'use strict';
'require baseclass';

/* Argon uses compact square-edged rows and its dynamic primary color. */
var ARGON_CSS = [
	'.lanspeed-config-root.lanspeed-theme-argon{font-size:1rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-header{padding:.95rem 1.25rem .8rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-subheader{padding:.95rem 1.25rem .8rem;background-color:transparent}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-subheader>h4{font-size:1.3rem;line-height:1.25!important}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-header>h3{font-size:1.3rem;line-height:1.25!important}',
	'.lanspeed-config-root.lanspeed-theme-argon :is(.lanspeed-header,.lanspeed-config-subheader)>.sum{padding-left:.55rem;',
		'border-left:.18rem solid var(--lanspeed-accent-safe);line-height:1.25}',
	'.lanspeed-config-root.lanspeed-theme-argon :is(.lanspeed-config-body,.lanspeed-ifcfg-body){',
		'padding:1rem 1.25rem 1.1rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .label{min-height:1.7rem;padding:.28rem .65rem!important}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-toggle>input[type="checkbox"]{',
		'position:static;top:auto;right:auto;bottom:auto;left:auto;vertical-align:middle}',
	'.lanspeed-config-root.lanspeed-theme-argon :is(.lanspeed-config-table,.lanspeed-ifcfg-table) :is(th,td){',
		'border-top:0;font-size:.96rem;line-height:1.45}',
	'.lanspeed-config-root.lanspeed-theme-argon :is(.lanspeed-range-stack,.lanspeed-range-list){gap:.45rem;max-width:none}',
	'.lanspeed-config-root.lanspeed-theme-argon :is(.lanspeed-range-pill,.lanspeed-range-add){',
		'display:grid;grid-template-columns:minmax(0,1fr) auto;gap:.45rem;align-items:center}',
	'.lanspeed-config-root.lanspeed-theme-argon :is(.lanspeed-range-text,.lanspeed-range-value,.lanspeed-range-add>input){',
		'height:2.5rem;min-height:2.5rem;max-width:none}',
	'.lanspeed-config-root.lanspeed-theme-argon :is(.lanspeed-range-text,.lanspeed-range-value){display:flex;align-items:center}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-range-remove{width:2.5rem;min-width:2.5rem;padding:0}',
	'.lanspeed-config-root.lanspeed-theme-argon :is(.lanspeed-range-remove,.lanspeed-range-add>button){',
		'height:2.5rem;min-height:2.5rem}',
	'.lanspeed-config-root.lanspeed-theme-argon :is(.cbi-button,.lanspeed-ifcfg-seg>button){',
		'display:inline-flex;align-items:center;justify-content:center;min-height:2.5rem;font-size:.96rem;line-height:1.2}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-seg{display:grid;',
		'grid-template-columns:repeat(3,minmax(0,1fr));width:100%;min-width:0;gap:.35rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-hint:empty{display:none}',
	'@media (min-width:801px){',
	'.lanspeed-theme-argon :is(.lanspeed-config-table,.lanspeed-ifcfg-table){display:block}',
	'.lanspeed-theme-argon :is(.lanspeed-config-table,.lanspeed-ifcfg-table) thead{display:none}',
	'.lanspeed-theme-argon .lanspeed-config-table tbody{display:grid;',
		'grid-template-columns:repeat(2,minmax(0,1fr));column-gap:1.25rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody tr{display:grid;',
		'grid-template-columns:minmax(10rem,1fr) minmax(12rem,15rem);',
		'grid-template-areas:"label control" "hint control";grid-template-rows:auto 1fr;',
		'column-gap:1rem;row-gap:.2rem;align-items:start;min-width:0;padding:.78rem 0;',
		'border-bottom:1px solid var(--lanspeed-border);background:transparent}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody :is(th,td){',
		'width:auto;min-width:0;padding:0;border:0}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody :is(th,td):nth-child(1){grid-area:label;font-weight:600}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody :is(th,td):nth-child(2){grid-area:control;justify-self:stretch}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody :is(th,td):nth-child(3){grid-area:hint}',
	'.lanspeed-theme-argon .lanspeed-config-table .value :is(input:not([type="checkbox"]),select){',
		'width:100%;max-width:none}',
	'.lanspeed-theme-argon .lanspeed-rate-control{display:grid;grid-template-columns:minmax(0,1fr);gap:.35rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody tr.lanspeed-private-ipv6-row{',
		'grid-column:1/-1;grid-template-columns:minmax(14rem,1fr) minmax(12rem,15rem)}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody tr.lanspeed-range-row{',
		'grid-column:1/-1;grid-template-columns:minmax(14rem,1fr) minmax(18rem,25rem)}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody{display:grid;',
		'grid-template-columns:repeat(2,minmax(0,1fr));column-gap:1rem}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody tr{display:grid;',
		'grid-template-columns:minmax(0,1fr) auto;grid-template-areas:"iface badge" "action action";',
		'gap:.45rem .75rem;min-width:0;padding:.72rem 0;border-bottom:1px solid var(--lanspeed-border);',
		'background:transparent}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-ifcfg-table tbody td{width:auto;min-width:0;padding:0;border:0}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody td:nth-child(1){grid-area:iface;overflow-wrap:anywhere}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody td:nth-child(2){grid-area:badge;justify-self:end}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody td.action{grid-area:action;width:auto}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table .devtags{justify-content:flex-end}',
	'}',
	'@media (min-width:801px) and (max-width:1100px){',
	'.lanspeed-theme-argon :is(.lanspeed-config-table,.lanspeed-ifcfg-table) tbody{',
		'grid-template-columns:minmax(0,1fr)}}',
	'@media (max-width:800px){',
	'.lanspeed-theme-argon{--lanspeed-mobile-config-row-padding:.75rem 0;',
		'--lanspeed-mobile-ifcfg-row-padding:.7rem 0;--lanspeed-mobile-seg-padding:.5rem .35rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-header{padding:.85rem 1rem .7rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-subheader{padding:.85rem 1rem .7rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-header>h3{font-size:1.3rem;line-height:1.25}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-subheader>h4{font-size:1.22rem}',
	'.lanspeed-config-root.lanspeed-theme-argon :is(.lanspeed-config-body,.lanspeed-ifcfg-body){',
		'padding:.8rem 1rem .9rem}',
	'.lanspeed-theme-argon :is(.lanspeed-config-table,.lanspeed-ifcfg-table) tbody tr{',
		'border-bottom:1px solid var(--lanspeed-border);background:transparent}}'
].join('\n');

return baseclass.extend({
	CSS: ARGON_CSS
});
