'use strict';
'require baseclass';

/* Argon uses compact square-edged setting blocks and a two-column rhythm. */
var ARGON_CSS = [
	'.lanspeed-theme-argon{font-size:1rem}',
	'.lanspeed-theme-argon .lanspeed-header{padding:.95rem 1.25rem .8rem;align-items:center}',
	'.lanspeed-theme-argon .lanspeed-header>h3{font-size:1.35rem;line-height:1.25!important}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-header>.sum{line-height:1.25}',
	'.lanspeed-theme-argon .lanspeed-config-body,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-body{padding:1rem 1.25rem 1.1rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .label{display:inline-flex;align-items:center;',
	'  justify-content:center;min-height:1.75rem;padding:.3rem .7rem!important;',
	'  box-sizing:border-box;line-height:1.15!important;vertical-align:middle}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-current-rate-source{align-items:center;line-height:1.5rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table th,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table td,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-ifcfg-table th,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-ifcfg-table td{',
	'  border-top:0;font-size:1rem;line-height:1.45}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table .hint,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-ifcfg-table .muted{font-size:.88rem;line-height:1.45}',
	'.lanspeed-theme-argon .lanspeed-config-table input,',
	'.lanspeed-theme-argon .lanspeed-config-table select{font-size:1rem}',
	'.lanspeed-theme-argon .lanspeed-range-stack,',
	'.lanspeed-theme-argon .lanspeed-range-list{gap:.45rem;max-width:none}',
	'.lanspeed-theme-argon .lanspeed-range-pill,',
	'.lanspeed-theme-argon .lanspeed-range-add{display:grid;grid-template-columns:minmax(0,1fr) auto;',
	'  gap:.45rem;align-items:center}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-range-text,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-range-add>input{',
	'  height:2.5rem;min-height:2.5rem;max-width:none;box-sizing:border-box}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-range-remove{',
	'  width:2.5rem;min-width:2.5rem;padding-left:0;padding-right:0}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-range-remove,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-range-add>button{',
	'  height:2.5rem;min-height:2.5rem;padding-top:0;padding-bottom:0}',
	'.lanspeed-config-root.lanspeed-theme-argon .cbi-button,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-ifcfg-seg>button{',
	'  display:inline-flex;align-items:center;justify-content:center;box-sizing:border-box;',
	'  min-height:2.5rem;font-size:1rem;line-height:1.2;vertical-align:middle}',
	'.lanspeed-theme-argon .lanspeed-config-actions,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-actions{margin:.8rem 0 0}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-seg{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));',
	'  width:100%;min-width:0;gap:.35rem}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-seg>button{padding:.55rem .55rem;border-radius:.25rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-hint{padding:0}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-hint:empty{display:none}',
	'@media (min-width:801px){',
	'.lanspeed-theme-argon .lanspeed-config-table,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table{display:block}',
	'.lanspeed-theme-argon .lanspeed-config-table thead,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table thead{display:none}',
	'.lanspeed-theme-argon .lanspeed-config-table tbody{display:grid;',
	'  grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody tr{display:grid;',
	'  grid-template-columns:minmax(10rem,1fr) minmax(12rem,15rem);',
	'  grid-template-areas:"label control" "hint control";grid-template-rows:auto 1fr;',
	'  column-gap:1rem;row-gap:.2rem;',
	'  align-items:start;align-content:start;min-width:0;padding:.82rem .9rem;border:0;',
	'  border-radius:.35rem;background:rgba(94,113,229,.045);',
	'  background:color-mix(in srgb,currentColor 4%,transparent)}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody td{',
	'  width:auto;padding:0;border:0;text-align:left;min-width:0}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(1){',
	'  grid-area:label;align-self:start;font-weight:600}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(2){',
	'  grid-area:control;align-self:start;justify-self:stretch}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(3){',
	'  grid-area:hint;align-self:start;padding-left:0}',
	'.lanspeed-theme-argon .lanspeed-config-table .value input:not([type="checkbox"]),',
	'.lanspeed-theme-argon .lanspeed-config-table .value select{width:100%;max-width:none;box-sizing:border-box}',
	'.lanspeed-theme-argon .lanspeed-rate-control{display:grid;grid-template-columns:minmax(0,1fr);',
	'  align-items:start;gap:.35rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody tr.lanspeed-private-ipv6-row{',
	'  grid-column:1/-1;grid-template-columns:minmax(14rem,1fr) minmax(12rem,15rem)}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody tr.lanspeed-range-row{',
	'  grid-column:1/-1;grid-template-columns:minmax(14rem,1fr) minmax(18rem,25rem);',
	'  grid-template-areas:"label control" "hint control";grid-template-rows:auto 1fr;min-height:0}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody{display:grid;',
	'  grid-template-columns:repeat(2,minmax(0,1fr));gap:.55rem}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody tr{display:grid;',
	'  grid-template-columns:minmax(0,1fr) auto;grid-template-areas:"iface badge" "action action";',
	'  gap:.45rem .75rem;min-width:0;padding:.75rem .85rem;border:0;border-radius:.35rem;',
	'  background:rgba(94,113,229,.045);background:color-mix(in srgb,currentColor 4%,transparent)}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-ifcfg-table tbody td{',
	'  width:auto;min-width:0;padding:0;border:0}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody td:nth-child(1){grid-area:iface;align-self:center}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody td:nth-child(1){white-space:normal;overflow-wrap:anywhere}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody td:nth-child(2){grid-area:badge;',
	'  align-self:center;justify-self:end;text-align:right}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody td.action{grid-area:action;width:auto}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table .devtags{justify-content:flex-end}',
	'}',
	'@media (min-width:801px) and (max-width:1100px){',
	'.lanspeed-theme-argon .lanspeed-config-table tbody,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody{grid-template-columns:minmax(0,1fr)}',
	'}',
	'@media (max-width:800px){',
	'.lanspeed-theme-argon{--lanspeed-mobile-config-row-padding:.78rem .75rem;',
	'  --lanspeed-mobile-ifcfg-row-padding:.72rem .75rem;--lanspeed-mobile-seg-padding:.5rem .35rem}',
	'.lanspeed-theme-argon .lanspeed-header{padding:.85rem 1rem .7rem}',
	'.lanspeed-theme-argon .lanspeed-header>h3{font-size:1.25rem}',
	'.lanspeed-theme-argon .lanspeed-config-body,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-body{padding:.8rem .85rem .9rem}',
	'.lanspeed-theme-argon .lanspeed-config-table tbody,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody{gap:.5rem}',
	'.lanspeed-theme-argon .lanspeed-config-table tbody tr,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table tbody tr{border:0;border-radius:.35rem;',
	'  background:rgba(94,113,229,.045);background:color-mix(in srgb,currentColor 4%,transparent)}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(3){padding-left:0}',
	'.lanspeed-theme-argon .lanspeed-range-stack{gap:.45rem}',
	'}'
].join('\n');

return baseclass.extend({
	CSS: ARGON_CSS
});
