'use strict';
'require baseclass';

/* Argon-only configuration layout overrides. */
var ARGON_CSS = [
	'.lanspeed-theme-argon{font-size:1rem}',
	'.lanspeed-theme-argon .lanspeed-header{padding:.95rem 1.25rem .8rem;align-items:center}',
	'.lanspeed-theme-argon .lanspeed-config-body,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-body{padding:1rem 1.25rem}',
	'.lanspeed-theme-argon .lanspeed-header>h3{font-size:1.35rem;line-height:1.25!important}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-header>.sum{line-height:1.25}',
	'.lanspeed-config-root.lanspeed-theme-argon .label{display:inline-flex;align-items:center;',
	'  justify-content:center;min-height:1.75rem;padding:.3rem .7rem!important;',
	'  box-sizing:border-box;line-height:1.15!important;vertical-align:middle}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-current-rate-source{align-items:center;line-height:1.5rem}',
	'.lanspeed-theme-argon .lanspeed-config-table th,.lanspeed-theme-argon .lanspeed-config-table td,.lanspeed-theme-argon .lanspeed-ifcfg-table th,.lanspeed-theme-argon .lanspeed-ifcfg-table td{padding:.68rem .75rem;font-size:1rem;line-height:1.45}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table th,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table td,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-ifcfg-table th,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-ifcfg-table td{border-top:0}',
	'.lanspeed-theme-argon .lanspeed-config-table .hint,.lanspeed-theme-argon .lanspeed-ifcfg-table .muted{font-size:.88rem;line-height:1.45}',
	'.lanspeed-theme-argon .lanspeed-config-table input,',
	'.lanspeed-theme-argon .lanspeed-config-table select{font-size:1rem}',
	'.lanspeed-theme-argon .lanspeed-config-table th:first-child,.lanspeed-theme-argon .lanspeed-config-table td:first-child,.lanspeed-theme-argon .lanspeed-ifcfg-table th:first-child,.lanspeed-theme-argon .lanspeed-ifcfg-table td:first-child{padding-left:.35rem}',
	'.lanspeed-theme-argon .lanspeed-config-table th:last-child,',
	'.lanspeed-theme-argon .lanspeed-config-table td:last-child,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table th:last-child,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table td:last-child{padding-right:0}',
	'.lanspeed-theme-argon .lanspeed-range-stack{gap:.55rem}',
	'.lanspeed-theme-argon .lanspeed-config-actions,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-actions{margin:.85rem 0 0 0}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-seg>button{padding:.55rem .8rem;border-radius:.25rem;font-size:.98rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-range-text,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-range-add>input{',
	'  height:2.5rem;min-height:2.5rem;box-sizing:border-box}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-range-remove{',
	'  width:2.5rem;min-width:2.5rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-range-remove,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-range-add>button{',
	'  height:2.5rem;min-height:2.5rem;padding-top:0;padding-bottom:0}',
	'.lanspeed-config-root.lanspeed-theme-argon .cbi-button,',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-ifcfg-seg>button{',
	'  display:inline-flex;align-items:center;justify-content:center;box-sizing:border-box;',
	'  min-height:2.5rem;font-size:1rem;line-height:1.2;vertical-align:middle}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-hint{padding:0}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-hint:empty{display:none}',
	'@media (min-width:801px){.lanspeed-theme-argon .lanspeed-ifcfg-table{table-layout:fixed}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table th:nth-child(1),.lanspeed-theme-argon .lanspeed-ifcfg-table td:nth-child(1){width:16rem}',
	'.lanspeed-theme-argon .lanspeed-ifcfg-table th:nth-child(3),.lanspeed-theme-argon .lanspeed-ifcfg-table td:nth-child(3){width:21rem}}',
	'@media (min-width:801px){',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody tr{align-items:start;align-content:start}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(1),',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(2){align-self:start}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody td:nth-child(3){padding-left:.35rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody tr.lanspeed-range-row{position:relative;min-height:7rem}',
	'.lanspeed-config-root.lanspeed-theme-argon .lanspeed-config-table tbody tr.lanspeed-range-row>td.hint{',
	'  position:absolute;grid-column:1;grid-row:1;align-self:start;',
	'  margin-top:calc(1.45rem + .2rem);width:min(20rem,calc(50% - 1.125rem))}',
	'}',
	'@media (max-width:800px){.lanspeed-theme-argon{',
	'  --lanspeed-mobile-config-row-padding:.75rem 0;',
	'  --lanspeed-mobile-ifcfg-row-padding:.75rem 0}',
	'.lanspeed-theme-argon .lanspeed-header{padding:.85rem 1rem .7rem}',
	'.lanspeed-theme-argon .lanspeed-config-body,',
	'.lanspeed-theme-argon .lanspeed-ifcfg-body{padding:.85rem 1rem}}'
].join('\n');

return baseclass.extend({
	CSS: ARGON_CSS
});
