'use strict';
'require baseclass';

/* Theme-neutral configuration layout CSS shared by all LuCI themes. */
var BASE_CSS = [
	'.lanspeed-config-root{font-weight:400}',
	'.lanspeed-config-root .cbi-section{font-weight:400}',
	'.lanspeed-header{display:flex;flex-wrap:wrap;gap:.4em 1em;align-items:baseline;',
	'  padding:1em 1.25em .75em 1.25em;margin:0;',
	'  border-bottom:1px solid var(--border,rgba(128,128,128,.25))}',
	'.lanspeed-header>h3{margin:0;padding:0;border:0;width:auto;display:inline;',
	'  flex:0 0 auto;background:transparent;box-shadow:none;line-height:1.25;font-weight:600}',
	'.lanspeed-header>.spacer{flex:1 1 auto}',
	'.lanspeed-header>.sum{font-size:.85em;opacity:.75;',
	'  font-family:var(--font-monospace,ui-monospace,monospace)}',
	'.lanspeed-config-body,.lanspeed-ifcfg-body{padding:1em 1.25em}',
	'.lanspeed-config-table,.lanspeed-ifcfg-table{width:100%;border-collapse:collapse;margin:0}',
	'.lanspeed-config-table th,.lanspeed-config-table td,',
	'.lanspeed-ifcfg-table th,.lanspeed-ifcfg-table td{padding:.6em .6em;text-align:left;',
	'  border-bottom:1px solid var(--border,rgba(128,128,128,.18));vertical-align:middle}',
	'.lanspeed-config-table tbody tr:last-child td,',
	'.lanspeed-ifcfg-table tbody tr:last-child td{border-bottom:0}',
	'.lanspeed-config-table th:first-child,.lanspeed-config-table td:first-child,',
	'.lanspeed-ifcfg-table th:first-child,.lanspeed-ifcfg-table td:first-child{padding-left:0}',
	'.lanspeed-config-table th:last-child,.lanspeed-config-table td:last-child,',
	'.lanspeed-ifcfg-table th:last-child,.lanspeed-ifcfg-table td:last-child{padding-right:0}',
	'.lanspeed-config-table thead th,.lanspeed-ifcfg-table thead th{font-weight:600;opacity:.85}',
	'.lanspeed-config-table .key,.lanspeed-ifcfg-table .mono{font-family:var(--font-monospace,ui-monospace,monospace);',
	'  font-size:.9em;white-space:nowrap}',
	'.lanspeed-config-table .value{width:12em}',
	'.lanspeed-config-table .value.rate{width:16em}',
	'.lanspeed-config-table .value input{width:100%;max-width:12em}',
	'.lanspeed-config-table .value.range{width:18em}',
	'.lanspeed-config-table .value.range input{max-width:none}',
	'.lanspeed-config-table .hint,.lanspeed-ifcfg-table .muted{font-size:.85em;opacity:.72}',
	'.lanspeed-rate-control{display:flex;flex-wrap:wrap;align-items:center;gap:.45em}',
	'.lanspeed-current-rate-source{display:inline-flex;align-items:baseline;gap:.25em;',
	'  font-size:.85em;white-space:nowrap}',
	'.lanspeed-current-rate-source>.label{opacity:.7}',
	'.lanspeed-range-stack{display:flex;flex-direction:column;gap:.6em;align-items:stretch;max-width:22em}',
	'.lanspeed-range-list{display:flex;flex-direction:column;gap:.6em}',
	'.lanspeed-range-pill{display:flex;align-items:center;justify-content:space-between;',
	'  gap:.5em;box-sizing:border-box}',
	'.lanspeed-range-text{flex:1 1 auto;min-width:0;',
	'  font-family:var(--font-monospace,ui-monospace,monospace)}',
	'.lanspeed-range-remove{flex:0 0 auto}',
	'.lanspeed-range-add{display:flex;gap:.5em;align-items:center}',
	'.lanspeed-range-add input{flex:1 1 auto;min-width:0}',
	'.lanspeed-range-add button{flex:0 0 auto}',
	'.lanspeed-ifcfg-table .action{text-align:right;width:17em}',
	'.lanspeed-ifcfg-table .devtags{font-size:.8em;opacity:.7;display:inline-flex;gap:.4em;flex-wrap:wrap}',
	'.lanspeed-ifcfg-table .devtag{padding:.05em .45em;border-radius:.25em;',
	'  background:var(--label-surface,rgba(128,128,128,.12))}',
	'.lanspeed-config-actions{display:flex;flex-wrap:wrap;gap:.5em;align-items:center;margin:1em 0 0 0}',
	'.lanspeed-config-actions>.spacer{flex:1 1 auto}',
	'.lanspeed-config-actions .status{font-size:.85em;opacity:.75;',
	'  font-family:var(--font-monospace,ui-monospace,monospace)}',
	'.lanspeed-ifcfg{display:flex;flex-direction:column;margin:0}',
	'.lanspeed-ifcfg-seg{display:inline-flex;gap:.35em;align-items:stretch;min-width:16em}',
	'.lanspeed-ifcfg-seg>button{flex:1 1 0;min-width:0;padding:.5em .7em;',
	'  font-size:.9em;border:1px solid var(--border,rgba(128,128,128,.3));',
	'  border-radius:.4em;background:transparent;cursor:pointer;color:inherit;',
	'  transition:background-color .1s ease,border-color .1s ease}',
	'.lanspeed-ifcfg-seg>button:hover{background:var(--label-surface,rgba(128,128,128,.1))}',
	'.lanspeed-ifcfg-seg>button.active{',
	'  background:var(--primary,var(--label-surface,rgba(80,120,200,.15)));',
	'  color:var(--primary-foreground,inherit);',
	'  border-color:var(--primary,var(--border,rgba(128,128,128,.3)));',
	'  font-weight:600}',
	'.lanspeed-ifcfg-actions{display:flex;flex-wrap:wrap;gap:.5em;align-items:center;',
	'  margin:.4em 0 0 0}',
	'.lanspeed-ifcfg-actions>.spacer{flex:1 1 auto}',
	'.lanspeed-ifcfg-actions .status{font-size:.85em;opacity:.75;',
	'  font-family:var(--font-monospace,ui-monospace,monospace)}',
	'.lanspeed-hint{margin:.8em 0 0 0;font-size:.85em;opacity:.75}',

].join('\n');

return baseclass.extend({
	CSS: BASE_CSS
});
