'use strict';
'require baseclass';

/* Bootstrap keeps a classic table hierarchy with quiet zebra surfaces. */
var BOOTSTRAP_CSS = [
	'.lanspeed-theme-bootstrap{display:flex;flex-direction:column;gap:.75rem;margin:0}',
	'.lanspeed-theme-bootstrap>.cbi-section{margin:0;padding:0}',
	'.lanspeed-theme-bootstrap .lanspeed-header{padding:.75rem 1rem .55rem;align-items:center}',
	'.lanspeed-theme-bootstrap .lanspeed-config-body,',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-body{padding:.55rem 1rem .85rem}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table,',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-table{border-collapse:separate;border-spacing:0 .3rem}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table thead th,',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-table thead th{padding:.45rem .65rem;',
	'  border-top:0;border-bottom:1px solid var(--border-color-low,var(--border,rgba(128,128,128,.2)))}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table tbody td,',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-table tbody td{padding:.52rem .65rem;border:0}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table tbody tr:nth-child(odd)>td,',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-table tbody tr:nth-child(odd)>td{',
	'  background:var(--background-color-medium,rgba(127,127,127,.055))}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table tbody tr:nth-child(odd)>td:first-child,',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-table tbody tr:nth-child(odd)>td:first-child{',
	'  border-radius:.3rem 0 0 .3rem}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table tbody tr:nth-child(odd)>td:last-child,',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-table tbody tr:nth-child(odd)>td:last-child{',
	'  border-radius:0 .3rem .3rem 0}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table th:nth-child(1),',
	'.lanspeed-theme-bootstrap .lanspeed-config-table td:nth-child(1){width:18%}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table th:nth-child(2),',
	'.lanspeed-theme-bootstrap .lanspeed-config-table td:nth-child(2){width:20%}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table .value{width:auto}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table .value input:not([type="checkbox"]),',
	'.lanspeed-theme-bootstrap .lanspeed-config-table .value select{width:100%;max-width:15rem;box-sizing:border-box}',
	'.lanspeed-theme-bootstrap .lanspeed-rate-control{gap:.4rem}',
	'.lanspeed-theme-bootstrap .lanspeed-range-stack{max-width:17rem;gap:.4rem}',
	'.lanspeed-theme-bootstrap .lanspeed-range-list{gap:.4rem}',
	'.lanspeed-theme-bootstrap .lanspeed-range-pill,',
	'.lanspeed-theme-bootstrap .lanspeed-range-add{display:grid;grid-template-columns:minmax(0,1fr) auto;',
	'  gap:.35rem;align-items:center}',
	'.lanspeed-theme-bootstrap .lanspeed-range-text,',
	'.lanspeed-theme-bootstrap .lanspeed-range-add input{max-width:none!important}',
	'.lanspeed-theme-bootstrap .lanspeed-range-remove{width:2.25rem;min-width:2.25rem;height:2.25rem;padding:0}',
	'.lanspeed-theme-bootstrap .lanspeed-range-add button{height:2.25rem}',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-table .action{width:18rem}',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-seg{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));',
	'  gap:0;min-width:17rem}',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-seg>button{min-height:2.25rem;border-radius:0;',
	'  padding:.45rem .55rem}',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-seg>button+button{margin-left:-1px}',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-seg>button:first-child{border-radius:.3rem 0 0 .3rem}',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-seg>button:last-child{border-radius:0 .3rem .3rem 0}',
	'.lanspeed-theme-bootstrap .lanspeed-config-actions,',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-actions{margin:.65rem 0 0}',
	'.lanspeed-theme-bootstrap .lanspeed-hint{margin:.65rem 0 0}',
	'@media (max-width:800px){',
	'.lanspeed-theme-bootstrap{--lanspeed-mobile-config-row-padding:.7rem .65rem;',
	'  --lanspeed-mobile-ifcfg-row-padding:.7rem .65rem;--lanspeed-mobile-seg-padding:.5rem .25rem;',
	'  gap:.6rem}',
	'.lanspeed-theme-bootstrap>.cbi-section{overflow:hidden}',
	'.lanspeed-theme-bootstrap .lanspeed-header{padding:.75rem .75rem .6rem}',
	'.lanspeed-theme-bootstrap .lanspeed-config-body,',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-body{padding:.65rem .6rem .8rem}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table,',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-table{border-spacing:0}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table tbody,',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-table tbody{gap:.35rem}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table tbody tr:nth-child(odd),',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-table tbody tr:nth-child(odd){',
	'  border-radius:.3rem;background:var(--background-color-medium,rgba(127,127,127,.055))}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table tbody tr>td,',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-table tbody tr>td{background:transparent!important;',
	'  border-radius:0!important}',
	'.lanspeed-theme-bootstrap .lanspeed-config-table .value input:not([type="checkbox"]),',
	'.lanspeed-theme-bootstrap .lanspeed-config-table .value select{max-width:none}',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-seg{width:100%;min-width:0}',
	'.lanspeed-theme-bootstrap .lanspeed-ifcfg-seg>button{line-height:1.25}',
	'}'
].join('\n');

return baseclass.extend({
	CSS: BOOTSTRAP_CSS
});
