'use strict';
'require baseclass';

/*
 * Product contract shared by the three page shells.  This layer owns only
 * semantic variables, focus/disabled behavior and table primitives; each
 * native theme supplies the actual values and page geometry.
 */
var ROOT = ':is(.lanspeed-root,.lanspeed-config-root,.lanspeed-diagnostics-root,.lanspeed-connection-detail)';

var BASE_CSS = [
	ROOT + '{',
		'--lanspeed-page-bg:transparent;--lanspeed-surface:transparent;',
		'--lanspeed-surface-muted:transparent;--lanspeed-surface-sunken:transparent;',
		'--lanspeed-surface-raised:transparent;',
		'--lanspeed-text:inherit;--lanspeed-text-muted:inherit;--lanspeed-text-subtle:inherit;',
		'--lanspeed-border:currentColor;--lanspeed-border-strong:currentColor;',
		'--lanspeed-accent:currentColor;--lanspeed-accent-safe:var(--lanspeed-accent);',
		'--lanspeed-accent-contrast:inherit;--lanspeed-accent-soft:transparent;',
		'--lanspeed-action-bg:var(--lanspeed-accent);--lanspeed-action-hover:var(--lanspeed-accent);',
		'--lanspeed-action-text:var(--lanspeed-accent-contrast);',
		'--lanspeed-action-hover-text:var(--lanspeed-action-text);',
		'--lanspeed-action-border:var(--lanspeed-accent);',
		'--lanspeed-hover:transparent;--lanspeed-control-bg:transparent;',
		'--lanspeed-control-border:currentColor;--lanspeed-normal:var(--lanspeed-accent);',
		'--lanspeed-normal-soft:var(--lanspeed-accent-soft);--lanspeed-normal-border:var(--lanspeed-accent);',
		'--lanspeed-normal-text:var(--lanspeed-text);',
		'--lanspeed-warning:currentColor;--lanspeed-warning-soft:transparent;',
		'--lanspeed-warning-border:currentColor;--lanspeed-danger:currentColor;',
		'--lanspeed-danger-soft:transparent;--lanspeed-danger-border:currentColor;',
		'--lanspeed-info:var(--lanspeed-accent);--lanspeed-info-soft:var(--lanspeed-accent-soft);',
		'--lanspeed-info-border:var(--lanspeed-info);',
		'--lanspeed-focus-color:var(--lanspeed-accent);',
		'--lanspeed-focus-ring:0 0 0 .18rem var(--lanspeed-focus-color);',
		'--lanspeed-radius-section:.5rem;--lanspeed-radius-control:.4rem;',
		'--lanspeed-radius-input:var(--lanspeed-radius-control);',
		'--lanspeed-radius-button:var(--lanspeed-radius-control);',
		'--lanspeed-radius-compact:var(--lanspeed-radius-control);',
		'--lanspeed-radius-badge:999px;--lanspeed-shadow-section:none;',
		'--lanspeed-shadow-raised:none;--lanspeed-disabled-opacity:.45;',
		'--lanspeed-page-gap:1rem;--lanspeed-section-x:1.25rem;',
		'--lanspeed-section-y:1rem;--lanspeed-control-height:2.35rem;',
		'--lanspeed-transition:120ms ease;box-sizing:border-box;',
		'color:var(--lanspeed-text);background-color:var(--lanspeed-page-bg)}',
	ROOT + ' *, ' + ROOT + ' *::before, ' + ROOT + ' *::after{box-sizing:border-box}',
	ROOT + ' [hidden]{display:none!important}',
	ROOT + ' :is(button,input,select,textarea){max-width:100%;font:inherit;letter-spacing:0}',
	ROOT + ' :is(button,input,select,textarea):disabled,' + ROOT + ' [aria-disabled="true"]{',
		'cursor:not-allowed!important;opacity:var(--lanspeed-disabled-opacity)}',
	ROOT + '>:is(.cbi-section,.lanspeed-config-subsection,.lanspeed-ifcfg){margin:0;',
		'border:1px solid var(--lanspeed-border);',
		'border-radius:var(--lanspeed-radius-section);background-color:var(--lanspeed-surface);',
		'box-shadow:var(--lanspeed-shadow-section);color:var(--lanspeed-text);overflow:hidden}',
	ROOT + ' :is(.lanspeed-header,.lanspeed-config-subheader,.lanspeed-diagnostics-header,.lanspeed-details>summary){',
		'border-bottom-color:var(--lanspeed-border);background-color:var(--lanspeed-surface-raised)}',
	ROOT + ' :is(.meta,.sum,.hint,.muted,.lanspeed-hint,.lanspeed-diagnostics-meta,',
		'.lanspeed-diagnostics-privacy,.lanspeed-diagnostic-description,.lanspeed-diagnostic-meta,',
		'.lanspeed-diagnostic-panel-description,.lanspeed-diagnostic-panel-meta,',
		'.lanspeed-diagnostic-fact-label,.lanspeed-diagnostic-stage-meta,',
		'.lanspeed-connection-breadcrumb-current,.lanspeed-connection-client-kicker,',
		'.lanspeed-connection-meta-heading-label,.lanspeed-connection-meta-label,',
		'.lanspeed-connection-summary-label,.lanspeed-connection-footer){',
		'color:var(--lanspeed-text-muted);opacity:1}',

	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea){min-height:var(--lanspeed-control-height);',
		'border-color:var(--lanspeed-control-border)!important;',
		'border-radius:var(--lanspeed-radius-input)!important;',
		'background-color:var(--lanspeed-control-bg)!important;color:var(--lanspeed-text)!important;',
		'transition:border-color var(--lanspeed-transition),box-shadow var(--lanspeed-transition),',
		'background-color var(--lanspeed-transition)}',
	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea):hover:not(:disabled){',
		'border-color:var(--lanspeed-accent-safe)!important}',
	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea):focus{outline:0!important;',
		'border-color:var(--lanspeed-focus-color)!important;box-shadow:var(--lanspeed-focus-ring)!important}',
	ROOT + ' :is(input[type="checkbox"],input[type="radio"]){',
		'accent-color:var(--lanspeed-switch-accent-safe,var(--lanspeed-accent));',
		'color:var(--lanspeed-text)!important}',
	ROOT + ' :is(input[type="checkbox"],input[type="radio"]):focus-visible{',
		'outline:2px solid var(--lanspeed-focus-color);outline-offset:3px}',

	ROOT + ' .cbi-button,' + ROOT + ' .lanspeed-ifcfg-seg>button{',
		'border-radius:var(--lanspeed-radius-button);',
		'border-color:var(--lanspeed-control-border)!important;',
		'background-color:var(--lanspeed-surface-muted)!important;color:var(--lanspeed-text)!important;',
		'transition:border-color var(--lanspeed-transition),box-shadow var(--lanspeed-transition),',
		'background-color var(--lanspeed-transition),color var(--lanspeed-transition)}',
	ROOT + ' .cbi-button:hover:not(:disabled),' + ROOT + ' .lanspeed-ifcfg-seg>button:hover:not(:disabled){',
		'border-color:var(--lanspeed-accent-safe)!important;box-shadow:var(--lanspeed-shadow-raised)}',
	ROOT + ' .cbi-button.cbi-button-action{border-color:var(--lanspeed-action-border)!important;',
		'background-color:var(--lanspeed-action-bg)!important;color:var(--lanspeed-action-text)!important}',
	ROOT + ' .cbi-button.cbi-button-action:hover:not(:disabled){',
		'background-color:var(--lanspeed-action-hover)!important;color:var(--lanspeed-action-hover-text)!important}',
	ROOT + ' .cbi-button:focus,' + ROOT + ' .lanspeed-ifcfg-seg>button:focus{',
		'outline:0!important;border-color:var(--lanspeed-focus-color)!important;',
		'box-shadow:var(--lanspeed-focus-ring)!important}',
	ROOT + ' .lanspeed-ifcfg-seg>button.active,' + ROOT + ' .lanspeed-connection-protocol[aria-pressed="true"]{',
		'border-color:var(--lanspeed-accent-safe)!important;background-color:var(--lanspeed-accent-soft)!important;',
		'color:var(--lanspeed-text)!important;box-shadow:inset 0 0 0 1px var(--lanspeed-accent-safe)}',

	ROOT + ' .label{display:inline-flex;align-items:center;justify-content:center;max-width:100%;',
		'border:1px solid var(--lanspeed-border-strong);border-radius:var(--lanspeed-radius-badge);',
		'background-color:var(--lanspeed-surface-muted)!important;color:var(--lanspeed-text)!important;',
		'text-shadow:none;line-height:1.25}',
	ROOT + ' .label.label-success{border-color:var(--lanspeed-normal-border)!important;',
		'background-color:var(--lanspeed-normal-soft)!important;color:var(--lanspeed-normal-text)!important}',
	ROOT + ' .label.label-warning{border-color:var(--lanspeed-warning-border)!important;',
		'background-color:var(--lanspeed-warning-soft)!important;color:var(--lanspeed-text)!important}',
	ROOT + ' .label.label-danger{border-color:var(--lanspeed-danger-border)!important;',
		'background-color:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-text)!important}',
	ROOT + ' .cbi-button.cbi-button-remove{border-color:var(--lanspeed-danger-border)!important;',
		'background-color:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-danger)!important}',

	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) :is(th,td){border-color:var(--lanspeed-border)}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) thead th{color:var(--lanspeed-text-muted)!important}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) tbody tr{transition:background-color var(--lanspeed-transition)}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) tbody tr:hover{background-color:var(--lanspeed-hover)}',
	ROOT + ' :is(.lanspeed-empty,.lanspeed-connection-empty,.lanspeed-diagnostic-alert-empty){',
		'border:1px dashed var(--lanspeed-border-strong);border-radius:var(--lanspeed-radius-control);',
		'background-color:var(--lanspeed-surface-muted);color:var(--lanspeed-text-muted)}',
	ROOT + ' :is(.alert-message.error,.lanspeed-connection-error,.lanspeed-diagnostics-error,',
		'.lanspeed-state-message[data-state="error"]){border-color:var(--lanspeed-danger-border)!important;',
		'background-color:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-danger)!important}',
	ROOT + ' :is(.lanspeed-sort-button,.lanspeed-connection-link):focus-visible{',
		'outline:2px solid var(--lanspeed-focus-color);outline-offset:3px}',
	'@media (prefers-reduced-motion:reduce){' + ROOT + ' *{scroll-behavior:auto!important;',
		'transition-duration:.01ms!important;animation-duration:.01ms!important;',
		'animation-iteration-count:1!important}}',
		'@media (forced-colors:active){' + ROOT + '>:is(.cbi-section,.lanspeed-config-subsection,.lanspeed-ifcfg),' + ROOT + ' .label,' +
		ROOT + ' :is(.lanspeed-empty,.lanspeed-connection-empty){forced-color-adjust:auto}}',
	'@media (max-width:700px){' + ROOT + '{width:100%;min-width:0;max-width:100%;overflow-x:hidden}',
		ROOT + '>:is(.cbi-section,.lanspeed-config-subsection,.lanspeed-ifcfg){min-width:0;max-width:100%}}'
].join('\n');

return baseclass.extend({
	CSS: BASE_CSS
});
