'use strict';
'require baseclass';

var ROOT = '.lanspeed-theme-bootstrap';

/* Bootstrap keeps LuCI's compact, bordered control and table grammar. */
var BOOTSTRAP_CSS = [
	ROOT + '{',
		'--lanspeed-page-bg:var(--background-color-low);',
		'--lanspeed-surface:var(--background-color-high);',
		'--lanspeed-surface-muted:var(--background-color-medium);',
		'--lanspeed-surface-sunken:var(--background-color-low);',
		'--lanspeed-surface-raised:var(--background-color-medium);',
		'--lanspeed-text:var(--text-color-high);--lanspeed-text-muted:var(--text-color-high);',
		'--lanspeed-text-subtle:var(--text-color-high);',
		'--lanspeed-border:var(--border-color-low);--lanspeed-border-strong:var(--border-color-high);',
		'--lanspeed-accent:var(--primary-color-high);--lanspeed-accent-safe:var(--primary-color-high);',
		'--lanspeed-accent-contrast:var(--on-primary-color,var(--background-color-high));',
		'--lanspeed-accent-soft:color-mix(in srgb,var(--primary-color-high) 12%,var(--background-color-high));',
		'--lanspeed-hover:color-mix(in srgb,var(--primary-color-high) 9%,var(--background-color-high));',
		'--lanspeed-control-bg:var(--background-color-high);',
		'--lanspeed-control-border:var(--border-color-high);',
		'--lanspeed-action-bg:var(--primary-color-high);',
		'--lanspeed-action-hover:var(--primary-color-medium,var(--primary-color-high));',
		'--lanspeed-action-text:var(--on-primary-color,var(--background-color-high));',
		'--lanspeed-action-hover-text:var(--on-primary-color,var(--background-color-high));',
		'--lanspeed-action-border:var(--primary-color-high);',
		'--lanspeed-normal:var(--success-color-high,var(--primary-color-high));',
		'--lanspeed-normal-soft:color-mix(in srgb,var(--success-color-high,var(--primary-color-high)) 12%,var(--background-color-high));',
		'--lanspeed-normal-text:color-mix(in srgb,var(--success-color-high,var(--primary-color-high)) 45%,var(--text-color-high));',
		'--lanspeed-normal-border:var(--success-color-high,var(--primary-color-high));',
		'--lanspeed-warning:color-mix(in srgb,var(--warn-color-high) 35%,var(--text-color-high));',
		'--lanspeed-warning-soft:color-mix(in srgb,var(--warn-color-high) 12%,var(--background-color-high));',
		'--lanspeed-warning-border:var(--warn-color-high);',
		'--lanspeed-danger:color-mix(in srgb,var(--error-color-high) 55%,var(--text-color-high));',
		'--lanspeed-danger-soft:color-mix(in srgb,var(--error-color-high) 12%,var(--background-color-high));',
		'--lanspeed-danger-border:var(--error-color-high);',
		'--lanspeed-info:var(--primary-color-high);',
		'--lanspeed-info-soft:color-mix(in srgb,var(--primary-color-high) 10%,var(--background-color-high));',
		'--lanspeed-info-border:var(--primary-color-high);',
		'--lanspeed-focus-color:var(--primary-color-high);',
		'--lanspeed-focus-ring:0 0 0 .16rem var(--primary-color-medium,var(--primary-color-high));',
		'--lanspeed-radius-section:.25rem;--lanspeed-radius-control:.2rem;',
		'--lanspeed-radius-input:.2rem;--lanspeed-radius-button:.2rem;',
		'--lanspeed-radius-compact:.12rem;--lanspeed-radius-badge:.2rem;',
		'--lanspeed-shadow-section:0 1px 3px var(--border-color-low);',
		'--lanspeed-shadow-raised:0 1px 2px var(--border-color-low);',
		'--lanspeed-disabled-opacity:var(--disabled-opacity,.45);',
		'--lanspeed-page-gap:.75rem;--lanspeed-section-x:1rem;--lanspeed-section-y:.75rem;',
		'--lanspeed-control-height:2.25rem;--lanspeed-transition:100ms ease;',
		'color:var(--lanspeed-text)}',
	ROOT + '[data-lanspeed-color-mode="dark"]{',
		'--lanspeed-action-hover:color-mix(in srgb,var(--primary-color-high) 92%,var(--text-color-high))}',

	ROOT + '>:is(.cbi-section,.lanspeed-config-subsection,.lanspeed-ifcfg){margin:0;padding:0;',
		'overflow:hidden;border:1px solid var(--lanspeed-border-strong);',
		'border-radius:var(--lanspeed-radius-section);background-color:var(--lanspeed-surface);',
		'box-shadow:var(--lanspeed-shadow-section);color:var(--lanspeed-text)}',
	ROOT + ' :is(.lanspeed-header,.lanspeed-config-subheader,.lanspeed-diagnostics-header,.lanspeed-details>summary){',
		'border-bottom-color:var(--lanspeed-border-strong);background-color:var(--lanspeed-surface-raised)}',
	ROOT + ' :is(.meta,.sum,.hint,.muted,.lanspeed-hint,.lanspeed-diagnostics-meta,',
		'.lanspeed-diagnostics-privacy,.lanspeed-diagnostic-description,.lanspeed-diagnostic-meta,',
		'.lanspeed-diagnostic-panel-description,.lanspeed-diagnostic-panel-meta,',
		'.lanspeed-diagnostic-fact-label,.lanspeed-diagnostic-stage-meta,',
		'.lanspeed-connection-breadcrumb-current,.lanspeed-connection-client-kicker,',
		'.lanspeed-connection-meta-heading-label,.lanspeed-connection-meta-label,',
		'.lanspeed-connection-summary-label,.lanspeed-connection-footer){',
		'color:var(--lanspeed-text-muted);opacity:.82}',

	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea){min-height:var(--lanspeed-control-height);',
		'border-color:var(--lanspeed-control-border)!important;border-radius:var(--lanspeed-radius-input)!important;',
		'background-color:var(--lanspeed-control-bg)!important;color:var(--lanspeed-text)!important;',
		'box-shadow:inset 0 1px 1px var(--lanspeed-border);',
		'transition:border-color var(--lanspeed-transition),box-shadow var(--lanspeed-transition),',
		'background-color var(--lanspeed-transition)}',
	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea)::placeholder{color:var(--lanspeed-text-subtle);opacity:.74}',
	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea):hover:not(:disabled){border-color:var(--lanspeed-accent-safe)!important}',
	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea):focus-visible{outline:0!important;',
		'border-color:var(--lanspeed-focus-color)!important;box-shadow:var(--lanspeed-focus-ring)!important}',
	ROOT + ' :is(.cbi-input-invalid,[aria-invalid="true"]){border-color:var(--lanspeed-danger-border)!important;',
		'box-shadow:0 0 0 1px var(--lanspeed-danger-border)!important}',
	ROOT + ' :is(input[type="checkbox"],input[type="radio"]){',
		'accent-color:var(--lanspeed-accent-safe);color:var(--lanspeed-text)!important}',
	ROOT + ' :is(input[type="checkbox"],input[type="radio"]):focus-visible{',
		'outline:2px solid var(--lanspeed-focus-color);outline-offset:3px}',

	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button){border-color:var(--lanspeed-control-border)!important;',
		'border-radius:var(--lanspeed-radius-button);background-color:var(--lanspeed-surface-muted)!important;',
		'color:var(--lanspeed-text)!important;box-shadow:var(--lanspeed-shadow-raised)!important;',
		'transition:border-color var(--lanspeed-transition),box-shadow var(--lanspeed-transition),',
		'background-color var(--lanspeed-transition),color var(--lanspeed-transition)}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):hover:not(:disabled){',
		'border-color:var(--lanspeed-accent-safe)!important;background-color:var(--lanspeed-hover)!important}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):active:not(:disabled){',
		'background-color:var(--lanspeed-accent-soft)!important;box-shadow:inset 0 1px 2px var(--lanspeed-border-strong)!important}',
	ROOT + ' .cbi-button.cbi-button-action{border-color:var(--lanspeed-action-border)!important;',
		'background-color:var(--lanspeed-action-bg)!important;background-image:none!important;',
		'color:var(--lanspeed-action-text)!important}',
	ROOT + ' .cbi-button.cbi-button-action:hover:not(:disabled){border-color:var(--lanspeed-action-border)!important;',
		'background-color:var(--lanspeed-action-hover)!important;background-image:none!important;',
		'color:var(--lanspeed-action-hover-text)!important}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):focus-visible{outline:0!important;',
		'border-color:var(--lanspeed-focus-color)!important;box-shadow:var(--lanspeed-focus-ring)!important}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):disabled,' + ROOT + ' [aria-disabled="true"]{',
		'opacity:var(--lanspeed-disabled-opacity)}',
	ROOT + ' :is(.lanspeed-ifcfg-seg>button.active,.lanspeed-connection-protocol[aria-pressed="true"]){',
		'border-color:var(--lanspeed-accent-safe)!important;background-color:var(--lanspeed-accent-soft)!important;',
		'color:var(--lanspeed-text)!important;box-shadow:inset 0 0 0 1px var(--lanspeed-accent-safe)!important}',

	ROOT + ' .label{display:inline-flex;align-items:center;justify-content:center;max-width:100%;',
		'padding:.16rem .45rem;border:1px solid var(--lanspeed-border-strong)!important;',
		'border-radius:var(--lanspeed-radius-badge);background-color:var(--lanspeed-surface-muted)!important;',
		'color:var(--lanspeed-text)!important;font-size:.72rem;font-weight:700;line-height:1.25;text-shadow:none}',
	ROOT + ' .label.label-success{border-color:var(--lanspeed-normal-border)!important;',
		'background-color:var(--lanspeed-normal-soft)!important;color:var(--lanspeed-normal-text)!important}',
	ROOT + ' .label.label-warning{border-color:var(--lanspeed-warning-border)!important;',
		'background-color:var(--lanspeed-warning-soft)!important;color:var(--lanspeed-warning)!important}',
	ROOT + ' .label.label-danger{border-color:var(--lanspeed-danger-border)!important;',
		'background-color:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-danger)!important}',
	ROOT + ' .cbi-button.cbi-button-remove{border-color:var(--lanspeed-danger-border)!important;',
		'background-color:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-danger)!important}',

	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) :is(th,td){border-color:var(--lanspeed-border)}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) thead th{color:var(--lanspeed-text-muted);',
		'background-color:var(--lanspeed-surface-muted)}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) tbody tr:nth-child(even){background-color:var(--lanspeed-surface-sunken)}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) tbody tr:hover{background-color:var(--lanspeed-hover)}',
	ROOT + ' :is(.lanspeed-empty,.lanspeed-connection-empty,.lanspeed-diagnostic-alert-empty){',
		'border:1px dashed var(--lanspeed-border-strong);border-radius:var(--lanspeed-radius-control);',
		'background-color:var(--lanspeed-surface-muted);color:var(--lanspeed-text-muted)}',
	ROOT + ' :is(.alert-message.error,.lanspeed-connection-error,.lanspeed-diagnostics-error,',
		'.lanspeed-state-message[data-state="error"],.lanspeed-state-message[data-state="invalid"]){',
		'border-color:var(--lanspeed-danger-border)!important;background-color:var(--lanspeed-danger-soft)!important;',
		'color:var(--lanspeed-danger)!important}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="loading"]{color:var(--lanspeed-info)}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="ready"]{color:var(--lanspeed-normal-text)}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="stale"],',
		ROOT + ' :is(.status,.lanspeed-state-message)[data-state="degraded"]{color:var(--lanspeed-warning)}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="error"],',
		ROOT + ' :is(.status,.lanspeed-state-message)[data-state="invalid"]{color:var(--lanspeed-danger)}',
	ROOT + ' :is(.lanspeed-sort-button,.lanspeed-connection-link,summary):focus-visible{',
		'outline:2px solid var(--lanspeed-focus-color);outline-offset:3px}'
].join('\n');

return baseclass.extend({
	CSS: BOOTSTRAP_CSS
});
