'use strict';
'require baseclass';

var ROOT = '.lanspeed-theme-shadcn';

/* shadcn exposes a flat oklch token set (--bg/--surface/--brand/--border ...)
 * plus a single --radius-base knob and a --shadow-sm elevation.  This layer
 * maps those native tokens onto the LAN Speed product contract. */
var SHADCN_CSS = [
	ROOT + '{',
		'--lanspeed-page-bg:var(--bg);--lanspeed-surface:var(--surface);',
		'--lanspeed-surface-muted:var(--label-surface);--lanspeed-surface-sunken:var(--label-surface);',
		'--lanspeed-surface-raised:transparent;',
		'--lanspeed-text:var(--text);',
		'--lanspeed-text-muted:color-mix(in srgb,var(--muted-foreground) 65%,var(--text));',
		'--lanspeed-text-subtle:color-mix(in srgb,var(--muted-foreground) 65%,var(--text));',
		'--lanspeed-border:var(--border);--lanspeed-border-strong:var(--border);',
		'--lanspeed-accent:var(--brand);--lanspeed-accent-safe:var(--brand);',
		'--lanspeed-accent-contrast:var(--on-brand);',
		'--lanspeed-accent-soft:var(--primary-a10);--lanspeed-hover:var(--primary-a5);',
		'--lanspeed-control-bg:var(--surface);--lanspeed-control-border:var(--input);',
		'--lanspeed-action-bg:var(--primary);--lanspeed-action-hover:var(--primary);',
		'--lanspeed-action-text:var(--primary-foreground);',
		'--lanspeed-action-hover-text:var(--primary-foreground);',
		'--lanspeed-action-border:var(--primary);',
		'--lanspeed-filled-action-safe:var(--primary);',
		'--lanspeed-filled-action-text-safe:var(--primary-foreground);',
		'--lanspeed-danger-safe:var(--danger);',
		'--lanspeed-normal:var(--success);',
		'--lanspeed-normal-soft:var(--success-a10);',
		'--lanspeed-normal-text:color-mix(in srgb,var(--success) 60%,var(--text));',
		'--lanspeed-normal-border:var(--success);',
		'--lanspeed-warning:color-mix(in srgb,var(--warning) 56%,var(--text));',
		'--lanspeed-warning-soft:var(--warning-a10);',
		'--lanspeed-warning-border:var(--warning);',
		'--lanspeed-danger:color-mix(in srgb,var(--danger) 80%,var(--text));',
		'--lanspeed-danger-soft:var(--destructive-a10);',
		'--lanspeed-danger-border:var(--danger);',
		'--lanspeed-info:var(--info);--lanspeed-info-soft:var(--info-a10);',
		'--lanspeed-info-border:var(--info);',
		'--lanspeed-focus-color:var(--ring);--lanspeed-focus-ring:0 0 0 .18rem var(--focus-ring);',
		'--lanspeed-radius-section:var(--radius-xl,var(--radius-base,.5rem));',
		'--lanspeed-radius-control:var(--radius-md,calc(var(--radius-base,.5rem)*.75));',
		'--lanspeed-radius-input:var(--radius-md,calc(var(--radius-base,.5rem)*.75));',
		'--lanspeed-radius-button:var(--radius-md,calc(var(--radius-base,.5rem)*.75));',
		'--lanspeed-radius-compact:var(--radius,calc(var(--radius-base,.5rem)*.5));',
		'--lanspeed-radius-badge:999px;',
		'--lanspeed-shadow-section:var(--shadow-sm);--lanspeed-shadow-raised:none;',
		'--lanspeed-disabled-opacity:.5;',
		'--lanspeed-page-gap:1rem;--lanspeed-section-x:1.15rem;',
		'--lanspeed-section-y:.95rem;--lanspeed-control-height:2.25rem;',
		'--lanspeed-transition:.15s;color:var(--lanspeed-text)}',

	ROOT + '>:is(.cbi-section,.lanspeed-config-subsection,.lanspeed-ifcfg){margin:0;padding:0;',
		'overflow:hidden;border:1px solid var(--panel-border,var(--lanspeed-border));',
		'border-radius:var(--lanspeed-radius-section);background-color:var(--lanspeed-surface);',
		'box-shadow:var(--lanspeed-shadow-section);color:var(--lanspeed-text)}',
	ROOT + ' :is(.lanspeed-header,.lanspeed-config-subheader,.lanspeed-diagnostics-header,.lanspeed-details>summary){',
		'border-bottom-color:var(--lanspeed-border);background-color:transparent}',
	ROOT + ' :is(.meta,.sum,.hint,.muted,.lanspeed-hint,.lanspeed-diagnostics-meta,',
		'.lanspeed-diagnostics-privacy,.lanspeed-diagnostic-description,.lanspeed-diagnostic-meta,',
		'.lanspeed-diagnostic-panel-description,.lanspeed-diagnostic-panel-meta,',
		'.lanspeed-diagnostic-fact-label,.lanspeed-diagnostic-stage-meta,',
		'.lanspeed-connection-breadcrumb-current,.lanspeed-connection-client-kicker,',
		'.lanspeed-connection-meta-heading-label,.lanspeed-connection-meta-label,',
		'.lanspeed-connection-summary-label,.lanspeed-connection-footer){',
		'color:var(--lanspeed-text-muted);opacity:1}',

	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea){min-height:var(--lanspeed-control-height);',
		'border-color:var(--lanspeed-control-border)!important;border-radius:var(--lanspeed-radius-input)!important;',
		'background-color:var(--lanspeed-control-bg)!important;color:var(--lanspeed-text)!important;',
		'transition:border-color var(--lanspeed-transition),box-shadow var(--lanspeed-transition),',
		'background-color var(--lanspeed-transition)}',
	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea)::placeholder{color:var(--lanspeed-text-muted);opacity:1}',
	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea):hover:not(:disabled){border-color:var(--lanspeed-accent-safe)!important}',
	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea):focus-visible{outline:0!important;',
		'border-color:var(--lanspeed-focus-color)!important;box-shadow:var(--lanspeed-focus-ring)!important}',
	ROOT + ' :is(.cbi-input-invalid,[aria-invalid="true"]){border-color:var(--lanspeed-danger-border)!important;',
		'box-shadow:0 0 0 1px var(--lanspeed-danger-border)!important}',
	ROOT + ' :is(input[type="checkbox"],input[type="radio"]){',
		'accent-color:var(--lanspeed-accent-safe);color:var(--lanspeed-text)!important}',
	ROOT + ' :is(input[type="checkbox"],input[type="radio"]):focus-visible{',
		'outline:2px solid var(--lanspeed-focus-color);outline-offset:3px}',

	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button){border-color:var(--lanspeed-control-border)!important;',
		'border-radius:var(--lanspeed-radius-button);background-color:var(--secondary)!important;',
		'color:var(--secondary-foreground,var(--lanspeed-text))!important;box-shadow:var(--lanspeed-shadow-raised)!important;',
		'transition:border-color var(--lanspeed-transition),box-shadow var(--lanspeed-transition),',
		'background-color var(--lanspeed-transition),color var(--lanspeed-transition)}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):hover:not(:disabled){',
		'border-color:var(--lanspeed-control-border)!important;',
		'background-color:var(--secondary)!important;color:var(--secondary-foreground,var(--lanspeed-text))!important}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):active:not(:disabled){',
		'background-color:var(--lanspeed-accent-soft)!important}',
	ROOT + ' .cbi-button.cbi-button-action{border-color:var(--lanspeed-action-border)!important;',
		'background-color:var(--lanspeed-action-bg)!important;background-image:none!important;',
		'color:var(--lanspeed-action-text)!important}',
	ROOT + ' .cbi-button.cbi-button-action:hover:not(:disabled){border-color:var(--lanspeed-action-border)!important;',
		'background-color:var(--lanspeed-action-bg)!important;background-image:none!important;',
		'color:var(--lanspeed-action-text)!important}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):is(:focus,:focus-visible):not(:disabled):not([aria-disabled="true"]){outline:0!important;',
		'border-color:var(--lanspeed-focus-color)!important;box-shadow:var(--lanspeed-focus-ring)!important}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):disabled,' + ROOT + ' [aria-disabled="true"]{',
		'opacity:var(--lanspeed-disabled-opacity)}',
	ROOT + ' :is(.lanspeed-ifcfg-seg>button.active,.lanspeed-connection-protocol[aria-pressed="true"]){',
		'border-color:var(--lanspeed-accent-safe)!important;background-color:var(--lanspeed-accent-soft)!important;',
		'color:var(--lanspeed-text)!important;box-shadow:inset 0 0 0 1px var(--lanspeed-accent-safe)!important}',
	ROOT + ' .lanspeed-connection-protocol[aria-pressed="true"]:hover:not(:disabled){',
		'border-color:var(--lanspeed-accent-safe)!important;background-color:var(--lanspeed-accent-soft)!important;',
		'color:var(--lanspeed-text)!important;box-shadow:inset 0 0 0 1px var(--lanspeed-accent-safe)!important}',

	ROOT + ' .label{display:inline-flex;align-items:center;justify-content:center;max-width:100%;',
		'padding:.16rem .55rem;border:1px solid var(--lanspeed-border-strong)!important;',
		'border-radius:var(--lanspeed-radius-badge);background-color:var(--lanspeed-surface-muted)!important;',
		'color:var(--lanspeed-text)!important;font-size:.72rem;font-weight:600;line-height:1.25;text-shadow:none}',
	ROOT + ' .label.label-success{border-color:var(--lanspeed-normal-border)!important;',
		'background-color:var(--lanspeed-normal-soft)!important;color:var(--lanspeed-normal-text)!important}',
	ROOT + ' .label.label-warning{border-color:var(--lanspeed-warning-border)!important;',
		'background-color:var(--lanspeed-warning-soft)!important;color:var(--lanspeed-warning)!important}',
	ROOT + ' .label.label-danger{border-color:var(--lanspeed-danger-border)!important;',
		'background-color:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-danger)!important}',
	ROOT + ' .cbi-button.cbi-button-remove{border-color:var(--lanspeed-danger-border)!important;',
		'background-color:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-danger)!important}',

	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table,.lanspeed-diagnostics-tc-conflict-table,.lanspeed-diagnostics-tc-table) :is(th,td){border-color:var(--lanspeed-border)}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table,.lanspeed-diagnostics-tc-conflict-table,.lanspeed-diagnostics-tc-table) thead th{',
		'color:var(--lanspeed-text);background-color:var(--label-surface,var(--lanspeed-surface-muted))}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table,.lanspeed-diagnostics-tc-conflict-table,.lanspeed-diagnostics-tc-table) tbody tr:hover{',
		'background-color:transparent!important;background-image:none!important}',
	ROOT + ' :is(code,kbd,samp){color:var(--lanspeed-text-muted);',
		'background-color:var(--lanspeed-surface-muted);border-radius:var(--lanspeed-radius-compact)}',
	ROOT + ' :is(.lanspeed-empty,.lanspeed-connection-empty,.lanspeed-diagnostic-alert-empty){',
		'border:1px dashed var(--lanspeed-border-strong);border-radius:var(--lanspeed-radius-control);',
		'background-color:var(--lanspeed-surface-muted);color:var(--lanspeed-text-muted)}',
	ROOT + ' :is(.alert-message.error,.lanspeed-connection-error,.lanspeed-diagnostics-error,',
		'.lanspeed-state-message[data-state="error"],.lanspeed-state-message[data-state="invalid"]){',
		'border-color:var(--lanspeed-danger-border)!important;background-color:var(--lanspeed-danger-soft)!important;',
		'color:var(--lanspeed-danger)!important}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="loading"]{color:var(--lanspeed-info)}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="ready"]{color:var(--lanspeed-normal-text)}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="stale"],',
		ROOT + ' :is(.status,.lanspeed-state-message)[data-state="degraded"]{color:var(--lanspeed-warning)}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="error"],',
		ROOT + ' :is(.status,.lanspeed-state-message)[data-state="invalid"]{color:var(--lanspeed-danger)}',
	ROOT + ' :is(.lanspeed-sort-button,.lanspeed-connection-link,summary):focus-visible{',
		'outline:2px solid var(--lanspeed-focus-color);outline-offset:3px}'
].join('\n');

return baseclass.extend({
	CSS: SHADCN_CSS
});
