'use strict';
'require baseclass';

var ROOT = '.lanspeed-theme-argon';

var ARGON_CSS = [
	ROOT + '{',
		'--lanspeed-page-bg:transparent;--lanspeed-surface:transparent;',
		'--lanspeed-surface-muted:transparent;--lanspeed-surface-sunken:transparent;',
		'--lanspeed-surface-raised:transparent;',
		'--lanspeed-text:currentColor;--lanspeed-text-muted:currentColor;--lanspeed-text-subtle:currentColor;',
		'--lanspeed-border:var(--gray,currentColor);--lanspeed-border-strong:var(--gray,currentColor);',
		'--lanspeed-accent:var(--primary,var(--default,currentColor));--lanspeed-accent-contrast:currentColor;',
		'--lanspeed-accent-safe:var(--lanspeed-accent);--lanspeed-accent-soft:transparent;',
		'--lanspeed-hover:transparent;--lanspeed-control-bg:transparent;',
		'--lanspeed-control-border:var(--gray,currentColor);',
		'--lanspeed-action-bg:var(--lanspeed-accent-soft);--lanspeed-action-hover:var(--lanspeed-accent-soft);',
		'--lanspeed-action-text:var(--lanspeed-text);--lanspeed-action-hover-text:var(--lanspeed-text);',
		'--lanspeed-action-border:var(--lanspeed-accent-safe);',
		'--lanspeed-normal:var(--lanspeed-accent-safe);--lanspeed-normal-soft:var(--lanspeed-accent-soft);',
		'--lanspeed-normal-text:var(--lanspeed-normal-text-safe,var(--lanspeed-link-safe,var(--lanspeed-text)));',
		'--lanspeed-normal-border:var(--lanspeed-accent-safe);',
		'--lanspeed-warning:var(--lanspeed-warning-safe,var(--warning,var(--lanspeed-accent-safe)));',
		'--lanspeed-warning-soft:transparent;--lanspeed-warning-border:var(--lanspeed-warning);',
		'--lanspeed-danger:var(--lanspeed-danger-safe,var(--danger,var(--lanspeed-accent-safe)));',
		'--lanspeed-danger-soft:transparent;--lanspeed-danger-border:var(--lanspeed-danger);',
		'--lanspeed-info:var(--lanspeed-info-safe,var(--info,var(--lanspeed-accent-safe)));',
		'--lanspeed-info-soft:transparent;--lanspeed-info-border:var(--lanspeed-info);',
		'--lanspeed-focus-color:var(--lanspeed-focus-color-safe,var(--lanspeed-accent-safe));',
		'--lanspeed-focus-ring:0 0 0 .16rem var(--lanspeed-focus-color);',
		'--lanspeed-radius-section:.35rem;--lanspeed-radius-control:.25rem;',
		'--lanspeed-radius-input:.25rem;--lanspeed-radius-button:.25rem;',
		'--lanspeed-radius-compact:.18rem;--lanspeed-radius-badge:.25rem;',
		'--lanspeed-shadow-section:none;--lanspeed-shadow-raised:none;',
		'--lanspeed-disabled-opacity:var(--disabled-opacity,.45);',
		'--lanspeed-page-gap:1rem;--lanspeed-section-x:1.25rem;--lanspeed-section-y:1rem;',
		'--lanspeed-control-height:2.5rem;--lanspeed-transition:120ms ease;',
		'--lanspeed-native-row-stripe:var(--lanspeed-surface-muted);color:var(--lanspeed-text)}',
	'@supports (color:color-mix(in srgb,currentColor 5%,transparent)){' + ROOT + '{',
		'--lanspeed-surface:color-mix(in srgb,currentColor 2%,transparent);',
		'--lanspeed-surface-muted:color-mix(in srgb,currentColor 5%,transparent);',
		'--lanspeed-surface-sunken:color-mix(in srgb,currentColor 5%,transparent);',
		'--lanspeed-surface-raised:color-mix(in srgb,currentColor 3%,transparent);',
		'--lanspeed-border:color-mix(in srgb,var(--gray,currentColor) 28%,transparent);',
		'--lanspeed-border-strong:color-mix(in srgb,var(--gray,currentColor) 46%,transparent);',
		'--lanspeed-accent-soft:color-mix(in srgb,var(--lanspeed-accent) 12%,transparent);',
		'--lanspeed-hover:color-mix(in srgb,var(--lanspeed-accent) 9%,transparent);',
		'--lanspeed-control-bg:color-mix(in srgb,currentColor 2%,transparent);',
		'--lanspeed-control-border:color-mix(in srgb,var(--gray,currentColor) 42%,transparent);',
		'--lanspeed-warning-soft:color-mix(in srgb,var(--warning,var(--lanspeed-accent)) 10%,transparent);',
		'--lanspeed-danger-soft:color-mix(in srgb,var(--danger,var(--lanspeed-accent)) 10%,transparent);',
		'--lanspeed-info-soft:color-mix(in srgb,var(--info,var(--lanspeed-accent)) 9%,transparent)}}',
	'@media (prefers-color-scheme:dark){' + ROOT + '{',
		'--lanspeed-accent:var(--dark-primary,var(--primary,var(--default,currentColor)))}}',
	'[data-lanspeed-color-mode="light"]' + ROOT + '{',
		'--lanspeed-accent:var(--primary,var(--default,currentColor))}',
	'[data-lanspeed-color-mode="dark"]' + ROOT + '{',
		'--lanspeed-accent:var(--dark-primary,var(--primary,var(--default,currentColor)))}',
	'.cbi-page-actions[data-lanspeed-theme="argon"][data-lanspeed-color-mode] .cbi-button.cbi-button-save{',
		'border-color:var(--lanspeed-footer-action,var(--primary,var(--default,currentColor)))!important;',
		'background-color:var(--lanspeed-footer-action,var(--primary,var(--default,currentColor)))!important;',
		'background-image:none!important;',
		'color:var(--lanspeed-footer-action-text,currentColor)!important}',
	'.cbi-page-actions[data-lanspeed-theme="argon"][data-lanspeed-color-mode] .cbi-button.cbi-button-save:hover:not(:disabled){',
		'filter:none}',
	'.cbi-page-actions[data-lanspeed-theme="argon"][data-lanspeed-color-mode] .cbi-button.cbi-button-save:focus-visible{',
		'outline:2px solid var(--lanspeed-footer-action,var(--primary,var(--default,currentColor)))!important;',
		'outline-offset:2px}',
	'.cbi-page-actions[data-lanspeed-theme="argon"][data-lanspeed-color-mode] .cbi-button.cbi-button-reset{',
		'border-color:var(--lanspeed-footer-danger,var(--danger,currentColor))!important;',
		'background-color:transparent!important;background-image:none!important;',
		'color:var(--lanspeed-footer-danger,var(--danger,currentColor))!important}',
	'@supports (color:color-mix(in srgb,currentColor 5%,transparent)){',
	'.cbi-page-actions[data-lanspeed-theme="argon"][data-lanspeed-color-mode] .cbi-button.cbi-button-reset{',
		'background-color:color-mix(in srgb,var(--lanspeed-footer-danger,var(--danger,currentColor)) 10%,transparent)!important}',
	'.cbi-page-actions[data-lanspeed-theme="argon"][data-lanspeed-color-mode] .cbi-button.cbi-button-reset:hover:not(:disabled){',
		'background-color:color-mix(in srgb,var(--lanspeed-footer-danger,var(--danger,currentColor)) 10%,transparent)!important}}',
	'.cbi-page-actions[data-lanspeed-theme="argon"][data-lanspeed-color-mode] .cbi-button.cbi-button-reset:focus-visible{',
		'outline:2px solid var(--lanspeed-footer-danger,var(--danger,currentColor))!important;',
		'outline-offset:2px}',
	'.cbi-page-actions[data-lanspeed-theme="argon"][data-lanspeed-color-mode] ',
		':is(.cbi-button-save,.cbi-button-apply,.cbi-button-reset):hover:not(:disabled):not(:focus-visible){',
		'box-shadow:none!important}',

	ROOT + '>:is(.cbi-section,.lanspeed-config-subsection,.lanspeed-ifcfg){margin:0;padding:0;',
		'overflow:hidden;border:1px solid var(--lanspeed-border);',
		'border-left:.2rem solid var(--lanspeed-accent-safe);border-radius:var(--lanspeed-radius-section);',
		'background-color:var(--lanspeed-surface);box-shadow:none;color:var(--lanspeed-text)}',
	ROOT + ' :is(.lanspeed-header,.lanspeed-config-subheader,.lanspeed-diagnostics-header,.lanspeed-details>summary){',
		'border-bottom-color:var(--lanspeed-border);background-color:var(--lanspeed-surface-raised)}',
	ROOT + ' :is(.meta,.sum,.hint,.muted,.lanspeed-hint,.lanspeed-diagnostics-meta,',
		'.lanspeed-diagnostics-privacy,.lanspeed-diagnostic-description,.lanspeed-diagnostic-meta,',
		'.lanspeed-diagnostic-panel-description,.lanspeed-diagnostic-panel-meta,',
		'.lanspeed-diagnostic-fact-label,.lanspeed-diagnostic-stage-meta,',
		'.lanspeed-connection-breadcrumb-current,.lanspeed-connection-client-kicker,',
		'.lanspeed-connection-meta-heading-label,.lanspeed-connection-meta-label,',
		'.lanspeed-connection-summary-label,.lanspeed-connection-footer){',
		'color:var(--lanspeed-text-muted);opacity:.82}',

	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea){min-height:var(--lanspeed-control-height);',
		'border-color:var(--lanspeed-control-border)!important;border-radius:var(--lanspeed-radius-input)!important;',
		'background-color:var(--lanspeed-control-bg)!important;color:var(--lanspeed-text)!important;',
		'box-shadow:none!important;transition:border-color var(--lanspeed-transition),',
		'box-shadow var(--lanspeed-transition),background-color var(--lanspeed-transition)}',
	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea):hover:not(:disabled){border-color:var(--lanspeed-accent-safe)!important}',
	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea):is(:focus,:focus-visible){outline:0!important;',
		'border-color:var(--lanspeed-focus-color)!important;box-shadow:var(--lanspeed-focus-ring)!important}',
	ROOT + ' :is(input[type="checkbox"],input[type="radio"]){',
		'accent-color:var(--lanspeed-switch-accent-safe,var(--lanspeed-accent-safe))!important;',
		'color:var(--lanspeed-text)!important}',
	ROOT + ' input[type="checkbox"]{border-color:var(--lanspeed-switch-accent-safe,var(--lanspeed-accent-safe))!important}',
	ROOT + ' input[type="checkbox"]:checked{',
		'border-color:var(--lanspeed-switch-accent-safe,var(--lanspeed-accent-safe))!important;',
		'background-color:var(--lanspeed-switch-accent-safe,var(--lanspeed-accent-safe))!important}',
	ROOT + ' :is(input[type="checkbox"],input[type="radio"]):focus-visible{',
		'outline:2px solid var(--lanspeed-focus-color);outline-offset:3px}',
	ROOT + ' input::placeholder{color:var(--lanspeed-text-muted)!important;opacity:.72}',

	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button){border-color:var(--lanspeed-control-border)!important;',
		'border-radius:var(--lanspeed-radius-button);background-color:var(--lanspeed-surface-muted)!important;',
		'color:var(--lanspeed-text)!important;box-shadow:none!important;',
		'transition:border-color var(--lanspeed-transition),background-color var(--lanspeed-transition),',
		'color var(--lanspeed-transition)}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):hover:not(:disabled){',
		'border-color:var(--lanspeed-control-border)!important;background-color:var(--lanspeed-surface-muted)!important}',
	ROOT + ' .cbi-button.cbi-button-action{border-color:var(--lanspeed-action-border)!important;',
		'background-color:var(--lanspeed-action-bg)!important;color:var(--lanspeed-action-text)!important;',
		'box-shadow:inset .18rem 0 0 var(--lanspeed-accent-safe)!important}',
	ROOT + ' .cbi-button.cbi-button-action:hover:not(:disabled){border-color:var(--lanspeed-action-border)!important;',
		'background-color:var(--lanspeed-action-bg)!important;color:var(--lanspeed-action-text)!important}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):disabled,' + ROOT + ' [aria-disabled="true"]{',
		'opacity:var(--lanspeed-disabled-opacity)}',
	ROOT + ' :is(.lanspeed-ifcfg-seg>button.active,.lanspeed-connection-protocol[aria-pressed="true"]){',
		'border-color:var(--lanspeed-accent-safe)!important;background-color:var(--lanspeed-accent-soft)!important;',
		'color:var(--lanspeed-text)!important;box-shadow:inset 0 0 0 1px var(--lanspeed-accent-safe)!important}',
	ROOT + ' .lanspeed-connection-protocol[aria-pressed="true"]:hover:not(:disabled){',
		'border-color:var(--lanspeed-accent-safe)!important;background-color:var(--lanspeed-accent-soft)!important;',
		'color:var(--lanspeed-text)!important;box-shadow:inset 0 0 0 1px var(--lanspeed-accent-safe)!important}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):is(:focus,:focus-visible){outline:0!important;',
		'border-color:var(--lanspeed-focus-color)!important;box-shadow:var(--lanspeed-focus-ring)!important}',

	ROOT + ' .label{display:inline-flex;align-items:center;justify-content:center;max-width:100%;',
		'border:1px solid var(--lanspeed-border-strong)!important;border-radius:var(--lanspeed-radius-badge);',
		'background-color:var(--lanspeed-surface-muted)!important;color:var(--lanspeed-text)!important;',
		'text-shadow:none;line-height:1.25}',
	ROOT + ' .label.label-success{border-color:var(--lanspeed-normal-border)!important;',
		'background-color:var(--lanspeed-normal-soft)!important;color:var(--lanspeed-normal-text)!important}',
	ROOT + ' .label.label-warning{border-color:var(--lanspeed-warning-border)!important;',
		'background-color:var(--lanspeed-warning-soft)!important;color:var(--lanspeed-warning)!important}',
	ROOT + ' .label.label-danger{border-color:var(--lanspeed-danger-border)!important;',
		'background-color:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-danger)!important}',
	ROOT + ' .cbi-button.cbi-button-remove{border-color:var(--lanspeed-danger-border)!important;',
		'background-color:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-danger)!important}',

	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) :is(th,td){border-color:var(--lanspeed-border)}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) thead th{color:var(--lanspeed-text-muted)}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) tbody tr:nth-child(odd):hover{',
		'background-color:transparent!important;background-image:none!important}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) tbody tr:nth-child(even),',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) tbody tr:nth-child(even):hover{',
		'background-color:var(--lanspeed-native-row-stripe)!important;background-image:none!important}',
	ROOT + ' :is(.lanspeed-empty,.lanspeed-connection-empty,.lanspeed-diagnostic-alert-empty){',
		'border:1px dashed var(--lanspeed-border-strong);border-radius:var(--lanspeed-radius-control);',
		'background-color:var(--lanspeed-surface-muted);color:var(--lanspeed-text-muted)}',
	ROOT + ' :is(.alert-message.error,.lanspeed-connection-error,.lanspeed-diagnostics-error,',
		'.lanspeed-state-message[data-state="error"]){border-color:var(--lanspeed-danger-border)!important;',
		'background-color:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-danger)!important}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="loading"]{color:var(--lanspeed-info)}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="ready"]{color:var(--lanspeed-normal-text)}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="error"]{color:var(--lanspeed-danger)}',
	ROOT + ' .lanspeed-connection-link:link,' + ROOT + ' .lanspeed-connection-link:visited,',
	ROOT + ' .lanspeed-connection-link:active,' + ROOT + ' .lanspeed-connection-link:hover{',
		'color:var(--lanspeed-link-safe,var(--lanspeed-accent-safe))!important;text-decoration:none!important}',
	ROOT + ' :is(.lanspeed-sort-button,.lanspeed-connection-link):is(:focus,:focus-visible){',
		'outline:2px solid var(--lanspeed-focus-color);outline-offset:3px}'
].join('\n');

return baseclass.extend({
	CSS: ARGON_CSS
});
