'use strict';
'require baseclass';

var ROOT = '.lanspeed-theme-aurora';

var AURORA_CSS = [
	ROOT + '{',
		'--lanspeed-page-bg:var(--bg);--lanspeed-surface:var(--surface);',
		'--lanspeed-surface-muted:var(--surface-sunken);--lanspeed-surface-sunken:var(--surface-sunken);',
		'--lanspeed-surface-raised:var(--surface-overlay);',
		'--lanspeed-text:var(--text);--lanspeed-text-muted:var(--text-muted);',
		'--lanspeed-text-subtle:var(--text-subtle);',
		'--lanspeed-border:var(--hairline);--lanspeed-border-strong:var(--hairline);',
		'--lanspeed-accent:var(--brand);--lanspeed-accent-safe:var(--brand);',
		'--lanspeed-accent-contrast:var(--on-brand);--lanspeed-accent-soft:var(--brand-subtle);',
		'--lanspeed-hover:var(--hover-faint);--lanspeed-control-bg:var(--control-bg);',
		'--lanspeed-control-border:var(--hairline);',
		'--lanspeed-action-bg:var(--brand);--lanspeed-action-hover:var(--brand-hover,var(--brand));',
		'--lanspeed-action-text:var(--lanspeed-action-text-safe,var(--on-brand));',
		'--lanspeed-action-hover-text:var(--lanspeed-action-hover-text-safe,var(--lanspeed-action-text));',
		'--lanspeed-action-border:var(--lanspeed-accent-safe);',
		'--lanspeed-normal:var(--lanspeed-accent-safe);--lanspeed-normal-soft:var(--brand-subtle);',
		'--lanspeed-normal-text:var(--lanspeed-normal-text-safe,var(--brand));',
		'--lanspeed-normal-border:var(--lanspeed-accent-safe);',
		'--lanspeed-warning:var(--lanspeed-warning-safe,var(--warning));',
		'--lanspeed-warning-soft:var(--warning-surface);--lanspeed-warning-border:var(--lanspeed-warning);',
		'--lanspeed-danger:var(--lanspeed-danger-safe,var(--danger));',
		'--lanspeed-danger-soft:var(--danger-surface);--lanspeed-danger-border:var(--lanspeed-danger);',
		'--lanspeed-info:var(--lanspeed-info-safe,var(--info));',
		'--lanspeed-info-soft:var(--info-surface);--lanspeed-info-border:var(--lanspeed-info);',
		'--lanspeed-focus-color:var(--lanspeed-focus-color-safe,var(--focus-ring));',
		'--lanspeed-focus-ring:0 0 0 .18rem var(--lanspeed-focus-color);',
		'--lanspeed-radius-section:calc(var(--radius-base,.5rem)*2);',
		'--lanspeed-radius-control:calc(var(--radius-base,.5rem)*1.5);',
		'--lanspeed-radius-input:calc(var(--radius-base,.5rem)*2);',
		'--lanspeed-radius-button:calc(var(--radius-base,.5rem)*1.5);',
		'--lanspeed-radius-compact:calc(var(--radius-base,.5rem)*.75);',
		'--lanspeed-radius-badge:999px;--lanspeed-shadow-section:var(--app-shadow-sm);',
		'--lanspeed-shadow-raised:var(--app-shadow-md,var(--app-shadow-sm));',
		'--lanspeed-disabled-opacity:var(--app-opacity-disabled,.4);',
		'--lanspeed-page-gap:calc(var(--spacing,.25rem)*4);',
		'--lanspeed-section-x:calc(var(--spacing,.25rem)*5);',
		'--lanspeed-section-y:calc(var(--spacing,.25rem)*4);',
		'--lanspeed-control-height:calc(var(--spacing,.25rem)*10);',
		'--lanspeed-transition:120ms ease;color:var(--lanspeed-text)}',

	ROOT + '>:is(.cbi-section,.lanspeed-config-subsection,.lanspeed-ifcfg){margin:0;padding:0;',
		'overflow:hidden;border:1px solid var(--lanspeed-border);',
		'border-radius:var(--lanspeed-radius-section);background-color:var(--lanspeed-surface);',
		'box-shadow:var(--lanspeed-shadow-section);color:var(--lanspeed-text)}',
	ROOT + ' :is(.lanspeed-header,.lanspeed-config-subheader,.lanspeed-diagnostics-header,.lanspeed-details>summary){',
		'border-bottom-color:var(--lanspeed-border);background-color:var(--lanspeed-surface-raised)}',
	ROOT + ' :is(.meta,.sum,.hint,.muted,.lanspeed-hint,.lanspeed-diagnostics-meta,',
		'.lanspeed-diagnostics-privacy,.lanspeed-diagnostic-description,.lanspeed-diagnostic-meta,',
		'.lanspeed-diagnostic-panel-description,.lanspeed-diagnostic-panel-meta,',
		'.lanspeed-diagnostic-fact-label,.lanspeed-diagnostic-stage-meta,',
		'.lanspeed-connection-breadcrumb-current,.lanspeed-connection-client-kicker,',
		'.lanspeed-connection-meta-heading-label,.lanspeed-connection-meta-label,',
		'.lanspeed-connection-summary-label,.lanspeed-connection-footer){',
		'color:var(--lanspeed-text-muted);opacity:1}',

	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea){min-height:var(--lanspeed-control-height);',
		'border-color:var(--lanspeed-control-border)!important;border-radius:var(--lanspeed-radius-input)!important;',
		'background-color:var(--lanspeed-control-bg)!important;color:var(--lanspeed-text)!important;',
		'box-shadow:var(--app-shadow-sm);transition:border-color var(--lanspeed-transition),',
		'box-shadow var(--lanspeed-transition),background-color var(--lanspeed-transition)}',
	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea):hover:not(:disabled){border-color:var(--lanspeed-accent-safe)!important}',
	ROOT + ' :is(.cbi-input-text,.cbi-input-select,input[type="search"],input[type="text"],',
		'input[type="number"],select,textarea):focus-visible{outline:0!important;',
		'border-color:var(--lanspeed-focus-color)!important;box-shadow:var(--lanspeed-focus-ring)!important}',
	ROOT + ' :is(input[type="search"],input[type="text"],input[type="number"],textarea)::placeholder{',
		'color:var(--lanspeed-text-muted)!important;opacity:1}',
	ROOT + ' :is(input[type="checkbox"],input[type="radio"]){accent-color:var(--lanspeed-accent-safe);color:var(--lanspeed-text)!important}',
	ROOT + ' :is(input[type="checkbox"],input[type="radio"]):focus-visible{',
		'outline:2px solid var(--lanspeed-focus-color);outline-offset:3px}',

	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button){border-color:var(--lanspeed-control-border)!important;',
		'border-radius:var(--lanspeed-radius-button);background-color:var(--lanspeed-surface-muted)!important;',
		'color:var(--lanspeed-text)!important;transition:border-color var(--lanspeed-transition),',
		'box-shadow var(--lanspeed-transition),background-color var(--lanspeed-transition),color var(--lanspeed-transition)}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):hover:not(:disabled){',
		'border-color:var(--lanspeed-control-border)!important;',
		'background-color:var(--lanspeed-surface-muted)!important;box-shadow:none!important}',
	ROOT + ' .cbi-button.cbi-button-action{border-color:var(--lanspeed-action-border)!important;',
		'background-color:var(--lanspeed-action-bg)!important;color:var(--lanspeed-action-text)!important}',
	ROOT + ' .cbi-button.cbi-button-action:hover:not(:disabled){border-color:var(--lanspeed-action-border)!important;',
		'background-color:var(--lanspeed-action-bg)!important;color:var(--lanspeed-action-text)!important}',
	'.cbi-page-actions[data-lanspeed-theme="aurora"][data-lanspeed-color-mode] ',
		':is(.cbi-button-save,.cbi-button-apply,.cbi-button-reset):hover:not(:disabled):not(:focus-visible){',
		'box-shadow:none!important}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):focus-visible{outline:0!important;',
		'border-color:var(--lanspeed-focus-color)!important;box-shadow:var(--lanspeed-focus-ring)!important}',
	ROOT + ' :is(.cbi-button,.lanspeed-ifcfg-seg>button):disabled,' + ROOT + ' [aria-disabled="true"]{',
		'opacity:var(--lanspeed-disabled-opacity)}',
	ROOT + ' :is(.lanspeed-ifcfg-seg>button.active,.lanspeed-connection-protocol[aria-pressed="true"]){',
		'border-color:var(--lanspeed-accent-safe)!important;background-color:var(--lanspeed-accent-soft)!important;',
		'color:var(--lanspeed-text)!important;box-shadow:none}',
	ROOT + ' .lanspeed-connection-protocol[aria-pressed="true"]:hover:not(:disabled){',
		'border-color:var(--lanspeed-accent-safe)!important;background-color:var(--lanspeed-accent-soft)!important;',
		'color:var(--lanspeed-text)!important;box-shadow:none!important}',

	ROOT + ' .label{display:inline-flex;align-items:center;justify-content:center;max-width:100%;',
		'padding:.2rem .65rem;border:1px solid transparent!important;border-radius:var(--lanspeed-radius-badge);',
		'background-color:var(--lanspeed-surface-muted)!important;color:var(--lanspeed-text)!important;',
		'font-size:.72rem;font-weight:700;line-height:1.25;text-shadow:none}',
	ROOT + ' .label.label-success{border-color:transparent!important;background-color:var(--brand-subtle)!important;color:var(--lanspeed-normal-text,var(--brand))!important}',
	ROOT + ' .label.label-warning{border-color:transparent!important;background-color:var(--warning-surface)!important;color:var(--warning)!important}',
	ROOT + ' .label.label-danger{border-color:transparent!important;background-color:var(--danger-surface)!important;color:var(--danger)!important}',
	ROOT + ' .cbi-button.cbi-button-remove{border-color:var(--lanspeed-danger-border)!important;',
		'background-color:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-danger)!important}',

	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) :is(th,td){border-color:var(--lanspeed-border)}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) thead th{color:var(--lanspeed-text-muted);background-color:var(--lanspeed-surface-muted)}',
	ROOT + ' :is(.lanspeed-table,.lanspeed-config-table,.lanspeed-ifcfg-table,',
		'.lanspeed-diagnostic-interface-table,.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
		'.lanspeed-diagnostics-rpc-table) tbody tr:hover{',
		'background-color:transparent!important;background-image:none!important}',
	ROOT + ' :is(.lanspeed-empty,.lanspeed-connection-empty,.lanspeed-diagnostic-alert-empty){',
		'border:1px dashed var(--lanspeed-border-strong);border-radius:var(--lanspeed-radius-control);',
		'background-color:var(--lanspeed-surface-muted);color:var(--lanspeed-text-muted)}',
	ROOT + ' :is(.alert-message.error,.lanspeed-connection-error,.lanspeed-diagnostics-error,',
		'.lanspeed-state-message[data-state="error"]){border-color:var(--lanspeed-danger-border)!important;',
		'background-color:var(--lanspeed-danger-soft)!important;color:var(--lanspeed-danger)!important}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="loading"]{color:var(--lanspeed-info)}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="ready"]{color:var(--lanspeed-normal-text)}',
	ROOT + ' :is(.status,.lanspeed-state-message)[data-state="error"]{color:var(--lanspeed-danger)}',
	ROOT + ' :is(.lanspeed-sort-button,.lanspeed-connection-link):focus-visible{',
		'outline:2px solid var(--lanspeed-focus-color);outline-offset:3px}',
	'@media (max-width:700px){#floating-toolbar~#maincontent #view{',
		'padding-right:calc(var(--spacing,.25rem)*12)}',
	'#floating-toolbar~#maincontent ' + ROOT + '{width:100%!important;max-width:none!important;margin-right:0}}'
].join('\n');

return baseclass.extend({
	CSS: AURORA_CSS
});
