'use strict';
'require baseclass';

/*
 * Theme-neutral diagnostics structure.  The shell deliberately uses one
 * section surface per major task; all descendants are bands, lists or tables
 * so a theme never needs to build a card inside another card.
 */
var BASE_CSS = [
	'.lanspeed-diagnostics-root{display:flex;flex-direction:column;gap:var(--lanspeed-page-gap);',
		'margin:0;min-width:0;color:var(--lanspeed-text)}',
	'.lanspeed-diagnostics-root>.cbi-section{padding:0;min-width:0;background:var(--lanspeed-surface);font-weight:400}',
	'.lanspeed-diagnostics-root .lanspeed-header{display:flex;flex-wrap:wrap;align-items:center;',
		'gap:.4em 1em;margin:0;padding:var(--lanspeed-section-y) var(--lanspeed-section-x) .78em;',
		'border-bottom:1px solid var(--lanspeed-border);min-width:0}',
	'.lanspeed-diagnostics-root .lanspeed-header>h3{display:inline;flex:0 0 auto;width:auto;',
		'margin:0;padding:0;border:0;background:transparent;box-shadow:none;color:var(--lanspeed-text);',
		'font-weight:600;letter-spacing:0;line-height:1.25}',
	'.lanspeed-diagnostics-root .lanspeed-header>.spacer{flex:1 1 auto}',
	'.lanspeed-diagnostics-root .lanspeed-header>.sum,',
	'.lanspeed-diagnostics-root .lanspeed-header>.meta{min-width:0;color:var(--lanspeed-text-muted);',
		'font-size:.8em;line-height:1.35;overflow-wrap:anywhere;text-align:right}',
	'.lanspeed-diagnostics-root .lanspeed-header>.cbi-button{flex:0 0 auto;white-space:nowrap}',
	'.lanspeed-diagnostics-root .lanspeed-body{min-width:0;padding:var(--lanspeed-section-y) var(--lanspeed-section-x)}',

	'.lanspeed-diagnostics-summary-body{display:grid;gap:.8em}',
	'.lanspeed-diagnostics-intro{margin:0;color:var(--lanspeed-text-muted);font-size:.88em;line-height:1.5}',
	'.lanspeed-diagnostics-state{display:flex;align-items:flex-start;gap:.55em;min-width:0;',
		'margin:0;padding:.65em .75em;border:1px solid var(--lanspeed-info-border);',
		'border-left:.22em solid var(--lanspeed-info);border-radius:var(--lanspeed-radius-control);',
		'background:var(--lanspeed-info-soft);color:var(--lanspeed-text);font-size:.84em;line-height:1.45}',
	'.lanspeed-diagnostics-state[data-state="ready"]{border-color:var(--lanspeed-normal-border);',
		'border-left-color:var(--lanspeed-normal);background:var(--lanspeed-normal-soft)}',
	'.lanspeed-diagnostics-state[data-state="degraded"],',
	'.lanspeed-diagnostics-state[data-state="partial"],',
	'.lanspeed-diagnostics-state[data-state="empty"]{border-color:var(--lanspeed-warning-border);',
		'border-left-color:var(--lanspeed-warning);background:var(--lanspeed-warning-soft)}',
	'.lanspeed-diagnostics-state[data-state="error"],',
	'.lanspeed-diagnostics-state[data-state="invalid"]{border-color:var(--lanspeed-danger-border);',
		'border-left-color:var(--lanspeed-danger);background:var(--lanspeed-danger-soft)}',
	'.lanspeed-diagnostics-state strong{flex:0 0 auto;font-weight:650}',
	'.lanspeed-diagnostics-state span{min-width:0;overflow-wrap:anywhere}',
	'.lanspeed-diagnostics-restart-feedback[hidden]{display:none!important}',
	'.lanspeed-diagnostics-error-details{margin:0;border-top:1px solid var(--lanspeed-border);',
		'padding-top:.7em;color:var(--lanspeed-text)}',
	'.lanspeed-diagnostics-error-details>summary{cursor:pointer;color:var(--lanspeed-danger);font-size:.84em;font-weight:650}',
	'.lanspeed-diagnostics-error-list{display:grid;gap:.35em;margin:.55em 0 0;padding-left:1.25em;',
		'font-size:.8em;line-height:1.45}',
	'.lanspeed-diagnostics-error-list li{min-width:0;overflow-wrap:anywhere}',
	'.lanspeed-diagnostics-error-list li[data-state="stale"],',
	'.lanspeed-diagnostics-error-list li[data-state="degraded"]{color:var(--lanspeed-warning)}',
	'.lanspeed-diagnostics-error-list li[data-state="error"],',
	'.lanspeed-diagnostics-error-list li[data-state="invalid"]{color:var(--lanspeed-danger)}',

	'.lanspeed-diagnostics-facts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));',
		'gap:0;margin:0;padding:0;min-width:0}',
	'.lanspeed-diagnostic-fact{display:grid;grid-template-columns:minmax(0,1fr);gap:.22em;',
		'min-width:0;min-height:4.6em;padding:.15em .9em;border-left:1px solid var(--lanspeed-border)}',
	'.lanspeed-diagnostic-fact:first-child{padding-left:0;border-left:0}',
	'.lanspeed-diagnostic-fact-label{margin:0;color:var(--lanspeed-text-muted);font-size:.73em;font-weight:650;',
		'line-height:1.3}',
	'.lanspeed-diagnostic-fact-value{margin:0;color:var(--lanspeed-text);font-size:1.04em;font-weight:650;',
		'line-height:1.3;overflow-wrap:anywhere}',
	'.lanspeed-diagnostic-fact-meta{margin:0;color:var(--lanspeed-text-muted);font-size:.72em;line-height:1.35;',
		'overflow-wrap:anywhere}',
	'.lanspeed-diagnostic-fact[data-state="good"] .lanspeed-diagnostic-fact-value{color:var(--lanspeed-normal-text)}',
	'.lanspeed-diagnostic-fact[data-state="warning"] .lanspeed-diagnostic-fact-value{color:var(--lanspeed-warning)}',
	'.lanspeed-diagnostic-fact[data-state="bad"] .lanspeed-diagnostic-fact-value{color:var(--lanspeed-danger)}',
	'.lanspeed-diagnostic-fact[data-state="loading"] .lanspeed-diagnostic-fact-value{color:var(--lanspeed-info)}',

	'.lanspeed-diagnostics-pipeline{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));',
		'gap:0;margin:0;padding:0;list-style:none;min-width:0}',
	'.lanspeed-diagnostic-stage{display:grid;grid-template-rows:auto auto 1fr auto auto;gap:.25em;',
		'min-width:0;min-height:8.5em;padding:.1em .9em;border-left:1px solid var(--lanspeed-border)}',
	'.lanspeed-diagnostic-stage:first-child{padding-left:0;border-left:0}',
	'.lanspeed-diagnostic-stage-heading{display:flex;align-items:center;justify-content:space-between;',
		'gap:.5em;min-width:0}',
	'.lanspeed-diagnostic-stage-heading>h4{min-width:0;margin:0;padding:0;border:0;background:transparent;',
		'box-shadow:none;color:var(--lanspeed-text-muted);font-size:.74em;font-weight:650;line-height:1.3;',
		'overflow-wrap:anywhere}',
	'.lanspeed-diagnostic-stage-badge{flex:0 0 auto;margin:0;white-space:nowrap;font-size:.68em}',
	'.lanspeed-diagnostic-stage-value{min-width:0;color:var(--lanspeed-text);font-size:1em;font-weight:650;',
		'line-height:1.3;overflow-wrap:anywhere}',
	'.lanspeed-diagnostic-stage[data-state="good"] .lanspeed-diagnostic-stage-value{color:var(--lanspeed-normal-text)}',
	'.lanspeed-diagnostic-stage[data-state="warning"] .lanspeed-diagnostic-stage-value{color:var(--lanspeed-warning)}',
	'.lanspeed-diagnostic-stage[data-state="bad"] .lanspeed-diagnostic-stage-value{color:var(--lanspeed-danger)}',
	'.lanspeed-diagnostic-stage[data-state="loading"] .lanspeed-diagnostic-stage-value{color:var(--lanspeed-info)}',
	'.lanspeed-diagnostic-stage-description{min-width:0;margin:0;color:var(--lanspeed-text-muted);',
		'font-size:.78em;line-height:1.4;overflow-wrap:anywhere}',
	'.lanspeed-diagnostic-stage-meta{min-width:0;margin:0;font-family:var(--font-mono,var(--font-monospace,ui-monospace,monospace));',
		'font-size:.7em;line-height:1.35;overflow-wrap:anywhere}',
	'.lanspeed-diagnostic-stage-evidence{display:grid;grid-template-columns:auto minmax(0,1fr);gap:.15em .5em;',
		'min-width:0;margin:.25em 0 0;padding-top:.35em;border-top:1px solid var(--lanspeed-border);',
		'font-size:.7em;line-height:1.35}',
	'.lanspeed-diagnostic-stage-evidence dt{min-width:0;color:var(--lanspeed-text-muted);overflow-wrap:anywhere}',
	'.lanspeed-diagnostic-stage-evidence dd{min-width:0;margin:0;color:var(--lanspeed-text);font-weight:600;',
		'overflow-wrap:anywhere;text-align:right}',

	'.lanspeed-diagnostics-health-body{display:grid;gap:1.05em;min-width:0}',
	'.lanspeed-diagnostics-health-group{min-width:0}',
	'.lanspeed-diagnostics-health-group>h4,.lanspeed-diagnostics-alert-group>h4{margin:0 0 .55em;',
		'padding:0;color:var(--lanspeed-text);font-size:.86em;font-weight:650;line-height:1.35}',
	'.lanspeed-diagnostics-table-wrap{min-width:0;max-width:100%;overflow-x:auto}',
	'.lanspeed-diagnostics-health-table,.lanspeed-diagnostics-subsystem-table,',
	'.lanspeed-diagnostics-rpc-table{width:100%;min-width:32em;border-collapse:collapse;margin:0;',
		'color:var(--lanspeed-text);font-size:.82em;table-layout:auto}',
	'.lanspeed-diagnostics-health-table caption,.lanspeed-diagnostics-subsystem-table caption,',
	'.lanspeed-diagnostics-rpc-table caption{padding:0 0 .45em;color:var(--lanspeed-text-muted);',
		'font-size:.9em;text-align:left;caption-side:top}',
	'.lanspeed-diagnostics-health-table :is(th,td),.lanspeed-diagnostics-subsystem-table :is(th,td),',
	'.lanspeed-diagnostics-rpc-table :is(th,td){padding:.48em .55em;border-bottom:1px solid var(--lanspeed-border);',
		'background:transparent;text-align:left;vertical-align:middle;overflow-wrap:anywhere}',
	'.lanspeed-diagnostics-health-table th,.lanspeed-diagnostics-subsystem-table th,',
	'.lanspeed-diagnostics-rpc-table th{color:var(--lanspeed-text-muted);font-weight:650;white-space:nowrap}',
	'.lanspeed-diagnostics-health-table tbody tr:last-child td,.lanspeed-diagnostics-subsystem-table tbody tr:last-child td,',
	'.lanspeed-diagnostics-rpc-table tbody tr:last-child td{border-bottom:0}',
	'.lanspeed-diagnostics-health-table tbody tr[data-state="warning"],',
	'.lanspeed-diagnostics-subsystem-table tbody tr[data-state="warning"],',
	'.lanspeed-diagnostics-rpc-table tbody tr[data-state="warning"]{color:var(--lanspeed-warning)}',
	'.lanspeed-diagnostics-health-table tbody tr[data-state="bad"],',
	'.lanspeed-diagnostics-subsystem-table tbody tr[data-state="bad"],',
	'.lanspeed-diagnostics-rpc-table tbody tr[data-state="bad"]{color:var(--lanspeed-danger)}',
	'.lanspeed-diagnostics-health-table tbody tr[data-state="empty"],',
	'.lanspeed-diagnostics-subsystem-table tbody tr[data-state="empty"]{color:var(--lanspeed-text-muted)}',
	'.lanspeed-diagnostics-health-table tbody tr:hover,.lanspeed-diagnostics-subsystem-table tbody tr:hover,',
	'.lanspeed-diagnostics-rpc-table tbody tr:hover{',
		'background:transparent!important;background-image:none!important}',
	'.lanspeed-diagnostics-rpc-details{margin:0;border-top:1px solid var(--lanspeed-border);padding-top:.75em}',
	'.lanspeed-diagnostics-rpc-details>summary,.lanspeed-diagnostics-report-details>summary{cursor:pointer;',
		'color:var(--lanspeed-text);font-size:.82em;font-weight:650}',

	'.lanspeed-diagnostics-support-body{display:grid;gap:1em;min-width:0}',
	'.lanspeed-diagnostics-alert-group{min-width:0}',
	'.lanspeed-diagnostic-alerts{display:grid;gap:.45em;margin:0;padding:0;list-style:none}',
	'.lanspeed-diagnostic-alert,.lanspeed-diagnostic-alert-empty{display:grid;',
		'grid-template-columns:1.5em minmax(0,1fr);align-items:start;gap:.6em;min-width:0;',
		'padding:.62em .72em;border:1px solid var(--lanspeed-warning-border);',
		'border-left:.22em solid var(--lanspeed-warning);border-radius:var(--lanspeed-radius-control);',
		'background:var(--lanspeed-warning-soft);font-size:.82em;line-height:1.45}',
	'.lanspeed-diagnostic-alert[data-severity="critical"]{border-color:var(--lanspeed-danger-border);',
		'border-left-color:var(--lanspeed-danger);background:var(--lanspeed-danger-soft)}',
	'.lanspeed-diagnostic-alert[data-severity="info"],.lanspeed-diagnostic-alert-empty{border-color:var(--lanspeed-info-border);',
		'border-left-color:var(--lanspeed-info);background:var(--lanspeed-info-soft)}',
	'.lanspeed-diagnostic-alert-severity{display:inline-flex;align-items:center;justify-content:center;',
		'width:1.5em;height:1.5em;border:1px solid currentColor;border-radius:var(--lanspeed-radius-badge);',
		'color:var(--lanspeed-warning);font-size:.78em;font-weight:700}',
	'.lanspeed-diagnostic-alert[data-severity="critical"] .lanspeed-diagnostic-alert-severity{color:var(--lanspeed-danger)}',
	'.lanspeed-diagnostic-alert[data-severity="info"] .lanspeed-diagnostic-alert-severity,',
	'.lanspeed-diagnostic-alert-empty .lanspeed-diagnostic-alert-severity{color:var(--lanspeed-info)}',
	'.lanspeed-diagnostic-alert-text{min-width:0;color:var(--lanspeed-text);overflow-wrap:anywhere}',
	'.lanspeed-diagnostics-report-details{margin:0;border-top:1px solid var(--lanspeed-border);padding-top:.75em}',
	'.lanspeed-diagnostics-report-preview{max-width:100%;margin:.65em 0 0;padding:.7em;overflow:auto;',
		'border:1px solid var(--lanspeed-border);border-radius:var(--lanspeed-radius-compact);',
		'background:var(--lanspeed-surface-muted);color:var(--lanspeed-text);font-family:var(--font-mono,var(--font-monospace,ui-monospace,monospace));',
		'font-size:.74em;line-height:1.45;white-space:pre-wrap;overflow-wrap:anywhere}',
	'.lanspeed-diagnostics-report-feedback{display:block;min-width:0;color:var(--lanspeed-text-muted);font-size:.78em;',
		'line-height:1.4;overflow-wrap:anywhere}',
	'.lanspeed-diagnostics-report-feedback[data-state="success"]{color:var(--lanspeed-normal-text)}',
	'.lanspeed-diagnostics-report-feedback[data-state="loading"]{color:var(--lanspeed-info)}',
	'.lanspeed-diagnostics-report-feedback[data-state="error"]{color:var(--lanspeed-danger)}',

	'@media (prefers-reduced-motion:reduce){.lanspeed-diagnostics-root *{transition-duration:.01ms!important;',
		'animation-duration:.01ms!important;animation-iteration-count:1!important}}'
].join('\n');

return baseclass.extend({
	CSS: BASE_CSS
});
