'use strict';
'require baseclass';

/* Theme-neutral status information architecture. Visual values come from the product tokens. */
var BASE_CSS = [
	'.lanspeed-root{display:flex;flex-direction:column;gap:var(--lanspeed-page-gap);margin:0;font-weight:400}',
	'.lanspeed-root .cbi-section{font-weight:400}',

	'.lanspeed-header{display:flex;flex-wrap:wrap;gap:.4em 1em;align-items:center;',
		'padding:var(--lanspeed-section-y) var(--lanspeed-section-x) .78em;margin:0;',
		'border-bottom:1px solid var(--lanspeed-border)}',
	'.lanspeed-header>h3{display:inline;flex:0 0 auto;width:auto;margin:0;padding:0;border:0;',
		'background:transparent;box-shadow:none;color:var(--lanspeed-text);font-weight:600;',
		'letter-spacing:0;line-height:1.25}',
	'.lanspeed-header>.spacer{flex:1 1 auto}',
	'.lanspeed-header>.meta{font-size:.8em;white-space:normal;text-align:right;',
		'font-family:var(--font-mono,var(--font-monospace,ui-monospace,monospace))}',
	'.lanspeed-header .lanspeed-collector-status{',
		'flex:0 0 auto;white-space:nowrap}',
	'.lanspeed-body{padding:var(--lanspeed-section-y) var(--lanspeed-section-x)}',
	'.lanspeed-root .alert-message{margin:0 0 var(--lanspeed-section-y);border-radius:var(--lanspeed-radius-control)}',
	'.lanspeed-root .alert-message pre{max-width:100%;overflow:auto;color:inherit}',
	'.lanspeed-status-error-summary{margin:0;font-weight:600;line-height:1.45}',
	'.lanspeed-status-error-list{display:grid;gap:.3em;margin:.45em 0 0;padding-left:1.2em;',
		'font-size:.85em;line-height:1.45}',

	'.lanspeed-metrics{display:grid;grid-template-columns:repeat(5,minmax(9.5em,12.5em));',
		'gap:.9em 1.2em;align-items:start;justify-content:start;margin:0}',
	'.lanspeed-metric{min-width:0;padding-left:.8em;border-left:.2em solid var(--lanspeed-border-strong)}',
	'.lanspeed-metric:first-child{border-left-color:var(--lanspeed-accent)}',
	'.lanspeed-metric .caption{margin:0;color:var(--lanspeed-text-muted);font-size:.72em;',
		'font-weight:600;text-transform:uppercase;letter-spacing:0}',
	'.lanspeed-metric .big{margin:.12em 0;color:var(--lanspeed-text);font-size:1.55em;',
		'font-weight:650;font-variant-numeric:tabular-nums;line-height:1.2}',
	'.lanspeed-metric .hint{margin:0;font-size:.78em}',
	'.lanspeed-connection-values{display:flex;flex-wrap:wrap;gap:.18em .7em;align-items:baseline}',
	'.lanspeed-connection-stat{display:inline-flex;min-width:0;gap:.22em;align-items:baseline;white-space:nowrap}',
	'.lanspeed-connection-label{color:var(--lanspeed-text-muted);font-size:.56em;font-weight:700;',
		'letter-spacing:.025em}',
	'.lanspeed-connection-number{color:inherit;font:inherit;font-variant-numeric:tabular-nums}',

	'.lanspeed-toolbar{display:flex;flex-wrap:wrap;gap:.65em 1em;align-items:center;',
		'justify-content:space-between;margin:0 0 .9em;padding:0 0 .8em;',
		'border-bottom:1px solid var(--lanspeed-border)}',
	'.lanspeed-toolbar-left{display:grid;grid-template-columns:auto minmax(14em,1fr);',
		'flex:1 1 36em;gap:.5em;align-items:center;min-width:0}',
	'.lanspeed-toolbar-filter,.lanspeed-toolbar-right{display:flex;flex-wrap:nowrap;gap:.5em;align-items:center}',
	'.lanspeed-toolbar-filter{min-width:0;width:100%;justify-content:flex-start}',
	'.lanspeed-toolbar-right{flex:0 0 auto;justify-content:flex-end;margin-left:auto;white-space:nowrap}',
	'.lanspeed-toolbar label{display:inline-flex;gap:.35em;align-items:center;color:var(--lanspeed-text);font-size:.88em}',
	'.lanspeed-toolbar .lanspeed-active-only{display:inline-flex;gap:.45em;align-items:center;',
		'flex:0 0 auto;white-space:nowrap;line-height:1.25}',
	'.lanspeed-toolbar :is(.lanspeed-unit-control,.lanspeed-refresh-control){flex:0 0 auto;white-space:nowrap}',
	'.lanspeed-toolbar .lanspeed-unit-control select{width:7.5em!important;min-width:7.5em;max-width:7.5em}',
	'.lanspeed-toolbar .lanspeed-refresh-control select{width:6.5em!important;min-width:6.5em;max-width:6.5em}',
	'.lanspeed-toolbar .lanspeed-active-only>input[type="checkbox"],',
	'.lanspeed-toolbar .lanspeed-active-only input[type="checkbox"]{position:relative;top:auto;right:auto;',
		'flex:0 0 auto;margin:0}',
	'.lanspeed-toolbar .lanspeed-active-label{margin:0;line-height:1.25}',
	'.lanspeed-toolbar input[type="search"]{flex:1 1 auto;min-width:10em;width:100%;max-width:24em}',

	'.lanspeed-table{width:100%;margin:0;border-collapse:collapse;table-layout:auto;color:var(--lanspeed-text)}',
	'.lanspeed-table th,.lanspeed-table td{padding:.48em .6em;border-bottom:1px solid var(--lanspeed-border);',
		'background:transparent;text-align:left;vertical-align:middle}',
	'.lanspeed-table thead th{color:var(--lanspeed-text-muted);font-weight:600}',
	'.lanspeed-sort-button{display:inline-flex;align-items:center;gap:.3em;min-height:0;margin:0;',
		'padding:0!important;border:0!important;appearance:none;background:transparent!important;',
		'box-shadow:none!important;color:inherit!important;cursor:pointer;font:inherit;font-weight:inherit;',
		'line-height:inherit;text-align:inherit;text-transform:none}',
	'.lanspeed-sort-indicator{display:inline-block;min-width:.75em;color:var(--lanspeed-accent)}',
	'.lanspeed-table tbody tr:last-child td{border-bottom:0}',
	'.lanspeed-clients-card .lanspeed-table :is(th,td)[hidden]{display:none!important}',
	'.lanspeed-table th:first-child,.lanspeed-table td:first-child{padding-left:0}',
	'.lanspeed-table th:last-child,.lanspeed-table td:last-child{padding-right:0}',
	'.lanspeed-table .num{text-align:left;font-variant-numeric:tabular-nums;white-space:nowrap}',
	'.lanspeed-table .mono{font-family:var(--font-mono,var(--font-monospace,ui-monospace,monospace));',
		'font-size:.9em;white-space:nowrap}',
	'.lanspeed-table tr.idle td{color:var(--lanspeed-text-muted)}',
	'.lanspeed-table td .ipline{display:block;max-width:22em;margin-top:.15em;overflow:hidden;',
		'color:var(--lanspeed-text-muted);font-family:var(--font-mono,var(--font-monospace,ui-monospace,monospace));',
		'font-size:.8em;text-overflow:ellipsis;white-space:nowrap}',
	'.lanspeed-connection-link{display:inline-flex;min-width:0;color:inherit;text-decoration:none!important}',
	'.lanspeed-connection-link:hover{color:var(--lanspeed-accent);text-decoration:none!important}',
	'.lanspeed-table td .state{display:inline-flex;gap:.25em;flex-wrap:wrap;align-items:center}',
	'.lanspeed-clients-card .lanspeed-table{font-weight:500}',
	'.lanspeed-pagination{display:flex;flex-wrap:wrap;align-items:center;justify-content:flex-end;',
		'gap:.55em .8em;margin:.8em 0 0;padding-top:.75em;border-top:1px solid var(--lanspeed-border)}',
	'.lanspeed-page-size-control{display:inline-flex;align-items:center;gap:.4em;',
		'color:var(--lanspeed-text-muted);font-size:.84em;white-space:nowrap}',
	'.lanspeed-page-size{width:5.25em!important;min-width:5.25em;max-width:5.25em}',
	'.lanspeed-page-actions{display:flex;align-items:center;gap:.4em}',
	'.lanspeed-page-button{display:inline-flex!important;align-items:center;justify-content:center;',
		'width:2.35em;height:2.35em;min-width:2.35em;padding:0!important;line-height:1}',
	'.lanspeed-page-summary{min-width:6.5em;color:var(--lanspeed-text-muted);font-size:.82em;',
		'font-variant-numeric:tabular-nums;text-align:center}',

	'.lanspeed-details{margin:0}',
	'.lanspeed-details>summary{display:flex;flex-wrap:wrap;gap:.4em 1em;align-items:center;margin:0;',
		'padding:var(--lanspeed-section-y) var(--lanspeed-section-x) .78em;',
		'border-bottom:1px solid var(--lanspeed-border);cursor:pointer;list-style:none}',
	'.lanspeed-details>summary::-webkit-details-marker{display:none}',
	'.lanspeed-details>summary::marker{content:""}',
	'.lanspeed-details>summary::before{content:"\u25B8";display:inline-block;width:1em;flex:0 0 auto;',
		'color:var(--lanspeed-accent);font-size:.85em}',
	'.lanspeed-details[open]>summary::before{content:"\u25BE"}',
	'.lanspeed-details>summary>h3{display:inline;flex:0 0 auto;width:auto;margin:0;padding:0;border:0;',
		'background:transparent;box-shadow:none;color:var(--lanspeed-text);font-weight:600;line-height:1.25}',
	'.lanspeed-details>summary>.spacer{flex:1 1 auto}',
	'.lanspeed-details>summary .sum{font-size:.8em;text-align:right;white-space:normal;',
		'font-family:var(--font-mono,var(--font-monospace,ui-monospace,monospace))}',
	'.lanspeed-details-body{margin:0;padding:var(--lanspeed-section-y) var(--lanspeed-section-x)}',

	'.lanspeed-empty{margin:.5em 0;padding:1.2em;text-align:center}',
	'.lanspeed-hint{margin:.8em 0 0;font-size:.85em}'
].join('\n');

return baseclass.extend({
	CSS: BASE_CSS
});
