'use strict';
'require baseclass';

/* Theme-neutral layout CSS shared by all LuCI themes. */
var BASE_CSS = [
	'.lanspeed-root .cbi-section{font-weight:400}',

	'.lanspeed-header{display:flex;flex-wrap:wrap;gap:.4em 1em;align-items:baseline;',
	'  padding:1em 1.25em .75em 1.25em;margin:0;',
	'  border-bottom:1px solid var(--border,rgba(128,128,128,.25))}',
	'.lanspeed-header>h3{margin:0;padding:0;border:0;width:auto;display:inline;flex:0 0 auto;',
	'  background:transparent;box-shadow:none;line-height:1.25;font-weight:600}',
	'.lanspeed-header>.spacer{flex:1 1 auto}',
	'.lanspeed-header>.meta{font-size:.85em;opacity:.75;white-space:nowrap;',
	'  font-family:var(--font-monospace,ui-monospace,monospace)}',
	'.lanspeed-header .label{margin-left:0}',
	'.lanspeed-body{padding:1.15em 1.25em}',

	'.lanspeed-metrics{display:grid;grid-template-columns:repeat(5,12.5em);',
	'  row-gap:1.1em;column-gap:1.2em;align-items:center;justify-content:start;margin:0}',
	'@media (max-width:1100px){.lanspeed-metrics{grid-template-columns:repeat(auto-fit,minmax(10em,1fr))}}',
	'.lanspeed-metric{min-width:0}',
	'.lanspeed-metric .caption{font-size:.75em;text-transform:uppercase;letter-spacing:.04em;opacity:.7;margin:0}',
	'.lanspeed-metric .big{font-size:1.6em;font-weight:600;font-variant-numeric:tabular-nums;',
	'  line-height:1.2;margin:.1em 0}',
	'.lanspeed-metric .hint{font-size:.8em;opacity:.7;margin:0}',

	'.lanspeed-toolbar{display:flex;flex-wrap:wrap;gap:.7em 1em;',
	'  align-items:center;justify-content:space-between;margin:0 0 1em 0}',
	'.lanspeed-toolbar-left{display:grid;grid-template-columns:auto minmax(14em,1fr);',
	'  flex:1 1 36em;gap:.5em;align-items:center;min-width:0}',
	'.lanspeed-toolbar-filter,.lanspeed-toolbar-right{',
	'  display:flex;flex-wrap:nowrap;gap:.5em;align-items:center}',
	'.lanspeed-toolbar-filter{min-width:0;width:100%;justify-content:flex-start}',
	'.lanspeed-toolbar-right{flex:0 0 auto;justify-content:flex-end;margin-left:auto;white-space:nowrap}',
	'.lanspeed-toolbar label{display:inline-flex;gap:.3em;align-items:center;font-size:.9em}',
	'.lanspeed-toolbar .lanspeed-active-only{display:inline-flex;gap:.45em;',
	'  align-items:center;line-height:1.25;flex:0 0 auto;white-space:nowrap}',
	'.lanspeed-toolbar .lanspeed-unit-control,.lanspeed-toolbar .lanspeed-refresh-control{',
	'  flex:0 0 auto;white-space:nowrap}',
	'.lanspeed-toolbar .lanspeed-unit-control select{width:7.5em!important;min-width:7.5em;max-width:7.5em}',
	'.lanspeed-toolbar .lanspeed-refresh-control select{width:6.5em!important;min-width:6.5em;max-width:6.5em}',
	'.lanspeed-toolbar .lanspeed-active-only>input[type=checkbox],',
	'.lanspeed-toolbar .lanspeed-active-only input[type=checkbox]{',
	'  position:relative;top:auto;right:auto;margin:0;flex:0 0 auto}',
	'.lanspeed-toolbar .lanspeed-active-label{margin:0;line-height:1.25}',
	'.lanspeed-toolbar input[type=search]{flex:1 1 auto;min-width:10em;width:100%;max-width:24em}',
	'@media (max-width:900px){.lanspeed-toolbar-right{justify-content:flex-start;margin-left:0}}',
	'@media (max-width:600px){.lanspeed-toolbar-left{grid-template-columns:1fr;flex-basis:100%}',
	'.lanspeed-toolbar-right{flex:1 1 100%;flex-wrap:wrap}',
	'.lanspeed-toolbar-filter{min-width:0;flex:1 1 100%}',
	'.lanspeed-toolbar input[type=search]{min-width:0;max-width:none}}',

	'.lanspeed-table{width:100%;border-collapse:collapse;margin:0;table-layout:auto}',
	'.lanspeed-table th,.lanspeed-table td{padding:.45em .6em;text-align:left;',
	'  border-bottom:1px solid var(--border,rgba(128,128,128,.18));',
	'  vertical-align:middle;background:transparent}',
	'.lanspeed-table thead th{font-weight:600;opacity:.85}',
	'.lanspeed-sort-button{appearance:none;background:transparent!important;border:0!important;',
	'  box-shadow:none!important;color:inherit!important;cursor:pointer;display:inline-flex;',
	'  align-items:center;gap:.3em;font:inherit;font-weight:inherit;line-height:inherit;',
	'  min-height:0;padding:0!important;margin:0;text-align:inherit;text-transform:none}',
	'.lanspeed-sort-button:focus-visible{outline:2px solid currentColor;outline-offset:3px}',
	'.lanspeed-sort-indicator{display:inline-block;min-width:.75em;opacity:.85}',
	'.lanspeed-table tbody tr:last-child td{border-bottom:0}',
	'.lanspeed-clients-card .lanspeed-table th[hidden],',
	'.lanspeed-clients-card .lanspeed-table td[hidden]{display:none!important}',
	'.lanspeed-table th:first-child,.lanspeed-table td:first-child{padding-left:0}',
	'.lanspeed-table th:last-child,.lanspeed-table td:last-child{padding-right:0}',
	'.lanspeed-table .num{text-align:left;font-variant-numeric:tabular-nums;white-space:nowrap}',
	'.lanspeed-table .mono{font-family:var(--font-monospace,ui-monospace,monospace);',
	'  font-size:.9em;white-space:nowrap}',
	'.lanspeed-table tr.idle td{opacity:.55}',
	'.lanspeed-table td .ipline{display:block;font-size:.8em;opacity:.7;margin-top:.15em;',
	'  font-family:var(--font-monospace,ui-monospace,monospace);max-width:22em;',
	'  overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
	'.lanspeed-connection-link{display:inline-flex;min-width:0;color:inherit;text-decoration:none!important}',
	'.lanspeed-connection-link:hover{opacity:.78;text-decoration:none!important}',
	'.lanspeed-connection-link:focus-visible{outline:2px solid currentColor;outline-offset:3px;text-decoration:none!important}',
	'.lanspeed-table td .state{display:inline-flex;gap:.25em;flex-wrap:wrap;align-items:center}',
	'.lanspeed-clients-card .lanspeed-table{font-weight:500}',

	'.lanspeed-details{margin:0}',
	'.lanspeed-details>summary{cursor:pointer;list-style:none;padding:0;margin:0;',
	'  display:flex;flex-wrap:wrap;gap:.4em 1em;align-items:baseline;',
	'  padding:1em 1.25em .75em 1.25em;',
	'  border-bottom:1px solid var(--border,rgba(128,128,128,.25))}',
	'.lanspeed-details>summary::-webkit-details-marker{display:none}',
	'.lanspeed-details>summary::marker{content:""}',
	'.lanspeed-details>summary::before{content:"\u25B8";display:inline-block;',
	'  width:1em;flex:0 0 auto;opacity:.6;font-size:.85em}',
	'.lanspeed-details[open]>summary::before{content:"\u25BE"}',
	'.lanspeed-details>summary>h3{margin:0;padding:0;border:0;flex:0 0 auto;',
	'  width:auto;background:transparent;box-shadow:none;line-height:1.25;display:inline;',
	'  font-weight:600}',
	'.lanspeed-details>summary>.spacer{flex:1 1 auto}',
	'.lanspeed-details>summary .sum{font-size:.85em;opacity:.75;',
	'  font-family:var(--font-monospace,ui-monospace,monospace)}',
	'.lanspeed-details-body{margin:0;padding:1em 1.25em}',

	'.lanspeed-empty{padding:1.2em 0;text-align:center;opacity:.7}',
	'.lanspeed-hint{margin:.8em 0 0 0;font-size:.85em;opacity:.75}',

].join('\n');

return baseclass.extend({
	CSS: BASE_CSS
});
