'use strict';
'require baseclass';

/* Layout-only CSS for the live status view.
 *
 * LuCI's active theme owns colours, backgrounds, borders, button styles and
 * form controls. LAN Speed only controls flex/grid flow, table density and
 * theme-specific spacing corrections.
 */
var LAYOUT_CSS = [
	'.lanspeed-root .cbi-section{font-weight:400}',

	'.lanspeed-header{display:flex;flex-wrap:wrap;gap:.4em 1em;align-items:baseline;',
	'  padding:1em 1.25em .75em 1.25em;margin:0;',
	'  border-bottom:1px solid var(--border,rgba(128,128,128,.25))}',
	'.lanspeed-header>h3{margin:0;padding:0;border:0;width:auto;display:inline;flex:0 0 auto;',
	'  background:transparent;box-shadow:none;line-height:1.25;font-weight:600}',
	'.lanspeed-header>.spacer{flex:1 1 auto}',
	'.lanspeed-header>.meta{font-size:.85em;opacity:.75;white-space:nowrap;',
	'  font-family:var(--font-monospace,ui-monospace,monospace)}',
	'.lanspeed-header .label{margin-left:0}',
	'.lanspeed-body{padding:1.15em 1.25em}',

	'.lanspeed-metrics{display:grid;grid-template-columns:repeat(5,12.5em);',
	'  row-gap:1.1em;column-gap:1.2em;align-items:center;justify-content:start;margin:0}',
	'@media (max-width:1100px){.lanspeed-metrics{grid-template-columns:repeat(auto-fit,minmax(10em,1fr))}}',
	'.lanspeed-metric{min-width:0}',
	'.lanspeed-metric .caption{font-size:.75em;text-transform:uppercase;letter-spacing:.04em;opacity:.7;margin:0}',
	'.lanspeed-metric .big{font-size:1.6em;font-weight:600;font-variant-numeric:tabular-nums;',
	'  line-height:1.2;margin:.1em 0}',
	'.lanspeed-metric .hint{font-size:.8em;opacity:.7;margin:0}',

	'.lanspeed-strip{display:flex;flex-wrap:wrap;gap:.3em;margin:1em 0 0 0}',
	'.lanspeed-strip:empty{display:none;margin:0}',

	'.lanspeed-toolbar{display:grid;grid-template-columns:auto minmax(18em,1fr) auto;',
	'  gap:.7em 1em;align-items:center;margin:0 0 1em 0}',
	'.lanspeed-toolbar-left,.lanspeed-toolbar-filter,.lanspeed-toolbar-options{',
	'  display:flex;flex-wrap:wrap;gap:.5em;align-items:center}',
	'.lanspeed-toolbar-filter{justify-content:flex-start}',
	'.lanspeed-toolbar-options{justify-content:flex-end}',
	'.lanspeed-toolbar label{display:inline-flex;gap:.3em;align-items:center;font-size:.9em}',
	'.lanspeed-toolbar .lanspeed-active-only{display:inline-flex;gap:.45em;',
	'  align-items:center;line-height:1.25}',
	'.lanspeed-toolbar .lanspeed-active-only>input[type=checkbox],',
	'.lanspeed-toolbar .lanspeed-active-only input[type=checkbox]{',
	'  position:relative;top:auto;right:auto;margin:0;flex:0 0 auto}',
	'.lanspeed-toolbar .lanspeed-active-label{margin:0;line-height:1.25}',
	'.lanspeed-toolbar input[type=search]{min-width:16em;max-width:24em}',
	'@media (max-width:900px){.lanspeed-toolbar{grid-template-columns:1fr}',
	'.lanspeed-toolbar-options{justify-content:flex-start}}',

	'.lanspeed-table{width:100%;border-collapse:collapse;margin:0;table-layout:auto}',
	'.lanspeed-table th,.lanspeed-table td{padding:.45em .6em;text-align:left;',
	'  border-bottom:1px solid var(--border,rgba(128,128,128,.18));',
	'  vertical-align:middle;background:transparent}',
	'.lanspeed-table thead th{font-weight:600;opacity:.85}',
	'.lanspeed-table tbody tr:last-child td{border-bottom:0}',
	'.lanspeed-table th:first-child,.lanspeed-table td:first-child{padding-left:0}',
	'.lanspeed-table th:last-child,.lanspeed-table td:last-child{padding-right:0}',
	'.lanspeed-table .num{text-align:left;font-variant-numeric:tabular-nums;white-space:nowrap}',
	'.lanspeed-table .mono{font-family:var(--font-monospace,ui-monospace,monospace);',
	'  font-size:.9em;white-space:nowrap}',
	'.lanspeed-table tr.idle td{opacity:.55}',
	'.lanspeed-table td .ipline{display:block;font-size:.8em;opacity:.7;margin-top:.15em;',
	'  font-family:var(--font-monospace,ui-monospace,monospace);max-width:22em;',
	'  overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
	'.lanspeed-table td .state{display:inline-flex;gap:.25em;flex-wrap:wrap;align-items:center}',
	'.lanspeed-clients-card .lanspeed-table{font-weight:500}',

	'.lanspeed-caps{display:grid;grid-template-columns:repeat(auto-fill,minmax(15em,1fr));',
	'  gap:.3em .8em;margin:.2em 0 1em 0}',
	'.lanspeed-caps .cap{display:flex;justify-content:space-between;align-items:center;',
	'  gap:.5em;padding:.15em 0}',

	'.lanspeed-warnings{margin:.2em 0 1em 0;padding-left:1.2em}',
	'.lanspeed-warnings li{margin:.2em 0;font-size:.9em}',
	'.lanspeed-warnings li .key{margin-right:.4em}',

	'.lanspeed-subhead{margin:.2em 0 .4em 0;font-size:1em;font-weight:600;opacity:.85}',
	'.lanspeed-subhead:first-child{margin-top:0}',

	'.lanspeed-details{margin:0}',
	'.lanspeed-details>summary{cursor:pointer;list-style:none;padding:0;margin:0;',
	'  display:flex;flex-wrap:wrap;gap:.4em 1em;align-items:baseline;',
	'  padding:1em 1.25em .75em 1.25em;',
	'  border-bottom:1px solid var(--border,rgba(128,128,128,.25))}',
	'.lanspeed-details>summary::-webkit-details-marker{display:none}',
	'.lanspeed-details>summary::marker{content:""}',
	'.lanspeed-details>summary::before{content:"\u25B8";display:inline-block;',
	'  width:1em;flex:0 0 auto;opacity:.6;font-size:.85em}',
	'.lanspeed-details[open]>summary::before{content:"\u25BE"}',
	'.lanspeed-details>summary>h3{margin:0;padding:0;border:0;flex:0 0 auto;',
	'  width:auto;background:transparent;box-shadow:none;line-height:1.25;display:inline;',
	'  font-weight:600}',
	'.lanspeed-details>summary>.spacer{flex:1 1 auto}',
	'.lanspeed-details>summary .sum{font-size:.85em;opacity:.75;',
	'  font-family:var(--font-monospace,ui-monospace,monospace)}',
	'.lanspeed-details>summary .label{margin-left:0}',
	'.lanspeed-details-body{margin:0;padding:1em 1.25em}',

	'.lanspeed-empty{padding:1.2em 0;text-align:center;opacity:.7}',
	'.lanspeed-hint{margin:.8em 0 0 0;font-size:.85em;opacity:.75}',

	'.lanspeed-theme-aurora{display:flex;flex-direction:column;gap:1rem;margin:0}',
	'.lanspeed-theme-aurora>.cbi-section{margin:0;padding:0;overflow:hidden}',
	'.lanspeed-theme-aurora .lanspeed-clients-card .lanspeed-body{overflow-x:auto}',
	'.lanspeed-theme-aurora .lanspeed-header,',
	'.lanspeed-theme-aurora .lanspeed-details>summary{padding:1rem 1.25rem .85rem}',
	'.lanspeed-theme-aurora .lanspeed-body,',
	'.lanspeed-theme-aurora .lanspeed-details-body{padding:1rem 1.25rem}',
	'.lanspeed-theme-aurora .lanspeed-metrics{grid-template-columns:repeat(auto-fit,minmax(11em,12.5em));',
	'  justify-content:start;column-gap:1rem;row-gap:.9rem}',
	'.lanspeed-theme-aurora .lanspeed-metric .big{font-size:1.45rem}',
	'.lanspeed-theme-aurora .lanspeed-toolbar{grid-template-columns:auto minmax(16rem,1fr) auto;',
	'  gap:.65rem .9rem;margin-bottom:.85rem}',
	'.lanspeed-theme-aurora .lanspeed-toolbar input[type=search]{min-width:14rem;max-width:22rem}',
	'.lanspeed-theme-aurora .lanspeed-table th,',
	'.lanspeed-theme-aurora .lanspeed-table td{padding:.48rem .6rem}',
	'.lanspeed-theme-aurora .lanspeed-table .mono{font-size:.85em}',
	'.lanspeed-theme-aurora .lanspeed-clients-card .lanspeed-table td:nth-child(2).mono{font-size:.95rem}',
	'@media (min-width:901px){.lanspeed-theme-aurora .lanspeed-clients-card .lanspeed-table{table-layout:fixed}',
	'.lanspeed-theme-aurora .lanspeed-clients-card .lanspeed-table th:nth-child(1),.lanspeed-theme-aurora .lanspeed-clients-card .lanspeed-table td:nth-child(1){width:18rem}',
	'.lanspeed-theme-aurora .lanspeed-clients-card .lanspeed-table th:nth-child(2),.lanspeed-theme-aurora .lanspeed-clients-card .lanspeed-table td:nth-child(2){width:15rem}}',
	'.lanspeed-theme-aurora .lanspeed-table td .ipline{max-width:18rem}',
	'.lanspeed-theme-aurora .lanspeed-caps{grid-template-columns:repeat(auto-fit,minmax(12rem,1fr));',
	'  gap:.35rem 1rem}',
	'.lanspeed-theme-aurora .lanspeed-caps .cap{padding:.2rem 0}',
	'@media (max-width:700px){.lanspeed-theme-aurora .lanspeed-header,',
	'.lanspeed-theme-aurora .lanspeed-details>summary{padding:.85rem 1rem .7rem}',
	'.lanspeed-theme-aurora .lanspeed-body,',
	'.lanspeed-theme-aurora .lanspeed-details-body{padding:.85rem 1rem}',
	'.lanspeed-theme-aurora .lanspeed-toolbar{grid-template-columns:1fr}',
	'.lanspeed-theme-aurora .lanspeed-toolbar-options{justify-content:flex-start}}',

	'.lanspeed-theme-argon{display:flex;flex-direction:column;gap:1rem;margin:0;font-size:1rem}',
	'.lanspeed-theme-argon>.cbi-section{margin:0;padding:0;overflow:hidden}',
	'.lanspeed-theme-argon .lanspeed-clients-card .lanspeed-body{overflow-x:auto}',
	'.lanspeed-theme-argon .lanspeed-header,',
	'.lanspeed-theme-argon .lanspeed-details>summary{padding:.95rem 1.25rem .8rem}',
	'.lanspeed-theme-argon .lanspeed-body,',
	'.lanspeed-theme-argon .lanspeed-details-body{padding:1rem 1.25rem}',
	'.lanspeed-theme-argon .lanspeed-metrics{grid-template-columns:repeat(auto-fit,minmax(10.5em,12.5em));',
	'  justify-content:start;gap:.9rem 1rem}',
	'.lanspeed-theme-argon .lanspeed-metric .big{font-size:1.5rem}',
	'.lanspeed-theme-argon .lanspeed-toolbar{grid-template-columns:auto minmax(14rem,1fr) auto;',
	'  gap:.65rem .85rem;margin-bottom:.9rem}',
	'.lanspeed-theme-argon .lanspeed-toolbar input[type=search]{min-width:13rem;max-width:22rem}',
	'.lanspeed-theme-argon .lanspeed-header>h3,',
	'.lanspeed-theme-argon .lanspeed-details>summary>h3{font-size:1.35rem}',
	'.lanspeed-theme-argon .lanspeed-toolbar button,',
	'.lanspeed-theme-argon .lanspeed-toolbar select,',
	'.lanspeed-theme-argon .lanspeed-toolbar input{font-size:1rem}',
	'.lanspeed-theme-argon .lanspeed-table th,.lanspeed-theme-argon .lanspeed-table td{padding:.65rem .75rem;font-size:1rem;line-height:1.45}',
	'.lanspeed-theme-argon .lanspeed-table th:first-child,.lanspeed-theme-argon .lanspeed-table td:first-child{padding-left:.35rem}',
	'.lanspeed-theme-argon .lanspeed-table th:last-child,',
	'.lanspeed-theme-argon .lanspeed-table td:last-child{padding-right:0}',
	'.lanspeed-theme-argon .lanspeed-table .mono{font-size:.96rem}',
	'.lanspeed-theme-argon .lanspeed-clients-card .lanspeed-table td:nth-child(2).mono{font-size:.96rem}',
	'@media (min-width:901px){.lanspeed-theme-argon .lanspeed-clients-card .lanspeed-table{table-layout:fixed}',
	'.lanspeed-theme-argon .lanspeed-clients-card .lanspeed-table th:nth-child(1),.lanspeed-theme-argon .lanspeed-clients-card .lanspeed-table td:nth-child(1){width:17rem}',
	'.lanspeed-theme-argon .lanspeed-clients-card .lanspeed-table th:nth-child(2),.lanspeed-theme-argon .lanspeed-clients-card .lanspeed-table td:nth-child(2){width:14.5rem}}',
	'.lanspeed-theme-argon .lanspeed-table td .ipline{max-width:18rem}',
	'.lanspeed-theme-argon .lanspeed-caps{grid-template-columns:repeat(4,12.95rem);max-width:56rem;justify-content:start;align-items:center;gap:.5rem 1rem;margin:.2rem 0 1rem 1.25rem}',
	'.lanspeed-theme-argon .lanspeed-caps .cap{display:grid;grid-template-columns:minmax(0,9.65rem) 2.55rem;',
	'  align-items:center;column-gap:.45rem;min-width:0;padding:.18rem 0}',
	'.lanspeed-theme-argon .lanspeed-caps .cap>span:first-child{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
	'.lanspeed-theme-argon .lanspeed-caps .cap>span:last-child{justify-self:start;min-width:2.25rem;text-align:center}',
	'@media (max-width:700px){.lanspeed-theme-argon .lanspeed-caps{grid-template-columns:1fr;max-width:none}',
	'.lanspeed-theme-argon .lanspeed-caps .cap{grid-template-columns:minmax(0,9.65rem) 2.55rem;max-width:12.95rem}}',
	'@media (max-width:700px){.lanspeed-theme-argon .lanspeed-header,',
	'.lanspeed-theme-argon .lanspeed-details>summary{padding:.85rem 1rem .7rem}',
	'.lanspeed-theme-argon .lanspeed-body,',
	'.lanspeed-theme-argon .lanspeed-details-body{padding:.85rem 1rem;overflow-x:auto}',
	'.lanspeed-theme-argon .lanspeed-toolbar{grid-template-columns:1fr}',
	'.lanspeed-theme-argon .lanspeed-toolbar-options{justify-content:flex-start}',
	'.lanspeed-theme-argon .lanspeed-toolbar input[type=search]{min-width:0;width:100%;max-width:none}}'
].join('\n');

return baseclass.extend({
	CSS: LAYOUT_CSS
});
