'use strict';
'require baseclass';

/* Argon uses a flatter, denser rhythm with its runtime primary color as the status cue. */
var ARGON_CSS = [
	'.lanspeed-root.lanspeed-theme-argon{gap:var(--lanspeed-page-gap);font-size:1rem}',
	'.lanspeed-root.lanspeed-theme-argon>.cbi-section{padding:0}',
	'.lanspeed-theme-argon .lanspeed-clients-card .lanspeed-body{overflow-x:auto}',
	'.lanspeed-theme-argon :is(.lanspeed-header,.lanspeed-details>summary){padding:.95rem 1.25rem .8rem}',
	'.lanspeed-theme-argon :is(.lanspeed-body,.lanspeed-details-body){padding:1rem 1.25rem}',
	'.lanspeed-theme-argon :is(.lanspeed-header,.lanspeed-details>summary) h3{',
		'font-size:1.3rem;line-height:1.25!important}',
	'.lanspeed-theme-argon .lanspeed-header>.meta,',
	'.lanspeed-theme-argon .lanspeed-details>summary .sum{padding-left:.55rem;',
		'border-left:.18rem solid var(--lanspeed-accent)}',
	'.lanspeed-theme-argon .lanspeed-metrics{grid-template-columns:repeat(4,minmax(0,1fr));',
		'gap:.85rem 1rem}',
	'.lanspeed-theme-argon .lanspeed-metric{border-left-width:.18rem}',
	'.lanspeed-theme-argon .lanspeed-metric .big{font-size:1.5rem}',
	'.lanspeed-theme-argon .lanspeed-toolbar{gap:.65rem .85rem;margin-bottom:.9rem}',
	'.lanspeed-theme-argon .lanspeed-toolbar label{font-size:.95rem;line-height:1.5rem}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card{overflow:hidden}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-header{',
		'background:var(--lanspeed-surface-raised);border-bottom-color:var(--lanspeed-border-strong)}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-header>h3{',
		'font-weight:650;letter-spacing:.01em}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-header>.meta{',
		'font-size:.82rem;line-height:1.4;white-space:nowrap}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-body{',
		'padding:.9rem 1.25rem 1rem}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-toolbar{',
		'border-bottom-color:var(--lanspeed-border-strong)}',
	'.lanspeed-root.lanspeed-theme-argon .lanspeed-active-only>input[type="checkbox"]{',
		'position:static;top:auto;right:auto;bottom:auto;left:auto;vertical-align:middle}',
	'.lanspeed-theme-argon .lanspeed-toolbar input[type="search"]{min-width:13rem;max-width:22rem}',
	'.lanspeed-theme-argon .lanspeed-table :is(th,td){padding:.62rem .72rem;font-size:.96rem;line-height:1.45}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table thead th{',
		'background:var(--lanspeed-surface-sunken);color:var(--lanspeed-text);',
		'border-bottom:1px solid var(--lanspeed-border-strong);font-size:.82rem;',
		'font-weight:650;line-height:1.3;white-space:nowrap}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table tbody td{',
		'font-variant-numeric:tabular-nums}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table tbody td:first-child{',
		'font-weight:600;font-variant-numeric:normal}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table tbody td:nth-child(2){',
		'border-left:1px solid var(--lanspeed-border);padding-left:.9rem}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table tbody td:last-child{',
		'border-left:1px solid var(--lanspeed-border);padding-left:.9rem}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table thead th:nth-child(2),',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table thead th:last-child{',
		'border-left:1px solid var(--lanspeed-border);padding-left:.9rem}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table :is(th,td):nth-child(2){',
		'border-left:0!important;padding-left:.72rem}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table :is(th,td):last-child{',
		'border-left:0!important;padding-left:.72rem}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table.lanspeed-custom-column-layout :is(th,td):nth-child(1),',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table.lanspeed-custom-column-layout :is(th,td):nth-child(2){',
		'box-shadow:none!important}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table.lanspeed-custom-column-layout[data-client-control="shown"] :is(th,td):nth-child(9),',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table.lanspeed-custom-column-layout[data-client-control="hidden"] :is(th,td):nth-child(8){',
		'box-shadow:-1px 0 0 var(--lanspeed-border)!important}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table.lanspeed-custom-column-layout tbody>tr{',
		'border-bottom:0!important}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-table.lanspeed-custom-column-layout tbody>tr :is(th,td){',
		'border-bottom:0!important}',
	'.lanspeed-theme-argon .lanspeed-sort-button{height:auto!important;min-height:0!important;line-height:1.35!important}',
	'.lanspeed-theme-argon .lanspeed-table :is(th,td):first-child{padding-left:.35rem}',
	'.lanspeed-theme-argon .lanspeed-table :is(th,td):last-child{padding-right:0}',
	'.lanspeed-theme-argon .lanspeed-table .mono{font-size:.94rem}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-client-name .ipline{',
		'font-size:.8rem;line-height:1.3;opacity:.8}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-control-actions{',
		'justify-content:center;gap:.5rem}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-control-button{',
		'min-width:6rem;width:6rem;min-height:2.4rem!important}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-client-control{',
		'text-align:center;vertical-align:middle}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-pagination{',
		'border-top-color:var(--lanspeed-border-strong);padding-top:.8rem}',
	'.lanspeed-theme-argon .lanspeed-table tbody tr:nth-child(odd):hover{',
		'background:transparent!important;background-image:none!important}',
	'.lanspeed-theme-argon .lanspeed-table tbody tr:nth-child(even),',
	'.lanspeed-theme-argon .lanspeed-table tbody tr:nth-child(even):hover{',
		'background:var(--lanspeed-native-row-stripe)!important;background-image:none!important}',
	'.lanspeed-theme-argon .lanspeed-connection-link:link,',
	'.lanspeed-theme-argon .lanspeed-connection-link:visited,',
	'.lanspeed-theme-argon .lanspeed-connection-link:active,',
	'.lanspeed-theme-argon .lanspeed-connection-link:hover{',
		'color:var(--lanspeed-link-safe,var(--lanspeed-accent))!important;',
		'text-decoration:none!important}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-ifaces-table thead th{',
		'background:var(--lanspeed-surface-sunken);color:var(--lanspeed-text);',
		'border-bottom:1px solid var(--lanspeed-border-strong);font-weight:650}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-ifaces-table tbody tr{border-bottom:0!important}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-ifaces-table tbody td{border-bottom:0!important}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-ifaces-table tbody td:first-child{font-weight:600}',
	'.lanspeed-theme-argon .lanspeed-hint:empty{display:none}',
	'.lanspeed-theme-argon .lanspeed-table td .ipline{max-width:18rem}',
	'@media (max-width:1100px){.lanspeed-theme-argon .lanspeed-metrics{',
		'grid-template-columns:repeat(2,minmax(0,1fr))}}',
	'@media (max-width:700px){',
	'.lanspeed-theme-argon :is(.lanspeed-header,.lanspeed-details>summary){padding:.85rem 1rem .7rem}',
	'.lanspeed-theme-argon :is(.lanspeed-body,.lanspeed-details-body){padding:.85rem 1rem}',
	'.lanspeed-theme-argon .lanspeed-toolbar input[type="search"]{min-width:0;width:100%;max-width:none}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-header>.meta{',
		'white-space:normal;text-align:right}',
	'.lanspeed-root.lanspeed-theme-argon[data-lanspeed-platform="x86"] .lanspeed-clients-card .lanspeed-body{',
		'padding:.85rem 1rem .9rem}}',
	'@media (max-width:480px){.lanspeed-theme-argon .lanspeed-metrics{',
		'grid-template-columns:repeat(2,minmax(0,1fr))}',
	'.lanspeed-theme-argon .lanspeed-metric .big{font-size:1.3rem}}'
].join('\n');

return baseclass.extend({
	CSS: ARGON_CSS
});
