[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[net]
offline = true

[target.bpfel-unknown-none]
linker = "bpf-linker"
rustflags = ["-C", "debuginfo=2", "-C", "link-arg=--btf"]
